var SianArt = globalThis.SianArt || {};
SianArt.artworks = [
  {
    id: "starry-night", title: "별이 빛나는 밤", originalTitle: "The Starry Night", artist: "빈센트 반 고흐", artistKey: "van-gogh", country: "네덜란드", year: "1889", museum: "뉴욕 현대미술관 (MoMA)", difficulty: "easy",
    story: "고흐가 밤하늘을 힘차게 움직이는 것처럼 그렸어요. 별과 달, 소용돌이치는 선을 찾아보세요.", look: "커다란 소용돌이와 노란 별, 아래쪽의 조용한 마을을 찾아보세요.", image: "assets/art-puzzle/starry-night.jpg", source: "https://www.moma.org/collection/works/79802", publicDomain: true,
    imageSource: "https://commons.wikimedia.org/wiki/File:Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg", imageLicense: "Public domain",
  },
  {
    id: "28560",
    title: "침실",
    originalTitle: "The Bedroom",
    artist: "빈센트 반 고흐",
    country: "네덜란드",
    year: "1889",
    story: "고흐가 지내던 방이에요. 침대와 의자가 우리를 반겨요.",
    look: "의자는 몇 개일까요? 벽에 걸린 그림도 찾아보세요.",
    image: "assets/art-puzzle/28560.jpg",
    source: "https://www.artic.edu/artworks/28560",
    apiSource: "https://api.artic.edu/api/v1/artworks/28560",
    publicDomain: true,
    imageId: "6644829f-f292-c5c4-a73c-0356a6fdbf0d",
    imageSource:
      "https://commons.wikimedia.org/wiki/File:1926.417_-_The_Bedroom_Vincent_van_Gogh_1889.jpg",
    imageLicense: "Public domain",
  },
  { id:"80607",title:"고흐의 자화상",originalTitle:"Self-Portrait",artist:"빈센트 반 고흐",artistKey:"van-gogh",country:"네덜란드",year:"1887",museum:"시카고 미술관",difficulty:"normal",story:"고흐가 거울을 보며 자기 모습을 그렸어요. 짧고 빠른 붓질이 얼굴 주위를 흐릅니다.",look:"배경과 옷에 반복되는 파란 붓자국을 찾아보세요.",image:"https://www.artic.edu/iiif/2/47c5bcb8-62ef-e5d7-55e7-f5121f409a30/full/843,/0/default.jpg",source:"https://www.artic.edu/artworks/80607",publicDomain:true,imageSource:"https://www.artic.edu/artworks/80607",imageLicense:"CC0 / Public Domain" },
  { id:"14586",title:"시인의 정원",originalTitle:"The Poet's Garden",artist:"빈센트 반 고흐",artistKey:"van-gogh",country:"네덜란드",year:"1888",museum:"시카고 미술관",difficulty:"normal",story:"햇빛 아래 정원에 나무와 길이 펼쳐져요. 고흐는 자연의 리듬을 굵은 색으로 담았어요.",look:"정원의 길과 키 큰 나무가 어디로 이어지는지 살펴보세요.",image:"https://www.artic.edu/iiif/2/d4bc1723-7cbc-d36d-a9cb-f84553f2a6f6/full/843,/0/default.jpg",source:"https://www.artic.edu/artworks/14586",publicDomain:true,imageSource:"https://www.artic.edu/artworks/14586",imageLicense:"CC0 / Public Domain" },
  { id:"61603",title:"파리 오페라의 발레",originalTitle:"Ballet at the Paris Opéra",artist:"에드가 드가",artistKey:"degas",country:"프랑스",year:"1877",museum:"시카고 미술관",difficulty:"hard",story:"무대 위 무용수들의 움직임을 특별한 시점에서 바라본 그림이에요.",look:"흰 치마가 만드는 원과 악기의 긴 선을 찾아보세요.",image:"https://www.artic.edu/iiif/2/cb34b0a8-bc51-d063-aab1-47c7debf3a7b/full/843,/0/default.jpg",source:"https://www.artic.edu/artworks/61603",publicDomain:true,imageSource:"https://www.artic.edu/artworks/61603",imageLicense:"CC0 / Public Domain" },
  { id:"11723",title:"화장하는 여인",originalTitle:"Woman at Her Toilette",artist:"베르트 모리조",artistKey:"morisot",country:"프랑스",year:"1875–1880",museum:"시카고 미술관",difficulty:"master",story:"밝고 부드러운 색으로 일상의 조용한 순간을 그렸어요.",look:"거울처럼 반짝이는 부분과 빠르게 칠한 붓자국을 살펴보세요.",image:"https://www.artic.edu/iiif/2/78c80988-6524-cec7-c661-a4c0a706d06f/full/843,/0/default.jpg",source:"https://www.artic.edu/artworks/11723",publicDomain:true,imageSource:"https://www.artic.edu/artworks/11723",imageLicense:"CC0 / Public Domain" },
  { id:"13916",title:"발코니에서",originalTitle:"On the Balcony",artist:"베르트 모리조",artistKey:"morisot",country:"프랑스",year:"1871–1872",museum:"시카고 미술관",difficulty:"hard",story:"발코니 너머의 풍경과 사람의 모습을 함께 담았어요.",look:"가까운 난간과 멀리 보이는 풍경의 차이를 찾아보세요.",image:"https://www.artic.edu/iiif/2/b5529ef6-c95d-9993-cc2e-bc9b209fed67/full/843,/0/default.jpg",source:"https://www.artic.edu/artworks/13916",publicDomain:true,imageSource:"https://www.artic.edu/artworks/13916",imageLicense:"CC0 / Public Domain" },
  { id:"153798",title:"정원의 여인",originalTitle:"Woman in a Garden",artist:"베르트 모리조",artistKey:"morisot",country:"프랑스",year:"1882–1883",museum:"시카고 미술관",difficulty:"normal",story:"초록 정원 속 인물을 가볍고 생생한 붓질로 표현했어요.",look:"인물의 옷과 잎사귀 사이에 숨어 있는 밝은 색을 찾아보세요.",image:"https://www.artic.edu/iiif/2/5edb357d-2e8f-8673-d9e8-4b1150af3895/full/843,/0/default.jpg",source:"https://www.artic.edu/artworks/153798",publicDomain:true,imageSource:"https://www.artic.edu/artworks/153798",imageLicense:"CC0 / Public Domain" },
  { id:"16571",title:"생라자르역에 도착한 기차",originalTitle:"Arrival of the Normandy Train, Gare Saint-Lazare",artist:"클로드 모네",artistKey:"monet",country:"프랑스",year:"1877",museum:"시카고 미술관",difficulty:"master",story:"기차역의 증기와 빛이 섞이는 순간을 모네가 빠르게 그렸어요.",look:"기차, 지붕, 푸른 증기가 겹치는 곳을 찾아보세요.",image:"https://www.artic.edu/iiif/2/0f1cc0e0-e42e-be16-3f71-2022da38cb93/full/843,/0/default.jpg",source:"https://www.artic.edu/artworks/16571",publicDomain:true,imageSource:"https://www.artic.edu/artworks/16571",imageLicense:"CC0 / Public Domain" },
  {
    id: "111436",
    title: "사과 바구니",
    originalTitle: "The Basket of Apples",
    artist: "폴 세잔",
    country: "프랑스",
    year: "1893년경",
    story: "바구니와 식탁 위에 사과가 모여 있어요. 둥근 모양과 색을 살펴봐요.",
    look: "빨간 사과와 노란 사과를 찾아보세요.",
    image: "assets/art-puzzle/111436.jpg",
    source: "https://www.artic.edu/artworks/111436",
    apiSource: "https://api.artic.edu/api/v1/artworks/111436",
    publicDomain: true,
    imageId: "52ac8996-3460-cf71-cb42-5c4d0aa29b74",
    imageSource:
      "https://commons.wikimedia.org/wiki/File:Paul_C%C3%A9zanne_-_The_Basket_of_Apples_-_1926.252_-_Art_Institute_of_Chicago.jpg",
    imageLicense: "Public domain",
  },
  {
    id: "14655",
    title: "두 자매 — 테라스에서",
    originalTitle: "Two Sisters (On the Terrace)",
    artist: "피에르 오귀스트 르누아르",
    country: "프랑스",
    year: "1881",
    story: "두 사람이 꽃과 나무 곁에 앉아 있어요. 따뜻한 색이 가득해요.",
    look: "커다란 빨간 모자를 찾아보세요.",
    image: "assets/art-puzzle/14655.jpg",
    source: "https://www.artic.edu/artworks/14655",
    apiSource: "https://api.artic.edu/api/v1/artworks/14655",
    publicDomain: true,
    imageId: "3a608f55-d76e-fa96-d0b1-0789fbc48f1e",
    imageSource:
      "https://commons.wikimedia.org/wiki/File:Pierre-Auguste_Renoir_-_Two_Sisters_(On_the_Terrace)_-_1933.455_-_Art_Institute_of_Chicago.jpg",
    imageLicense: "Public domain",
  },
  {
    id: "77333",
    title: "가나가와 해변의 높은 파도",
    originalTitle:
      'Under the Wave off Kanagawa (Kanagawa oki nami ura), also known as The Great Wave, from the series "Thirty-Six Views of Mount Fuji (Fugaku sanjūrokkei)"',
    artist: "가쓰시카 호쿠사이",
    country: "일본",
    year: "1830–1833",
    story: "커다란 파도가 배 위로 솟아올라요. 멀리 작은 후지산도 보여요.",
    look: "큰 파도 사이에서 작은 산을 찾아보세요.",
    image: "assets/art-puzzle/77333.jpg",
    source: "https://www.artic.edu/artworks/77333",
    apiSource: "https://api.artic.edu/api/v1/artworks/77333",
    publicDomain: true,
    imageId: "05cd1ba7-67d1-96c5-0e78-2eb4114b65e7",
    imageSource:
      "https://commons.wikimedia.org/wiki/File:1952.343_-_Under_the_Wave_off_Kanagawa_(Kanagawa_oki_nami.jpg",
    imageLicense: "CC0",
  },
  {
    id: "16568",
    title: "수련",
    originalTitle: "Water Lilies",
    artist: "클로드 모네",
    country: "프랑스",
    year: "1906",
    story: "연못 위에 수련 꽃이 둥둥 떠 있어요. 물에도 여러 색이 보여요.",
    look: "꽃이 있는 곳과 물에 비친 그림자를 찾아보세요.",
    image: "assets/art-puzzle/16568.jpg",
    source: "https://www.artic.edu/artworks/16568",
    apiSource: "https://api.artic.edu/api/v1/artworks/16568",
    publicDomain: true,
    imageId: "3c27b499-af56-f0d5-93b5-a7f2f1ad5813",
    imageSource:
      "https://commons.wikimedia.org/wiki/File:Claude_Monet_-_Water_Lilies_-_1933.1157_-_Art_Institute_of_Chicago.jpg",
    imageLicense: "Public domain",
  },
  {
    id: "87088",
    title: "수련 연못",
    originalTitle: "Water Lily Pond",
    artist: "클로드 모네",
    country: "프랑스",
    year: "1900",
    story: "나무 사이의 다리 아래로 연못이 펼쳐져요. 모네의 정원이에요.",
    look: "휘어진 다리의 모양을 손가락으로 따라가 보세요.",
    image: "assets/art-puzzle/87088.jpg",
    source: "https://www.artic.edu/artworks/87088",
    apiSource: "https://api.artic.edu/api/v1/artworks/87088",
    publicDomain: true,
    imageId: "8534685d-1102-e1e3-e194-94f6e925e8b0",
    imageSource:
      "https://commons.wikimedia.org/wiki/File:Claude_Monet_-_Water_Lily_Pond_-_1933.441_-_Art_Institute_of_Chicago.jpg",
    imageLicense: "Public domain",
  },
  {
    id: "20684",
    title: "파리의 거리, 비 오는 날",
    originalTitle: "Paris Street; Rainy Day",
    artist: "귀스타브 카유보트",
    country: "프랑스",
    year: "1877",
    story: "우산을 쓴 사람들이 비 오는 거리를 걸어요. 길이 멀리 이어져요.",
    look: "우산을 찾아보고 길바닥의 빛도 살펴보세요.",
    image: "assets/art-puzzle/20684.jpg",
    source: "https://www.artic.edu/artworks/20684",
    apiSource: "https://api.artic.edu/api/v1/artworks/20684",
    publicDomain: true,
    imageId: "f8fd76e9-c396-5678-36ed-6a348c904d27",
    imageSource:
      "https://commons.wikimedia.org/wiki/File:Gustave_Caillebotte_-_Paris_Street,_Rainy_Day_-_1964.336_-_Art_Institute_of_Chicago.jpg",
    imageLicense: "Public domain",
  },
  {
    id: "111442",
    title: "아이의 목욕",
    originalTitle: "The Child's Bath",
    artist: "메리 커샛",
    country: "미국",
    year: "1893",
    story: "어른이 아이의 발을 조심조심 씻겨 줘요. 다정한 순간을 그렸어요.",
    look: "줄무늬 옷과 둥근 물그릇을 찾아보세요.",
    image: "assets/art-puzzle/111442.jpg",
    source: "https://www.artic.edu/artworks/111442",
    apiSource: "https://api.artic.edu/api/v1/artworks/111442",
    publicDomain: true,
    imageId: "3b885ae0-4d46-5fe4-d70a-00474827f02c",
    imageSource:
      "https://commons.wikimedia.org/wiki/File:The_Child%27s_Bath_by_Mary_Cassatt_1893.jpg",
    imageLicense: "Public domain",
  },
  {
    id: "64818",
    title: "밀짚 더미 — 여름의 끝",
    originalTitle: "Stacks of Wheat (End of Summer)",
    artist: "클로드 모네",
    country: "프랑스",
    year: "1890–1891",
    story: "들판에 모아 둔 밀짚이 햇빛을 받아요. 밝은 곳과 그늘의 색이 달라요.",
    look: "밀짚 더미의 그림자는 어느 쪽으로 길게 뻗었나요?",
    image: "assets/art-puzzle/64818.jpg",
    source: "https://www.artic.edu/artworks/64818",
    apiSource: "https://api.artic.edu/api/v1/artworks/64818",
    publicDomain: true,
    imageId: "a38e2828-ec6f-ece1-a30f-70243449197b",
    imageSource:
      "https://commons.wikimedia.org/wiki/File:Claude_Monet_-_Stacks_of_Wheat_(End_of_Summer)_-_1985.1103_-_Art_Institute_of_Chicago.jpg",
    imageLicense: "Public domain",
  },
  {
    id: "14620",
    title: "푸르빌 절벽 산책",
    originalTitle: "Cliff Walk at Pourville",
    artist: "클로드 모네",
    country: "프랑스",
    year: "1882",
    story: "바닷가 언덕 위에서 사람들이 산책해요. 풀과 바다가 바람을 만나요.",
    look: "바다와 하늘은 어떤 색으로 다르게 보이나요?",
    image: "assets/art-puzzle/14620.jpg",
    source: "https://www.artic.edu/artworks/14620",
    apiSource: "https://api.artic.edu/api/v1/artworks/14620",
    publicDomain: true,
    imageId: "b0effb1c-ff23-bbaa-f809-9fd94e31c1a0",
    imageSource:
      "https://commons.wikimedia.org/wiki/File:Claude_Monet_-_Cliff_Walk_at_Pourville_-_Google_Art_Project.jpg",
    imageLicense: "Public domain",
  },
  {
    id: "27992",
    title: "그랑드 자트 섬의 일요일 오후",
    originalTitle: "A Sunday on La Grande Jatte — 1884",
    artist: "조르주 쇠라",
    country: "프랑스",
    year: "1884–1886 · 테두리 1888–1889",
    story:
      "강가에서 사람들이 쉬고 있어요. 작은 색 점들이 모여 그림이 되었어요.",
    look: "양산을 쓴 사람과 작은 동물을 찾아보세요.",
    image: "assets/art-puzzle/27992.jpg",
    source: "https://www.artic.edu/artworks/27992",
    apiSource: "https://api.artic.edu/api/v1/artworks/27992",
    publicDomain: true,
    imageId: "2d484387-2509-5e8e-2c43-22f9981972eb",
    imageSource:
      "https://commons.wikimedia.org/wiki/File:Georges_Seurat_-_A_Sunday_on_La_Grande_Jatte_--_1884_-_Google_Art_Project.jpg",
    imageLicense: "Public domain",
  },
  {
    id: "64957",
    title: "포도, 레몬, 배와 사과",
    originalTitle: "Grapes, Lemons, Pears, and Apples",
    artist: "빈센트 반 고흐",
    country: "네덜란드",
    year: "1887",
    story: "여러 과일이 알록달록 모여 있어요. 모양과 색이 조금씩 달라요.",
    look: "길쭉한 배와 동그란 포도를 구별해 보세요.",
    image: "assets/art-puzzle/64957.jpg",
    source: "https://www.artic.edu/artworks/64957",
    apiSource: "https://api.artic.edu/api/v1/artworks/64957",
    publicDomain: true,
    imageId: "f11bd233-6cc3-4221-59eb-f7363be4119e",
    imageSource:
      "https://commons.wikimedia.org/wiki/File:Vincent_van_Gogh_-_Grapes,_Lemons,_Pears,_and_Apples_-_1949.215_-_Art_Institute_of_Chicago.jpg",
    imageLicense: "Public domain",
  },
];