(function (B) {
  const powers = ["MULTI", "WIDE", "LASER", "FIRE", "SLOW", "MAGNET", "SHIELD", "FEVER"];
  B.start = function () {
    Session.begin();
    const r = B.progress(state);
    gameShell("🌠 별빛 벽돌깨기", `<section class="brickAdventure"><header><div><small>STAGE ADVENTURE</small><h2>별빛 항로</h2><p>모양과 장치를 깨고 우주 보스에게 가요!</p></div><strong>${Object.keys(r.stages).length}/30 CLEAR</strong></header><div class="brickMap">${B.stages.map(s => `<button data-stage="${s.id}" ${s.id > r.unlocked ? "disabled" : ""} class="${r.stages[s.id]?.cleared ? "cleared" : ""}"><i>${s.icon}</i><b>${s.id}</b><span>${s.name}</span><small>${r.stages[s.id] ? "★".repeat(r.stages[s.id].stars) : s.id > r.unlocked ? "🔒" : "PLAY"}</small></button>`).join("")}</div></section>`);
    gameBody.querySelectorAll("[data-stage]").forEach(b => b.onclick = () => B.play(+b.dataset.stage));
  };
  B.play = function (id) {
    const stage = B.stages[id - 1], touch = matchMedia("(pointer: coarse)").matches;
    gameShell(`STAGE ${id} · ${stage.name}`, `<div class="brickHud"><span>❤️ <b data-life>${stage.lives}</b></span><span>SCORE <b data-score>0</b></span><span>⭐ <b data-stars>0</b></span></div><div class="brickScene brickStage" aria-label="별빛 벽돌깨기 스테이지"><div class="brickField"></div><div class="brickDrops"></div><div class="brickShield"></div><div class="pixelPaddle"><i></i></div></div><p class="gameStatus">${touch ? "손가락으로 받침대를 움직여요" : "마우스·방향키로 받침대를 움직여요"}</p>`, `<button class="moveL">◀</button><button class="brickLaunch">발사</button><button class="moveR">▶</button>`);
    const scene = gameBody.querySelector(".brickScene"), field = gameBody.querySelector(".brickField"), paddle = gameBody.querySelector(".pixelPaddle"), msg = gameBody.querySelector(".gameStatus"); if(stage.boss) scene.classList.add("boss");
    const startedAt = performance.now(); let paddleX = 50, width = stage.paddle, lives = stage.lives, score = 0, foundStars = 0, running = true, fire = false, shield = false, magnet = true, held = true, lasers = 0;
    const balls = [], drops = []; const starRenderer=new B.StarRenderer(scene);Session.cleanup(()=>{running=false;starRenderer.destroy()});scene.dataset.material=['wood','crystal','ice','energy'][Math.floor((id-1)/8)];let lastFrame=0,accumulator=0;
    const brickEls = stage.bricks.map((d, i) => { const e=document.createElement("div"), hp=B.typeHp[d.type]; e.className=`starBrick ${d.type}`; e.style.left=`${5+d.x*13}%`; e.style.top=`${7+d.y*7.4}%`; e.dataset.hp=hp; e.dataset.i=i; const symbol=d.type==="metal"?"◆":d.type==="star"?"★":d.type==="multiball"?"×3":d.type==="mystery"?"?":"";e.innerHTML=`<i></i>${symbol?`<span class="brickSymbol">${symbol}</span>`:""}`; field.append(e); return { ...d, hp, e, baseX:5+d.x*13 }; });
    function addBall(x=50,y=76,vx=.55,vy=-stage.speed){ balls.push({x,y,vx,vy,trail:[]}); }
    addBall(); paddle.style.width=width+"%";
    const draw=()=>{paddle.style.left=paddleX+"%"; starRenderer.paint(balls);};
    const drop=(x,y,kind)=>{const e=document.createElement("div");e.className="brickPower";e.textContent={MULTI:"×3",WIDE:"↔",LASER:"⚡",FIRE:"🔥",SLOW:"🐢",MAGNET:"🧲",SHIELD:"🛡",FEVER:"★"}[kind];scene.querySelector(".brickDrops").append(e);drops.push({x,y,kind,e});};
    function starReward(x,y,amount=1){foundStars+=amount;const counter=gameBody.querySelector("[data-stars]");counter.classList.remove("starCountPop");void counter.offsetWidth;counter.classList.add("starCountPop");for(let i=0;i<12;i++){const p=document.createElement("i");p.className="starRewardParticle";p.textContent=i%3?"✦":"★";p.style.left=x+"%";p.style.top=y+"%";p.style.setProperty("--dx",`${Math.cos(i*Math.PI/6)*(35+i%3*10)}px`);p.style.setProperty("--dy",`${Math.sin(i*Math.PI/6)*(28+i%4*8)}px`);scene.append(p);setTimeout(()=>p.remove(),760);}}
    function power(kind){msg.textContent=`POWER UP · ${kind}`; if(kind==="MULTI")balls.slice(0,1).forEach(b=>{addBall(b.x,b.y,-1.05,b.vy);addBall(b.x,b.y,1.05,b.vy)}); if(kind==="WIDE"){width=Math.min(38,width+10);paddle.style.width=width+"%"} if(kind==="SLOW")balls.forEach(b=>{b.vx*=.76;b.vy*=.76}); if(kind==="FIRE")fire=true; if(kind==="MAGNET")magnet=true; if(kind==="SHIELD"){shield=true;scene.classList.add("shielded")} if(kind==="FEVER")starReward(50,45,3); if(kind==="LASER")lasers=8;}
    function hit(br){ starRenderer.impact((parseFloat(br.e.style.left)+5.75)*starRenderer.w/100,(parseFloat(br.e.style.top)+2)*starRenderer.h/100);if(br.type==="metal")return; br.hp--; br.e.dataset.hp=br.hp; if(br.type==="boss")br.e.style.setProperty("--boss-hp",`${br.hp/12*100}%`); br.e.classList.remove("hit"); void br.e.offsetWidth; br.e.classList.add("hit"); if(br.hp>0)return; br.e.classList.add("breaking"); score += br.type==="star"?250:br.type==="boss"?2000:100; if(br.type==="star")starReward(br.baseX+5.5,parseFloat(br.e.style.top)+3,1); if(br.type==="explosive")brickEls.filter(x=>x.hp>0&&x!==br&&Math.abs(x.x-br.x)<=1&&Math.abs(x.y-br.y)<=1).forEach(hit); if(br.type==="multiball")power("MULTI"); if(br.type==="mystery"||Math.random()<.13)drop(br.baseX+6,parseFloat(br.e.style.top),powers[Math.floor(Math.random()*powers.length)]); br.hp=0; setTimeout(()=>br.e.remove(),280); checkClear(); }
    function checkClear(){if(brickEls.every(b=>b.hp<=0||b.type==="metal")){running=false; const sec=Math.max(1,Math.round((performance.now()-startedAt)/1000)), rating=3-Number(lives<2)-Number(sec>150), delta=B.complete(state,id,score,Math.max(1,rating),sec);save(); gameBody.querySelector(".arcade").insertAdjacentHTML("beforeend",`<div class="brickResult"><small>STAGE ${id}</small><h2>STAGE CLEAR!</h2><strong>${"★".repeat(Math.max(1,rating))}${"☆".repeat(3-Math.max(1,rating))}</strong><p>${score}점 · ${sec}초 · 별 +${delta}</p><div><button data-retry>다시 하기</button><button data-map>스테이지 선택</button>${id<30?"<button data-next>다음 스테이지</button>":""}</div></div>`); const box=gameBody.querySelector(".brickResult");box.querySelector("[data-retry]").onclick=()=>B.play(id);box.querySelector("[data-map]").onclick=B.start;if(id<30)box.querySelector("[data-next]").onclick=()=>B.play(id+1);}}
    function loseBall(ball){balls.splice(balls.indexOf(ball),1);if(balls.length)return;if(shield){shield=false;scene.classList.remove("shielded");addBall(paddleX,76);held=true;return}lives--;gameBody.querySelector("[data-life]").textContent=lives;if(lives<=0){running=false;msg.innerHTML=`별빛이 잠시 쉬어요. <button data-again>다시 도전</button>`;msg.querySelector("button").onclick=()=>B.play(id)}else{addBall(paddleX,76);held=true;magnet=true;}}
    function step(t){if(!running)return; brickEls.forEach(br=>{if(br.hp>0&&br.type==="moving"){const x=br.baseX+Math.sin(t/700+br.y)*4;br.e.style.left=x+"%";br.x=(x-5)/13}}); if(lasers>0&&Math.floor(t/350)!==Math.floor((t-16)/350)){lasers--;const targets=brickEls.filter(b=>b.hp>0&&b.type!=="metal").sort((a,b)=>b.y-a.y);if(targets[0]){const beam=document.createElement("i");beam.className="paddleLaser";beam.style.left=paddleX+"%";beam.style.height=(78-parseFloat(targets[0].e.style.top))+"%";scene.append(beam);setTimeout(()=>beam.remove(),180);hit(targets[0])}} for(const b of [...balls]){
      if(held){b.x=paddleX;b.y=76;b.trail.length=0;continue}
      const w=starRenderer.w,h=starRenderer.h,r=B.ballRadius(w),rx=r/w*100,ry=r/h*100;
      // Pixel-distance substeps keep the bigger ball from tunnelling through thin bricks.
      const steps=Math.max(1,Math.ceil(Math.hypot(b.vx*w/100,b.vy*h/100)/(r*.5)));
      for(let sub=0;sub<steps;sub++){
        b.x+=b.vx/steps;b.y+=b.vy/steps;
        if(b.x<rx){b.x=rx;b.vx=Math.abs(b.vx)}if(b.x>100-rx){b.x=100-rx;b.vx=-Math.abs(b.vx)}if(b.y<ry){b.y=ry;b.vy=Math.abs(b.vy)}
        const paddleTop=h*.89-paddle.offsetHeight;
        if(b.vy>0&&b.y*h/100+r>=paddleTop&&b.y*h/100-r<=paddleTop+paddle.offsetHeight&&Math.abs(b.x-paddleX)<=width/2+rx){b.y=(paddleTop-r)/h*100;b.vy=-Math.abs(b.vy);b.vx=Math.max(-2.2,Math.min(2.2,b.vx+(b.x-paddleX)*.035));starRenderer.impact(b.x*w/100,paddleTop);if(magnet){held=true;magnet=false;break}}
        for(const br of brickEls){if(br.hp<=0)continue;
          const box={x:br.e.offsetLeft,y:br.e.offsetTop,w:br.e.offsetWidth,h:br.e.offsetHeight},contact=B.circleContact(b.x*w/100,b.y*h/100,r,box);
          if(!contact)continue;
          b.x+=contact.x*(contact.depth+.1)/w*100;b.y+=contact.y*(contact.depth+.1)/h*100;
          if(!fire||br.type==='metal'){let vx=b.vx*w/100,vy=b.vy*h/100,dot=vx*contact.x+vy*contact.y;if(dot<0){vx-=2*dot*contact.x;vy-=2*dot*contact.y;b.vx=vx/w*100;b.vy=vy/h*100;}}
          hit(br);break;
        }
        if(b.y>101+ry){loseBall(b);break}
      }
    } drops.forEach((d,i)=>{d.y+=.22;d.e.style.left=d.x+"%";d.e.style.top=d.y+"%";if(d.y>82&&Math.abs(d.x-paddleX)<width/2){power(d.kind);d.e.remove();drops.splice(i,1)}else if(d.y>100){d.e.remove();drops.splice(i,1)}});gameBody.querySelector("[data-score]").textContent=score;gameBody.querySelector("[data-stars]").textContent=foundStars;paddle.style.left=paddleX+"%";starRenderer.paint(balls,1/60)}
    function move(clientX){const r=scene.getBoundingClientRect();paddleX=Math.max(width/2,Math.min(100-width/2,(clientX-r.left)/r.width*100));draw()}
    let pointer=null;scene.onmousemove=e=>move(e.clientX);scene.onpointerdown=e=>{if(e.pointerType!=="mouse"){pointer=e.pointerId;scene.setPointerCapture?.(e.pointerId);move(e.clientX)}};scene.onpointermove=e=>{if(pointer===e.pointerId)move(e.clientX)};scene.onpointerup=scene.onpointercancel=e=>{if(pointer===e.pointerId)pointer=null};
    const launch=()=>{held=false}; gameBody.querySelector(".brickLaunch").onclick=launch;gameBody.querySelector(".moveL").onclick=()=>{paddleX=Math.max(width/2,paddleX-10)};gameBody.querySelector(".moveR").onclick=()=>{paddleX=Math.min(100-width/2,paddleX+10)};Session.key(e=>{if(e.key==="ArrowLeft")paddleX=Math.max(width/2,paddleX-4);if(e.key==="ArrowRight")paddleX=Math.min(100-width/2,paddleX+4);if(e.key===" "||e.key==="ArrowUp")launch()});function frame(t){if(!running)return;const dt=lastFrame?Math.min(.05,(t-lastFrame)/1000):1/60;lastFrame=t;accumulator+=dt;while(accumulator>=1/60&&running){step(t);accumulator-=1/60;}Session.frame(frame)}
    draw();Session.frame(frame);
  };
})(SianBrick);
