const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const listeners={},intervals=new Map();let iid=0,created=0,clock=0,nodes=[];
class Param{constructor(){this.value=0;}setValueAtTime(v){this.value=v;}linearRampToValueAtTime(v){this.value=v;}exponentialRampToValueAtTime(v){this.value=v;}cancelScheduledValues(){}}
class Node{constructor(){this.gain=new Param();this.frequency=new Param();this.threshold=new Param();this.ratio=new Param();}connect(n){return n;}disconnect(){}start(){}stop(){this.onended?.();}getFloatTimeDomainData(a){a.fill(.01);}}
class Ctx{constructor(){created++;this.state='running';this.destination=new Node();}get currentTime(){return clock;}createGain(){return new Node();}createOscillator(){const n=new Node();nodes.push(n);return n;}createDynamicsCompressor(){return new Node();}createAnalyser(){return new Node();}resume(){this.state='running';return Promise.resolve();}suspend(){this.state='suspended';return Promise.resolve();}}
const doc={hidden:false,documentElement:{dataset:{}},getElementById:()=>null,addEventListener:(k,f)=>listeners[k]=f};
const c={window:{AudioContext:Ctx,addEventListener:(k,f)=>listeners[k]=f},document:doc,state:{stars:37,stage100:{영어:7}},save:()=>{},Float32Array,setInterval:f=>{intervals.set(++iid,f);return iid},clearInterval:id=>intervals.delete(id)};vm.createContext(c);
for(const f of ['scores','engine','voice-director'])vm.runInContext(fs.readFileSync('js/audio/'+f+'.js','utf8'),c);
(async()=>{const A=c.window.SianAudio,S=c.window.SianScores;
assert.equal(Object.keys(S.tracks).length,27);assert.equal(new Set(S.worlds.map(w=>JSON.stringify(S.tracks[w].melodies))).size,9);
for(const t of Object.values(S.tracks)){assert.ok(t.bars*240/t.bpm>=40);const phrases=new Set();for(let b=0;b<32;b++){let notes=[];for(let s=0;s<8;s++){const ns=S.notes(t.id,b,s,1);assert.ok(ns.every(n=>Number.isFinite(n.note)&&n.duration>0));notes.push(ns);}phrases.add(JSON.stringify(notes));}assert.ok(phrases.size>=8,t.id+' variation');}
A.start('forest');await A.unlock();assert.equal(created,1);assert.equal(intervals.size,1);assert.equal(doc.documentElement.dataset.audioTrack,'forest');
for(let n=0;n<20;n++)A.music(n%2?'ocean':'sky');assert.equal(intervals.size,1);assert.equal(created,1);assert.ok(+doc.documentElement.dataset.audioNodes<=64);
A.duck(true);assert.equal(doc.documentElement.dataset.audioDucked,'true');A.duck(false);
A.pause(true);assert.equal(intervals.size,0);A.pause(false);assert.equal(intervals.size,1);
A.event({type:'bossTransition'},2);assert.equal(intervals.size,0);A.event({type:'bossArena'},2);assert.equal(doc.documentElement.dataset.audioTrack,'boss-ocean');assert.equal(intervals.size,1);
A.event({type:'bossDefeat'},2);assert.equal(doc.documentElement.dataset.audioTrack,'none');A.music('ocean');A.event({type:'death',reason:'fall'},2);A.event({type:'respawn'},2);assert.equal(doc.documentElement.dataset.audioTrack,'ocean');
A.configure('master',false);const before=nodes.length;A.effect('starShot');assert.equal(nodes.length,before);assert.equal(A.voiceAllowed(),false);A.configure('master',true);await A.unlock();
A.configure('bgm',false);A.start('brick');assert.equal(A.settings().bgm,false);A.configure('bgm',true);doc.hidden=true;listeners.visibilitychange();assert.equal(intervals.size,0);doc.hidden=false;listeners.visibilitychange();await A.unlock();assert.equal(intervals.size,1);
A.stop();assert.equal(intervals.size,0);assert.equal(doc.documentElement.dataset.audioNodes,'0');A.start('memory');await A.unlock();assert.equal(created,1);assert.equal(intervals.size,1);A.stop();assert.equal(c.state.stars,37);assert.equal(c.state.stage100.영어,7);
const D=c.window.VoiceDirector;assert.equal(D.prepare([{text:'ㄷ ㄲ ㅙ',lang:'ko-KR'}])[0].text,'디귿 쌍기역 왜');assert.equal(D.prepare([{text:'cat',lang:'en-US'}])[0].text,'cat');assert.ok(D.lesson('사고력 수학','별 모양을 찾아 줘.').spokenText.some(x=>x.text==='별 모양을 찾아 줘.'));assert.equal(D.hanja({character:'山',meaning:'산',reading:'산'})[0].text,'뫼 산');assert.notEqual(D.respond('success').text,D.respond('success').text);
console.log('PASS 27 original 32-bar scores, nine distinct world melodies, bounded single scheduler/context, boss/death transitions, pause, mute persistence, duck lifecycle, hidden tab, cleanup, saved progress and voice scripts (not audible hardware verification)');
})().catch(e=>{console.error(e);process.exitCode=1;});
// Physical key tracking: both Shift keys and F coexist with movement and release independently.
let now=0;const keyListeners={},rootListeners={};const root={querySelectorAll:()=>[]};
const input={window:{addEventListener:(k,f)=>rootListeners[k]=f,removeEventListener(){}},document:{addEventListener:(k,f)=>keyListeners[k]=f,removeEventListener(){}},HangulRunner:{},performance:{now:()=>now}};vm.createContext(input);vm.runInContext(fs.readFileSync('js/games/hangul-runner/controls.js','utf8'),input);let force=false;const controls=new input.HangulRunner.Controls(root,v=>force=v,()=>{});const key=(type,code)=>keyListeners[type]({code,target:{matches:()=>false},preventDefault(){},repeat:false});
key('keydown','ArrowRight');key('keydown','ShiftLeft');key('keydown','ShiftRight');assert.equal(controls.read().right,true);assert.equal(controls.read().fire,true);key('keyup','ShiftLeft');now=200;assert.equal(controls.read().fire,true);key('keyup','ShiftRight');assert.equal(controls.read().fire,false);key('keydown','KeyF');assert.equal(controls.read().fire,true);rootListeners.blur();assert.equal(force,true);assert.equal(controls.read().fire,false);assert.equal(controls.read().right,false);controls.destroy();assert.equal(controls.listeners.length,0);
console.log('PASS ShiftLeft/ShiftRight/F simultaneous movement/fire, independent key releases, blur reset and listener cleanup');
