const fs = require("node:fs");
const vm = require("node:vm");
const assert = require("node:assert/strict");

const window = { state: { records: {} }, save() {} };
const ctx = vm.createContext({ window, state: window.state, save: window.save, Math, Date, console });
for (const file of ["data", "storage", "engine"]) {
  vm.runInContext(fs.readFileSync(`js/games/autobattler/${file}.js`, "utf8"), ctx);
}
const D = window.AutoBattlerData;
const E = window.AutoBattlerEngine;
const S = window.AutoBattlerStorage;
assert.equal(D.characters.length, 15, "original roster");
assert.equal(Object.keys(D.roles).length, 7, "seven distinct combat roles");
assert.equal(D.stages.length, 16, "four worlds of rounds");

const run = S.createRun();
assert.equal(run.inventory.length, 0, "new run starts with an empty inventory");
E.rollShop(run, () => 0.01);
assert.equal(run.shop.length, 5);
assert.ok(run.shop.every((s) => D.characters.find((c) => c.id === s.characterId).grade === 1));
run.shop = [{ characterId: "bolt", sold: false }, { characterId: "bolt", sold: false }, { characterId: "bolt", sold: false }];
for (let i = 0; i < 3; i++) assert.equal(E.buy(run, i).ok, true);
assert.equal(run.bench.length, 1, "three one-stars merge into one unit");
assert.equal(run.bench[0].star, 2);

const upgraded = run.bench[0];
assert.equal(E.move(run, upgraded.uid, { type: "board", x: 2, y: 6 }).ok, true);
assert.equal(run.board.length, 1);
assert.equal(E.move(run, upgraded.uid, { type: "board", x: 2, y: 1 }).ok, false, "enemy half is locked");

run.inventory = ["power", "gear", "armor", "crystal"];
assert.equal(E.combine(run, "power", "gear"), "rapid");
assert.equal(E.combine(run, "armor", "crystal"), "barrier");
assert.equal(E.equip(run, upgraded.uid, "rapid"), true);
assert.equal(upgraded.items[0], "rapid");
const combat = E.buildCombatUnit(upgraded, "player", 0);
assert.ok(combat.maxHp > D.characters.find((c) => c.id === "bolt").hp);
assert.ok(combat.speed > combat.data.speed, "equipment modifies combat stats");

const enemy = E.makeEnemy(D.stages[7], () => 0.2);
assert.equal(enemy.length, D.stages[7].count);
assert.ok(enemy.every((u) => u.tile.y < 4));
assert.ok(enemy.composition, "AI composition is named before battle");
const earlyEnemy = E.makeEnemy(D.stages[0], () => 0.01);
assert.ok(earlyEnemy.every((u) => D.characters.find((c) => c.id === u.characterId).grade === 1), "early AI uses grade 1 units");
const lateEnemy = E.makeEnemy(D.stages[15], () => 0.01);
assert.ok(lateEnemy.some((u) => u.star > 1), "late AI upgrades stars");
assert.ok(lateEnemy.some((u) => u.items.length), "late AI equips items");
const capacityRun=S.createRun();capacityRun.gold=30;assert.equal(E.buyCapacity(capacityRun).ok,true);assert.equal(capacityRun.capacity,3);assert.equal(capacityRun.gold,21);
assert.equal(E.sell(run, upgraded.uid).ok, true);
assert.ok(run.equipment.includes("rapid"), "equipment returns on sale");
const gameSource = fs.readFileSync("js/games/autobattler/game.js", "utf8");
const responsiveCss = fs.readFileSync("css/games/autobattler.css", "utf8");
const rendererSource = fs.readFileSync("js/games/autobattler/renderer.js", "utf8");
assert.match(gameSource, /setPlanningTeams\(run\.board, run\.enemyTeam\)/, "planning renders player and AI teams together");
assert.match(gameSource, /run\.phase !== "PREP" \|\| !run\.board\.length/, "one deployed unit enables battle CTA");
assert.match(gameSource, /data-close-panel/, "information and workshop expose close controls");
assert.match(gameSource, /data-action="capacity"/, "team capacity can be purchased with gold");
assert.doesNotMatch(gameSource, /b\.onpointerdown/, "tap selection is not hijacked by drag state");
assert.match(responsiveCss, /@media\(max-width:520px\)/, "compact mobile layout exists");
assert.match(responsiveCss, /grid-auto-columns:minmax\(104px,39vw\)/, "mobile shop cards scroll at full card widths");
assert.match(rendererSource, /c\.name.*"★"\.repeat\(unit\.star\)/, "WebGL nameplates use character data and live star rank");
assert.match(rendererSource, /enemy \? "#ff5c68" : "#4ee5aa"/, "combat nameplates distinguish AI and player HP");
assert.match(rendererSource, /function contain\(unit\)/, "combat movement is clamped to board bounds");
assert.match(responsiveCss, /grid-template-rows:50px 32px minmax\(250px,1fr\) 54px 112px 62px/, "short desktop viewport keeps every play section visible");
assert.doesNotMatch(responsiveCss, /\.autoGame[^}]*transform\s*:\s*scale/, "one-screen layout does not scale the entire game");
assert.match(rendererSource, /innerWidth < 700 \? 2 : 1\.8/, "mobile WebGL uses a Retina-aware capped pixel ratio");
assert.match(responsiveCss, /grid-template-rows:44px 32px 240px 52px 92px 50px/, "mobile game uses compact fixed play sections instead of stretching the board");
const foreignRecords = { korean: { stage: 44 }, claw: { collection: ["dragon"] }, robot: { saved: "hero" } };
window.state.records = { ...foreignRecords, autoBattler: { ...S.get(), activeRun: run } };
const starRecord = S.get();
starRecord.collection.bolt = true;
const restarted = S.replaceRun(starRecord);
assert.equal(restarted.stageIndex, 0);
assert.equal(restarted.gold, 12);
assert.equal(restarted.level, 2);
assert.equal(restarted.board.length, 0);
assert.equal(restarted.bench.length, 0);
assert.equal(starRecord.collection.bolt, true, "permanent Star Board collection survives a run reset");
assert.deepEqual(window.state.records.korean, foreignRecords.korean, "learning progress survives a run reset");
assert.deepEqual(window.state.records.claw, foreignRecords.claw, "claw collection survives a run reset");
assert.deepEqual(window.state.records.robot, foreignRecords.robot, "robot data survives a run reset");
console.log("PASS auto-battler shop, merge, placement, crafting, equipment, AI and sale loop");
