const a=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const ctx={window:{},state:{records:{},stage100:{'한자':17,'한글':28},completed:{'learn:한자:1':1},stars:9},Math,localStorage:{setItem(){}}};vm.createContext(ctx);
for(const f of ['core','content','tracing','mission-model','learning-space','math-space','hanja-data','hanja-space','discovery-model','space-curriculum']){vm.runInContext(fs.readFileSync('js/curriculum/'+f+'.js','utf8'),ctx);if(f==='tracing')ctx.HangulTrace=ctx.window.HangulTrace;}
const M=ctx.window.MissionModel,H=ctx.window.HanjaSpace,C=ctx.window.HanjaCharacters;
const counts={};for(const subject of ['수학','사고력 수학','연산'])for(let s=1;s<=(subject==='연산'?30:100);s++)for(let v=0;v<5;v++){const q=M.make(subject,s,v);a.ok(M.validate(q),q.id);counts[q.mode]=(counts[q.mode]||0)+1;for(const it of q.items)if(q.expected[it.id]&&q.expected[it.id]!=='none')a.ok(q.targets.some(t=>M.accepts(q,it.id,t.id)),q.id+' reachable');}
const venn=M.make('사고력 수학',42);a.equal(venn.mode,'venn');a.equal(venn.expected['1'],'both');a.equal(venn.expected['3'],'outside');a.equal(M.accepts(venn,'1','right'),false);
const board=M.make('사고력 수학',91);a.equal(board.mode,'board');a.equal(M.accepts(board,'b','2'),false);a.ok(board.targets.some(t=>M.accepts(board,'a',t.id)));a.equal(M.accepts(board,'a','99'),false);
a.equal(M.pathNext({shape:'star',color:'red'},{shape:'star',color:'red'}),false);a.equal(M.pathNext({shape:'star',color:'red'},{shape:'star',color:'blue'}),true);
function dense(p){return p.slice(1).flatMap((b,i)=>{const x=p[i];return Array.from({length:20},(_,j)=>[x[0]+(b[0]-x[0])*j/20,x[1]+(b[1]-x[1])*j/20]);}).concat([p.at(-1)]);}
let strokeCount=0;for(const ch of C){a.equal(ch.strokeCount,ch.strokePaths.length);a.equal(ch.strokeCount,ch.strokeOrder.length);for(const p of ch.strokePaths){strokeCount++;a.ok(p.every(([x,y])=>Number.isFinite(x)&&Number.isFinite(y)&&x>=0&&y>=0&&x<=100&&y<=100),ch.character+' bounds');const good=dense(p);a.ok(H.assess(good,p,'touch'),ch.character+' correct');a.equal(H.assess(good.slice().reverse(),p,'touch'),false,ch.character+' reversed');a.ok(H.assess(good.map(([x,y],i)=>[x+Math.sin(i)*1.2,y+Math.cos(i)*1.2]),p,'touch'),ch.character+' shaky');a.equal(H.assess(good.map(([x,y])=>[x+28,y+25]),p,'touch'),false,ch.character+' displaced');a.equal(H.assess(Array.from({length:100},(_,i)=>[50+44*Math.sin(i),50+44*Math.cos(i)]),p,'touch'),false,ch.character+' scribble');}}
a.deepEqual(Array.from(H.phasesFor(1)),['A','A','B','B','C','D']);a.deepEqual(Array.from(H.phasesFor(95)),['D']);a.equal(ctx.state.stage100['한자'],17);a.equal(ctx.state.stage100['한글'],28);a.equal(ctx.state.stars,9);a.equal(ctx.state.completed['learn:한자:1'],1);
for(let s=1;s<=100;s++){const l=H.lesson(s);a.ok(l.character);a.equal(ctx.window.SianCurriculum.curricula['한자'][s-1].questionType,'HANJA_TRACING');}
console.log('PASS 1150 interactive math missions, Venn exclusive/intersection/neither, strategic actual wins, '+C.length+' Hanja / '+strokeCount+' strokes, shaky acceptance, scribble rejection, 100 lessons and legacy save preservation');
