const assert=require("node:assert/strict"),fs=require("node:fs"),vm=require("node:vm");
const sandbox={window:{},state:{stars:8,records:{claw:{coins:7}},completed:{},stage100:{한글:12},collection:["keep"]},save(){sandbox.saved=JSON.parse(JSON.stringify(sandbox.state));}};
sandbox.window.SianMemory={};sandbox.SianMemory=sandbox.window.SianMemory;vm.createContext(sandbox);
vm.runInContext(fs.readFileSync("js/games/memory/catalog.js","utf8"),sandbox);
vm.runInContext(fs.readFileSync("js/games/memory/storage.js","utf8"),sandbox);
assert.equal(sandbox.SianMemory.catalog.length,20);
assert.equal(sandbox.SianMemory.levels.length,5);
const monster=sandbox.SianMemory.catalog[0];
assert.equal(sandbox.SianMemory.discover(monster,1),true);
assert.equal(sandbox.state.stars,9);
assert.equal(sandbox.SianMemory.discover(monster,1),false);
assert.equal(sandbox.state.stars,9);
sandbox.SianMemory.finish(1,10,45);
sandbox.SianMemory.finish(1,12,50);
assert.equal(sandbox.state.stars,10);
assert.deepEqual(sandbox.state.records.claw,{coins:7});
assert.equal(sandbox.state.stage100.한글,12);
assert.deepEqual(sandbox.state.collection,["keep"]);
assert.equal(sandbox.state.records.englishFriends.levels[1].plays,2);
console.log("PASS 20 friends, 5 levels, capped rewards, legacy state preservation");
