const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const THREE=require('../assets/vendor/three-0.160.1.min.js');
const ctx={window:{},THREE,state:{records:{claw:{coins:7}},stars:41},save(){}};
vm.createContext(ctx);
for(const f of ['catalog','storage','model'])vm.runInContext(fs.readFileSync(`js/games/robot/${f}.js`,'utf8'),ctx);
const R=ctx.window.SianRobot,b=R.normalize(R.defaultBuild());
b.colors.head.primary='#ff0000';b.colors.body.primary='#0000ff';
let m=R.makeModel(b);
assert.equal(m.children.length,8);
assert.equal(m.userData.parts.head.children[0].material.color.getHexString(),'ff0000');
assert.equal(m.userData.parts.body.children[0].material.color.getHexString(),'0000ff');
const before=m.userData.parts.head.children.length;
b.parts.head='dino';let changed=R.makeModel(b);
assert.notEqual(changed.userData.parts.head.children.length,before);
assert.ok(new THREE.Box3().setFromObject(changed).getSize(new THREE.Vector3()).z>.5);
let meshCount=0,channels=new Set();changed.traverse(o=>{if(o.isMesh){meshCount++;channels.add(o.userData.channel);}});assert.ok(meshCount>=70,'hero mecha uses layered armor and mechanical detail');assert.ok(channels.has('mechanical')&&channels.has('rubber')&&channels.has('glass'),'metal, rubber, glass and energy materials are separated');assert.ok(changed.userData.core,'battle renderer can animate the shared energy core');
const eye=changed.userData.parts.head.children[2];changed.updateMatrixWorld(true);const front=eye.getWorldPosition(new THREE.Vector3());changed.rotation.y=Math.PI;changed.updateMatrixWorld(true);const back=eye.getWorldPosition(new THREE.Vector3());assert.ok(front.z>0&&back.z<0);
R.store.saveRobot(b);assert.equal(R.store.active().colors.head.primary,'#ff0000');assert.equal(ctx.state.records.claw.coins,7);
R.disposeModel(m);R.disposeModel(changed);
console.log('PASS real mesh replacement, independent materials, 180-degree depth rotation, saved build preservation');
