const fs=require('node:fs'),vm=require('node:vm'),a=require('node:assert/strict');
const c=vm.createContext({Math,Date});
for(const f of ['stage-data','engine','world-data','world-engine','world-forest','world-ocean','world-sky','world-underground','boss'])vm.runInContext(fs.readFileSync(`js/games/hangul-runner/${f}.js`,'utf8'),c);
const H=c.HangulRunner,advance=(e,seconds,input={})=>{for(let i=0;i<seconds*120;i++)e.step(1/120,input);};
a.equal(H.worlds.length,4);a.equal(H.worldStages.length,16);a.deepEqual([...new Set(H.worldStages.map(s=>s.theme))],['forest','ocean','sky','underground']);
for(const id of ['1-4','2-4','3-4','4-4']){
 const e=new H.WorldEngine(H.buildWorldStage(id));a.equal(e.sceneState,'RUN_STAGE');a.equal(e.boss,undefined,`${id} hides boss during the run`);
 for(let i=0;i<e.stage.words.length;i++){const item=e.stage.items.find(v=>v.id===`letter-${i}`);item.contained=false;e.player.x=item.x;e.player.y=item.y;e.step(1/120,{});if(i<e.stage.words.length-1)a.equal(e.sceneState,'RUN_STAGE');}
 a.equal(e.letterCount,e.stage.words.length);a.equal(e.sceneState,'RUN_STAGE',`${id} waits for the entrance after collection`);a.equal(e.boss,undefined);
 e.player.x=e.stage.goal.x;e.player.y=e.stage.goal.y;e.step(1/120,{});a.equal(e.sceneState,'TRANSITION',`${id} transitions only on entrance contact`);
 advance(e,2.6);a.equal(e.sceneState,'BOSS_INTRO');a.ok(e.boss);a.equal(e.boss.difficulty,Number(id[0]));a.equal(e.stage.items.length,0);advance(e,2.3);a.equal(e.sceneState,'BOSS_STAGE');e.player.invincible=999;
 for(let i=0;i<e.boss.maxHp;i++){for(let wait=0;wait<5&&!e.boss.choices.length;wait+=.1)advance(e,.1);const correct=e.boss.choices.find(v=>v.correct);a.ok(correct,`${id} offers an arena learning choice after the boss attack`);a.equal(new Set(e.boss.choices.map(v=>v.x)).size,e.boss.choices.length,`${id} never stacks choices on one x axis`);for(const left of e.boss.choices)for(const right of e.boss.choices)if(left!==right)a.equal(H.overlaps(left,right),false,`${id} choice hitboxes never overlap`);a.ok(e.boss.choiceTime>4&&e.boss.choiceTime<=5.5);e.player.x=correct.x;e.player.y=correct.y;e.step(1/120,{});a.ok(e.projectiles.some(v=>v.team==='player'),`${id} launches a visible player projectile`);advance(e,1.8);}
 a.equal(e.boss.hp,0);a.equal(e.sceneState,'BOSS_DEFEATED');a.notEqual(e.status,'clear',`${id} does not auto-clear on boss defeat`);a.ok(e.events.bossHit>=1);a.ok(e.events.bossAttack>=1);advance(e,2.1);a.equal(e.sceneState,'EXIT_OPEN');a.equal(e.boss.unlocked,true);a.equal(e.events.doorUnlock,1);a.notEqual(e.status,'clear');
 e.player.x=e.stage.goal.x;e.player.y=e.stage.goal.y;e.step(1/120,{});a.equal(e.status,'clear',`${id} clears only after entering the unlocked door`);
}
const adventure=new H.WorldEngine(H.buildWorldStage('1-2'));a.ok(adventure.stage.length>=5000);a.deepEqual(Array.from(adventure.stage.sections,x=>x.id),['start','move','enemy','blocks','platform','final']);a.ok(['breakable','reward','hard'].every(kind=>adventure.stage.blocks.some(b=>b.kind===kind)));a.ok(adventure.stage.platforms.some(p=>p.motion));
const walker=adventure.stage.enemies.find(e=>!e.armored);adventure.player.x=walker.x;adventure.player.y=walker.y-adventure.player.h-1;adventure.player.velocityY=180;adventure.player.isGrounded=false;adventure.step(1/120,{});a.equal(walker.defeated,true);a.ok(adventure.player.velocityY<0);a.equal(adventure.events.enemyStomp,1);
const side=new H.WorldEngine(H.buildWorldStage('1-2')),sideEnemy=side.stage.enemies.find(e=>!e.armored);side.player.x=sideEnemy.x-side.player.w+5;side.player.y=sideEnemy.y;side.step(1/120,{});a.equal(side.player.hp,2,'small player loses one life on fatal side contact');a.equal(side.status,'dead');
const armor=adventure.stage.enemies.find(e=>e.armored);adventure.player.x=armor.x;adventure.player.y=armor.y-adventure.player.h-1;adventure.player.velocityY=180;adventure.player.isGrounded=false;adventure.step(1/120,{});a.equal(armor.state,'shell');adventure.player.x=armor.x;adventure.player.y=armor.y-adventure.player.h-1;adventure.player.velocityY=180;adventure.player.isGrounded=false;adventure.step(1/120,{});a.equal(armor.state,'rolling');
const rewardBlock=adventure.stage.blocks.find(b=>b.kind==='reward'&&b.rewardId==='letter-1'),reward=adventure.stage.items.find(i=>i.id==='letter-1');adventure.player.x=rewardBlock.x+5;adventure.player.y=rewardBlock.y+rewardBlock.h+1;adventure.player.velocityY=-500;adventure.player.isGrounded=false;adventure.step(1/120,{});a.equal(rewardBlock.used,true);a.equal(reward.contained,false);a.equal(adventure.events.rewardPop,1);
const breakable=adventure.stage.blocks.find(b=>b.kind==='breakable');adventure.player.powerState='big';adventure.player.x=breakable.x+5;adventure.player.y=breakable.y+breakable.h+1;adventure.player.velocityY=-500;adventure.player.isGrounded=false;adventure.step(1/120,{});a.equal(breakable.removed,true);a.equal(adventure.events.blockBreak,1);
const rolling=new H.WorldEngine(H.buildWorldStage('1-2')),roller=rolling.stage.enemies.find(e=>e.armored),rollingTarget=rolling.stage.enemies.find(e=>e!==roller),rollingBlock=rolling.stage.blocks.find(b=>b.kind==='breakable');rolling.player.x=0;roller.state='rolling';roller.left=0;roller.right=rolling.stage.length;roller.dir=1;roller.x=rollingTarget.x-roller.w+2;roller.y=rollingTarget.y;roller.baseY=rollingTarget.y;rolling.step(1/120,{});a.equal(rollingTarget.defeated,true);a.equal(rolling.events.enemyCombo,1);roller.x=rollingBlock.x+10;roller.y=rollingBlock.y;roller.baseY=rollingBlock.y;rolling.step(1/120,{});a.equal(rollingBlock.removed,true);a.equal(rolling.events.rollingBreak,1);
const normalGoal=new H.WorldEngine(H.buildWorldStage('1-1'));for(let i=0;i<normalGoal.stage.words.length;i++){const item=normalGoal.stage.items.find(v=>v.id===`letter-${i}`);item.contained=false;normalGoal.player.x=item.x;normalGoal.player.y=item.y;normalGoal.step(1/120,{})}normalGoal.player.x=normalGoal.stage.goal.x;normalGoal.player.y=normalGoal.stage.goal.y;normalGoal.step(1/120,{});a.equal(normalGoal.status,'clear');
const underground=new H.WorldEngine(H.buildWorldStage('4-2'));underground.player.x=300;underground.player.y=300;underground.step(1/120,{jump:true});a.equal(underground.mode,'swim');
const oceanOrdered=new H.WorldEngine(H.buildWorldStage('2-3'));oceanOrdered.player.invincible=999;for(let i=0;i<20*120;i++)oceanOrdered.step(1/120,{right:true});a.ok(oceanOrdered.player.x>2600,'2-3 can move beyond the former invisible 241m gate');
for(const stageData of H.worldStages){const stage=H.buildWorldStage(stageData.id);for(const gate of stage.gates||[]){const e=new H.WorldEngine(stage);e.sequence=0;e.player.invincible=999;e.player.x=gate.x-e.player.w-2;e.player.y=200;for(let i=0;i<40;i++)e.step(1/120,{right:true});a.ok(e.player.x>gate.x,`${stage.id} never uses an invisible movement gate`);}}
const enemyStages=H.worldStages.map(s=>H.buildWorldStage(s.id)),enemyKinds=new Set(enemyStages.flatMap(s=>s.enemies.map(e=>e.kind)));for(const kind of ['berry-bandit','seed-shell','pipe-snapper','fire-imp','bubble-puffer','reef-crab','ink-sprite','cloud-rascal','storm-bat','spark-drake','tunnel-bat','gear-shell'])a.ok(enemyKinds.has(kind),`enemy catalog contains ${kind}`);a.ok(H.buildWorldStage('1-4').enemies.length>H.buildWorldStage('1-1').enemies.length,'later forest rounds contain more villains');a.ok(enemyStages.flatMap(s=>s.enemies).some(e=>(e.hp||1)>1),'later enemies gain durability');
const fireStage=H.buildWorldStage('1-4'),fireEngine=new H.WorldEngine(fireStage),fireEnemy=fireStage.enemies.find(e=>e.kind==='fire-imp');fireEngine.player.x=fireEnemy.x-200;fireEngine.player.y=fireEnemy.y;fireEnemy.shotCooldown=0;fireEngine.step(1/120,{});a.ok(fireEngine.enemyShots.some(s=>s.kind==='fire'),'fire villains launch visible projectiles');
const wrongChoice=new H.WorldEngine(H.buildWorldStage('1-4'),{viewport:640});for(const item of wrongChoice.stage.items.filter(v=>v.kind==='letter')){item.contained=false;wrongChoice.player.x=item.x;wrongChoice.player.y=item.y;wrongChoice.step(1/120,{})}wrongChoice.player.x=wrongChoice.stage.goal.x;wrongChoice.player.y=wrongChoice.stage.goal.y;wrongChoice.step(1/120,{});advance(wrongChoice,5);wrongChoice.player.invincible=0;for(let wait=0;wait<5&&!wrongChoice.boss.choices.length;wait+=.1)advance(wrongChoice,.1);const orderedChoices=[...wrongChoice.boss.choices].sort((x,y)=>x.x-y.x);for(const screenWidth of [320,390,430])for(let i=1;i<orderedChoices.length;i++)a.ok((orderedChoices[i].x-orderedChoices[i-1].x)*screenWidth/640>=69,`${screenWidth}px keeps independently selectable horizontal targets`);a.ok(Math.max(...orderedChoices.map(v=>v.x+v.w))<wrongChoice.boss.x,'mobile choices stay clear of the boss');const hpBeforeWrong=wrongChoice.player.hp,wrong=wrongChoice.boss.choices.find(v=>!v.correct);wrongChoice.player.x=wrong.x;wrongChoice.player.y=wrong.y;wrongChoice.step(1/120,{});a.equal(wrongChoice.player.hp,hpBeforeWrong,'wrong boss letters do not damage young players');a.equal(wrongChoice.events.wrong,1);
const ui=fs.readFileSync('js/games/hangul-runner.js','utf8'),html=fs.readFileSync('index.html','utf8'),renderer=fs.readFileSync('js/games/hangul-runner/renderer.js','utf8');
for(const token of ['hr-world-map','data-world-stage','recordWorldClear','WorldEngine'])a(ui.includes(token),`UI contains ${token}`);
for(const token of ['TRANSITION','BOSS_INTRO','BOSS_STAGE','BOSS_DEFEATED','EXIT_OPEN'])a(renderer.includes(token),`renderer owns ${token}`);
a(!renderer.includes('열린 별빛 문'));a(renderer.includes('별빛 신호가 켜졌어요'));a(fs.readFileSync('js/games/hangul-runner/engine.js','utf8').includes('viewport*.31'));
for(const module of ['world-data','world-engine','world-forest','world-ocean','world-sky','world-underground','boss'])a(html.includes(`hangul-runner/${module}.js`),`${module} loaded`);
console.log('PASS separate run/transition/boss arenas, answer projectiles, boss attacks, defeat, unlock and door clear');
