/* QA entry uses the production adapter, art loader, controls and simulation; saves disabled. */
(function(){
 const width=document.getElementById('review-width'),stage=document.getElementById('review-stage'),metrics=document.getElementById('review-metrics');
 let currentEngine=null;let frames=0,total=0,max=0,previous=0,interval=0,lastText=0;
 const paint=HangulRunner.Renderer.prototype.paint;
 HangulRunner.Renderer.prototype.paint=function(e){currentEngine=e;const t=performance.now();paint.call(this,e);const cost=performance.now()-t;frames++;total+=cost;max=Math.max(max,cost);if(previous)interval+=Math.min(1000,t-previous);previous=t;if(t-lastText>1000){lastText=t;const r=document.querySelector('.hr-shell'),canvas=r?.querySelector('canvas'),touch=r?.querySelector('.hr-touch'),cr=canvas?.getBoundingClientRect(),tr=touch?.getBoundingClientRect();metrics.textContent=`발사 ${e.events.starShot||0} · 명중 ${e.events.enemyStarDefeat||0} · ${e.stage.id} · ${width.value}px · 그리기 ${(total/frames).toFixed(1)}ms · ${frames}프레임 · ${r?.dataset.playerState||''}`;metrics.dataset.stage=e.stage.id;metrics.dataset.paintMeanMs=(total/frames).toFixed(2);metrics.dataset.paintMaxMs=max.toFixed(2);metrics.dataset.frames=frames;metrics.dataset.canvasWidth=cr?.width.toFixed(1);metrics.dataset.controlsOverlap=String(!!(cr&&tr&&tr.top<cr.bottom));metrics.dataset.contentOverflow=String(r?r.scrollWidth>r.clientWidth+1:false);}};
 const assist=document.createElement('select');assist.id='aim-case';assist.setAttribute('aria-label','조준 검증 대상');for(const [value,label] of [['ground','작은 지상 적'],['air','공중 적'],['lower','아래 적'],['rear','뒤쪽 적'],['empty','적 없음']]){const o=document.createElement('option');o.value=value;o.textContent=label;assist.append(o);}const setup=document.createElement('button');setup.textContent='조준 장면 준비';document.querySelector('.review-toolbar').append(assist,setup);setup.onclick=()=>{const e=currentEngine;if(!e)return;e.stage.platforms=[{x:0,y:424,w:2000,h:180}];e.stage.blocks=[];e.stage.items=[];e.stage.hazards=[];e.stage.length=2000;e.player.x=90;e.player.y=280;e.setForm('star_power');e.player.invincible=.6;e.cameraX=0;const kind=assist.value;e.stage.enemies=kind==='empty'?[]:[{id:'qa-aim',kind:e.stage.worldId===2?'puffer':'slime',x:kind==='rear'?0:290,y:kind==='air'?270:kind==='lower'?390:396,w:28,h:28,hp:1,speed:0,left:290,right:290,dir:1,baseY:kind==='air'?270:396,phase:0}];metrics.textContent='검증 장면 · 실제 ★ 발사 버튼을 누르세요';};
 function applyWidth(){game.style.setProperty('width',width.value+'px','important');}
 async function restart(){frames=total=max=previous=interval=0;applyWidth();await HangulRunner.start({reviewStage:stage.value});}
 width.onchange=applyWidth;stage.onchange=restart;document.getElementById('review-restart').onclick=restart;
 window.openGameWorld=restart;window.render=()=>{};
 restart();
})();
