const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const ctx=vm.createContext({});for(const f of ['stage-data','engine','world-data','world-engine','world-forest','world-ocean','world-sky','world-underground','world-expansion','boss'])vm.runInContext(fs.readFileSync(`js/games/hangul-runner/${f}.js`,'utf8'),ctx);
const H=ctx.HangulRunner,e=new H.WorldEngine(H.buildWorldStage('1-1'));
assert.equal(e.player.powerState,'small');assert.equal(e.player.h,64);
for(const form of ['big','small']){const feet=e.player.y+e.player.h;e.setForm(form);assert.equal(e.player.y+e.player.h,feet);for(let i=0;i<20;i++)e.step(.02,{});assert.equal(e.player.y+e.player.h,420);const s={w:160,h:250,sole:238},r=H.playerRenderBounds(e.player,s);assert.equal(r.y+r.h*s.sole/s.h,420);assert.equal(r.feet,420);}
console.log('PASS SMALL/BIG dimensions, invariant sole and physical landing');
const growth=new H.WorldEngine(H.buildWorldStage('1-1'));const soles=growth.player.y+growth.player.h;growth.grow();assert.equal(growth.player.powerState,'big');assert.equal(growth.player.h,96);assert.equal(growth.player.w,46);assert.equal(growth.player.y+growth.player.h,soles);assert(growth.player.growthTime>0);growth.damage();assert.equal(growth.player.powerState,'small');assert.equal(growth.status,'playing');assert.equal(growth.playerState,'INVINCIBLE_TEMP');growth.damage();assert.equal(growth.status,'playing');growth.player.invincible=0;growth.damage();assert.equal(growth.playerState,'DEAD');const deadX=growth.player.x;growth.step(.02,{right:true,jump:true});assert.equal(growth.player.x,deadX);assert(growth.player.velocityY<0);for(let i=0;i<50;i++)growth.step(.02,{});assert.equal(growth.status,'playing');assert.equal(growth.player.powerState,'small');assert.equal(growth.player.hp,2);
const low=new H.WorldEngine(H.buildWorldStage('1-1'));low.stage.blocks.push({x:50,y:310,w:100,h:35,kind:'hard',revealed:true});low.grow();assert(low.player.pendingGrowth);assert.equal(low.player.h,64);low.player.x=10;low.step(.02,{});assert.equal(low.player.powerState,'big');assert.equal(low.player.y+low.player.h,420);
console.log('PASS growth, ceiling clearance, shrink, immunity, death animation and checkpoint life');
for(const width of [320,390,430])for(const form of ['small','big']){
 const swim=new H.WorldEngine(H.buildWorldStage('2-3'),{viewport:640});swim.stage.enemies=[];swim.stage.hazards=[];swim.stage.items=swim.stage.items.filter(i=>i.contained);swim.setForm(form);const block=swim.stage.blocks.find(b=>b.kind==='reward');swim.player.x=block.x+4;swim.player.y=block.y+block.h+2;
 for(let i=0;i<100;i++)swim.step(.02,{down:true});assert.equal(swim.player.y+swim.player.h,510,`${width} ${form} reaches seabed`);assert(swim.player.y>block.y+block.h);
 for(let i=0;i<150&&!block.used;i++)swim.step(.02,{jump:true});assert(block.used,`${width} ${form} swims up to block`);
}
for(const form of ['small','big']){const sim=new H.WorldEngine(H.buildWorldStage('1-1'));sim.stage.items=[];sim.stage.enemies=[];sim.setForm(form);const b=sim.stage.blocks.find(b=>b.kind==='breakable');sim.player.x=b.x+4;sim.player.y=420-sim.player.h;sim.player.isGrounded=true;for(let i=0;i<45&&!sim.events.blockHit;i++)sim.step(.02,{jump:true});assert(sim.events.blockHit);assert.equal(!!b.removed,form==='big');if(form==='big')assert(sim.particles.length);}
console.log('PASS small/big jump block contacts, BIG-only break, underwater floor and block ascent at all mobile layout widths');
for(const form of ['small','big'])for(const cause of ['fall','lava']){const sim=new H.WorldEngine(H.buildWorldStage('1-1'));sim.setForm(form);sim.player.invincible=1.5;if(cause==='fall')sim.player.y=610;else sim.stage.hazards.push({kind:'lava',x:sim.player.x,y:sim.player.y,w:50,h:100});sim.step(.02,{});assert.equal(sim.status,'dead',form+' '+cause);assert.equal(sim.player.hp,2);}
const pipe=new H.WorldEngine(H.buildWorldStage('1-3')),plant=pipe.stage.enemies.find(e=>e.kind==='cactus');plant.phase=0;pipe.elapsed=0;pipe.beforePhysics(.02);assert(plant.retracted);assert.equal(plant.stompable,false);assert(pipe.stage.platforms.some(p=>p.kind==='drain'&&p.x===plant.x-8));pipe.elapsed=2.5;pipe.beforePhysics(.02);assert(!plant.retracted);pipe.player.x=plant.x;pipe.player.y=plant.y;pipe.player.invincible=0;pipe.step(.01,{});assert.equal(pipe.status,'dead');
console.log('PASS lethal pits/lava bypass size and immunity, drain collider and exposed plant contact');
