const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const ctx=vm.createContext({});for(const f of ['stage-data','engine','world-data','world-engine','world-forest','world-ocean','world-sky','world-underground','world-expansion','boss'])vm.runInContext(fs.readFileSync(`js/games/hangul-runner/${f}.js`,'utf8'),ctx);
const H=ctx.HangulRunner,e=new H.WorldEngine(H.buildWorldStage('1-1'));
assert.equal(e.player.powerState,'small');assert.equal(e.player.h,64);
for(const form of ['big','small']){const feet=e.player.y+e.player.h;e.setForm(form);assert.equal(e.player.y+e.player.h,feet);for(let i=0;i<20;i++)e.step(.02,{});assert.equal(e.player.y+e.player.h,420);const s={w:160,h:250,sole:238},r=H.playerRenderBounds(e.player,s);assert.equal(r.y+r.h*s.sole/s.h,420);assert.equal(r.feet,420);}
console.log('PASS SMALL/BIG dimensions, invariant sole and physical landing');
const growth=new H.WorldEngine(H.buildWorldStage('1-1'));const soles=growth.player.y+growth.player.h;growth.grow();assert.equal(growth.player.powerState,'big');assert.equal(growth.player.h,96);assert.equal(growth.player.w,46);assert.equal(growth.player.y+growth.player.h,soles);assert(growth.player.growthTime>0);growth.damage();assert.equal(growth.player.powerState,'small');assert.equal(growth.status,'playing');assert.equal(growth.playerState,'INVINCIBLE_TEMP');growth.damage();assert.equal(growth.status,'playing');growth.player.invincible=0;growth.damage();assert.equal(growth.playerState,'DEAD');const deadX=growth.player.x;growth.step(.02,{right:true,jump:true});assert.equal(growth.player.x,deadX);assert(growth.player.velocityY<0);for(let i=0;i<50;i++)growth.step(.02,{});assert.equal(growth.status,'playing');assert.equal(growth.player.powerState,'small');assert.equal(growth.player.hp,2);
const low=new H.WorldEngine(H.buildWorldStage('1-1'));low.stage.blocks.push({x:50,y:310,w:100,h:35,kind:'hard',revealed:true});low.grow();assert(low.player.pendingGrowth);assert.equal(low.player.h,64);low.player.x=10;low.step(.02,{});assert.equal(low.player.powerState,'big');assert.equal(low.player.y+low.player.h,420);
console.log('PASS growth, ceiling clearance, shrink, immunity, death animation and checkpoint life');
