(function(R){
  const pct=(v,m)=>Math.max(0,Math.round(v/m*100));
  R.startBattle=function(root,build,difficulty="normal"){
    Session.begin();const engine=new R.BattleEngine(build,difficulty);root.innerHTML=`<div class="robotBattle"><header class="robotBattleHead"><b>🤖 ${build.name} VS 스파크봇</b><button data-exit>← 메이커</button></header><div class="battleHud"><span>나 <i data-php></i></span><strong data-state>READY!</strong><span>AI <i data-ehp></i></span></div><canvas width="900" height="470" aria-label="실시간 로봇 배틀"></canvas><div class="battleMobile"><div class="battleStick" data-stick><i></i></div><div class="battleActions"><button data-act="attack">ATTACK</button><button data-act="skill">SKILL</button><button data-act="jump">JUMP</button><button data-act="guard">GUARD</button><button data-act="dash">DASH</button></div></div><p class="battleKeys">WASD 이동 · Space 점프 · J 공격 · K 스킬 · L 가드 · Shift 대시</p><div class="battleResult" hidden></div></div>`;
    const canvas=root.querySelector("canvas"),stateEl=root.querySelector("[data-state]"),php=root.querySelector("[data-php]"),ehp=root.querySelector("[data-ehp]"),activePointers=new Map();let last=performance.now(),finished=false;
    const action=a=>{if(a==="attack")engine.attack(engine.player);if(a==="skill")engine.attack(engine.player,true);if(a==="jump")engine.jump(engine.player);if(a==="dash")engine.dash(engine.player)};
    Session.key(e=>{if(["ArrowLeft","ArrowRight"," "].includes(e.key))e.preventDefault();if(e.key==="a"||e.key==="A"||e.key==="ArrowLeft")engine.input.left=true;if(e.key==="d"||e.key==="D"||e.key==="ArrowRight")engine.input.right=true;if(e.key===" "||e.key==="w"||e.key==="W")action("jump");if(e.key==="j"||e.key==="J")action("attack");if(e.key==="k"||e.key==="K")action("skill");if(e.key==="l"||e.key==="L")engine.input.guard=true;if(e.key==="Shift")action("dash")});
    const keyup=e=>{if(e.key==="a"||e.key==="A"||e.key==="ArrowLeft")engine.input.left=false;if(e.key==="d"||e.key==="D"||e.key==="ArrowRight")engine.input.right=false;if(e.key==="l"||e.key==="L")engine.input.guard=false};document.addEventListener("keyup",keyup);
    const stick=root.querySelector("[data-stick]");stick.onpointerdown=e=>{stick.setPointerCapture?.(e.pointerId);activePointers.set(e.pointerId,"stick")};stick.onpointermove=e=>{if(activePointers.get(e.pointerId)!=="stick")return;const r=stick.getBoundingClientRect(),d=e.clientX-(r.left+r.width/2);engine.input.left=d<-8;engine.input.right=d>8;stick.querySelector("i").style.transform=`translateX(${Math.max(-28,Math.min(28,d))}px)`};
    root.querySelectorAll("[data-act]").forEach(b=>{b.onpointerdown=e=>{e.preventDefault();activePointers.set(e.pointerId,b.dataset.act);b.classList.add("pressed");if(b.dataset.act==="guard")engine.input.guard=true;else action(b.dataset.act)};b.onpointerup=b.onpointercancel=e=>{activePointers.delete(e.pointerId);b.classList.remove("pressed");if(b.dataset.act==="guard")engine.input.guard=false}});
    const release=e=>{if(activePointers.get(e.pointerId)==="stick"){engine.input.left=engine.input.right=false;stick.querySelector("i").style.transform=""}activePointers.delete(e.pointerId)};stick.onpointerup=stick.onpointercancel=release;
    function loop(now){const dt=Math.min(2,(now-last)/16.67);last=now;engine.tick(dt);R.drawBattle(canvas,engine,build);php.style.setProperty("--hp",pct(engine.player.hp,engine.player.maxHp)+"%");ehp.style.setProperty("--hp",pct(engine.enemy.hp,engine.enemy.maxHp)+"%");stateEl.textContent=engine.player.guard?"GUARD":engine.player.skill?"SKILL!":"BATTLE";if(engine.over&&!finished){finished=true;const win=engine.result==="win",box=root.querySelector(".battleResult");build.record[win?"wins":"losses"]++;R.store.saveRobot(build);if(win){const id="robot-win-"+difficulty;if(!state.completed[id]){state.completed[id]=Date.now();state.stars+=2;save()}}box.hidden=false;box.innerHTML=`<h2>${win?"ARENA WIN! ⭐":"GOOD TRY!"}</h2><p>${win?"별 2개와 배틀 기록을 얻었어요.":"부품을 바꾸고 다시 도전해 봐요."}</p><button data-rematch>다시 배틀</button><button data-maker>로봇 고치기</button>`;box.querySelector("[data-rematch]").onclick=()=>R.startBattle(root,build,difficulty);box.querySelector("[data-maker]").onclick=R.start;return}Session.frame(loop)}
    root.querySelector("[data-exit]").onclick=R.start;Session.cleanup(()=>{document.removeEventListener("keyup",keyup);activePointers.clear();engine.input.left=engine.input.right=engine.input.guard=false});Session.frame(loop);
  };
  const startMaker=R.start;
  R.start=function(){startMaker();const saveButton=gameBody.querySelector(".robotSave");if(!saveButton)return;saveButton.insertAdjacentHTML("afterend",`<div class="robotBattleChoice"><select aria-label="AI 난이도"><option value="easy">EASY</option><option value="normal" selected>NORMAL</option><option value="hard">HARD</option></select><button class="robotBattleStart">⚡ AI 배틀 시작</button></div>`);gameBody.querySelector(".robotBattleStart").onclick=()=>{R.store.saveRobot(buildFromMaker());R.startBattle(gameBody,R.store.active(),gameBody.querySelector(".robotBattleChoice select").value)}};
  function buildFromMaker(){gameBody.querySelector(".robotSave")?.click();return R.store.active()}
})(window.SianRobot);
