(function(R){
 const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
 const weapons={blaster:{range:10,damage:9,cooldown:.55,shot:true},sword:{range:2,damage:15,cooldown:.58},hammer:{range:2.25,damage:25,cooldown:1.1},drill:{range:1.8,damage:7,cooldown:.28},guard:{range:1.6,damage:8,cooldown:.6}};
 class Fighter{constructor(build,x,z){this.build=JSON.parse(JSON.stringify(build));this.stats=R.stats(build);Object.assign(this,{x,z,y:0,vy:0,angle:0,hp:this.stats.hp,energy:this.stats.energy,cooldown:0,hurt:0,flash:0,dash:0,dashCooldown:0,guard:false,guardWanted:false,shield:this.stats.defense*2.4,shieldMax:this.stats.defense*2.4,shieldCooldown:0,shieldRipple:0,attackPose:0,attackState:null,motionState:'idle',land:0,walking:false,knockX:0,knockZ:0});}}
 R.BattleEngine=class{
  constructor(build,difficulty='normal'){
   this.difficulty=difficulty;this.player=new Fighter(build,-4,0);const enemy=R.defaultBuild();enemy.name='스파크봇';for(const slot of R.slots){enemy.parts[slot]=R.parts[slot][Math.floor(Math.random()*R.parts[slot].length)].id;enemy.colors[slot]={primary:'#ff668e',secondary:'#744db8',accent:'#ffdf69'};}
   this.enemy=new Fighter(enemy,4,0);this.enemy.angle=-Math.PI/2;this.player.angle=Math.PI/2;this.input={x:0,z:0,guard:false};this.projectiles=[];this.particles=[];this.pending=[];this.events={};this.time=0;this.shake=0;this.over=false;this.result=null;this.aiTimer=0;this.aiMove={x:0,z:0};
  }
  emit(type){this.events[type]=(this.events[type]||0)+1;}
  jump(f){if(!this.over&&f.y===0){f.vy=6+f.stats.jump*.04;return true;}return false;}
  dash(f){if(this.over||f.dashCooldown>0||f.energy<16)return false;f.energy-=16;f.dash=.2;f.dashCooldown=1;return true;}
  burst(x,y,z,color='spark',amount=18){for(let i=0;i<amount;i++)this.particles.push({kind:color,x,y,z,life:.25+Math.random()*.3,vx:(Math.random()-.5)*6,vy:1+Math.random()*4,vz:(Math.random()-.5)*6,scale:.07+Math.random()*.13});}
  breakShield(target){target.guard=false;target.guardWanted=false;target.shield=0;target.shieldCooldown=2.2;target.shieldRipple=.35;this.burst(target.x,target.y+1.35,target.z,'shieldBreak',24);this.emit('shieldBreak');}
  hit(target,amount,source){if(target.hurt>0||target.dash>0)return false;const guarded=target.guard&&target.shield>0;if(guarded){target.shield-=amount;target.energy=clamp(target.energy-amount*.32,0,target.stats.energy);target.shieldRipple=.22;this.burst(target.x,target.y+1.45,target.z,'guard',12);this.shake=.07;this.emit('guardHit');if(target.shield<=0||target.energy<=0)this.breakShield(target);return true;}target.hp=clamp(target.hp-Math.max(1,amount-target.stats.defense*.12),0,target.stats.hp);target.hurt=.25;target.flash=.15;if(source){const dx=target.x-source.x,dz=target.z-source.z,d=Math.hypot(dx,dz)||1;target.knockX=dx/d*3.5;target.knockZ=dz/d*3.5;}this.burst(target.x,target.y+1.45,target.z,'spark',22);this.shake=.18;this.emit('hit');return true;}
  schedule(time,run){this.pending.push({time,run});}
  skillKind(f){const weapon=f.build.parts.weapon;if(weapon==='guard')return 'barrier';if(weapon==='hammer')return 'groundBreaker';if(weapon==='drill')return 'drillRush';if(weapon==='sword')return 'energySlash';if(f.build.parts.head==='dino')return 'dragonEnergy';if(f.build.parts.back==='pack')return 'missileBarrage';if(f.build.parts.back==='jet')return 'laserBeam';return 'energyCannon';}
  projectile(f,damage,kind='energy',speed=12,target,extra={}){
   const aim=target||(f===this.player?this.enemy:this.player),dx=aim.x-f.x,dz=aim.z-f.z,d=Math.hypot(dx,dz)||1,direction={x:dx/d,z:dz/d};
   f.angle=Math.atan2(direction.x,direction.z);
   const lifetime=kind==='shockwave'?1.5:2.2;
   this.projectiles.push({owner:f,kind,position:{x:f.x+direction.x*.82,y:f.y+(kind==='shockwave'?.18:1.45),z:f.z+direction.z*.82},velocity:{x:direction.x*speed,y:0,z:direction.z*speed},direction,speed,damage,lifetime,life:lifetime,radius:kind==='shockwave'?1:kind==='laser'||kind==='dragonEnergy'?.92:.68,x:f.x+direction.x*.82,z:f.z+direction.z*.82,y:f.y+(kind==='shockwave'?.18:1.45),...extra});
   this.burst(f.x+direction.x*.72,f.y+1.4,f.z+direction.z*.72,kind==='shockwave'?'wave':'muzzle',10);this.emit('launch');
  }
  melee(f,target,w,skill,multiplier=1){const dx=target.x-f.x,dz=target.z-f.z,d=Math.hypot(dx,dz),front=d===0?1:(dx*Math.sin(f.angle)+dz*Math.cos(f.angle))/d;const bonus=skill?(f.build.parts.weapon==='sword'?1.1:.7):0;if(d<w.range+bonus&&front>.2&&Math.abs(target.y-f.y)<1.35){this.hit(target,(w.damage+f.stats.power*.2)*(skill?1.8:1)*multiplier,f);return true;}this.emit('miss');return false;}
  attack(f,skill=false){
   if(this.over||f.cooldown>0||f.guard||(skill&&f.energy<30))return false;const weapon=f.build.parts.weapon,w=weapons[weapon]||weapons.blaster,target=f===this.player?this.enemy:this.player,damage=w.damage+f.stats.power*.2;
   const skillType=skill?this.skillKind(f):null,charge=skill?.72:.34;f.cooldown=w.cooldown*(skill?1.75:1);f.attackPose=charge;f.attackState={weapon,skill,skillType,phase:skill?'charge':'windup',duration:charge};if(skill){f.energy-=30;this.emit('skillCharge');}else this.emit('attack');
   if(weapon==='guard'&&skill){f.shieldTime=2;f.shield=Math.min(f.shieldMax*1.35,f.shield+f.shieldMax*.7);f.guard=true;this.emit('guard');return true;}
   const aim={x:target.x,y:target.y,z:target.z};
   if(!skill&&weapon==='blaster')this.schedule(.18,()=>this.projectile(f,damage,'energy',13,aim));
   else if(skillType==='energyCannon')this.schedule(.72,()=>this.projectile(f,damage*2.15,'energyBall',9,aim));
   else if(skillType==='laserBeam')this.schedule(.72,()=>this.projectile(f,damage*2.05,'laser',18,aim));
   else if(skillType==='dragonEnergy')this.schedule(.72,()=>this.projectile(f,damage*2.35,'dragonEnergy',10,aim));
   else if(skillType==='missileBarrage')for(let i=0;i<4;i++)this.schedule(.68+i*.1,()=>this.projectile(f,damage*.62,'missile',8.5,{x:target.x+(i-1.5)*.35,y:target.y,z:target.z},{homing:.65,curve:(i-1.5)*.8}));
   else if(skillType==='groundBreaker')this.schedule(.68,()=>this.projectile(f,damage*1.85,'shockwave',8,aim));
   else if(skillType==='drillRush')for(let i=0;i<5;i++)this.schedule(.48+i*.09,()=>this.melee(f,target,w,true,.42));
   else this.schedule(skill?.58:.16,()=>this.melee(f,target,w,skill));return true;
  }
  move(f,x,z,dt){const n=Math.hypot(x,z);f.walking=n>.05;if(n>.05){x/=Math.max(1,n);z/=Math.max(1,n);f.angle=Math.atan2(x,z);}const speed=(2.5+f.stats.speed*.045)*(f.guard?.35:1),boost=f.dash>0?4:1;if(f.dash>0){x=Math.sin(f.angle);z=Math.cos(f.angle);}f.x=clamp(f.x+(x*speed*boost+f.knockX)*dt,-8,8);f.z=clamp(f.z+(z*speed*boost+f.knockZ)*dt,-6,6);f.knockX*=Math.exp(-dt*11);f.knockZ*=Math.exp(-dt*11);}
  ai(dt){const a=this.enemy,p=this.player,dx=p.x-a.x,dz=p.z-a.z,d=Math.hypot(dx,dz)||1;a.angle=Math.atan2(dx,dz);this.aiTimer-=dt;if(this.aiTimer<=0){this.aiTimer={easy:.7,normal:.4,hard:.2}[this.difficulty];const ranged=a.build.parts.weapon==='blaster',ideal=ranged?4:1.2,dir=d>ideal?1:d<ideal*.6?-1:0;this.aiMove={x:dx/d*dir,z:dz/d*dir};a.guardWanted=p.attackPose>0&&d<2.6&&Math.random()<.65;if(d<6&&Math.random()>.2)this.attack(a,a.energy>50&&Math.random()<.35);if(this.difficulty!=='easy'&&this.projectiles.some(q=>q.owner===p&&Math.hypot(q.x-a.x,q.z-a.z)<3)){this.aiMove={x:-dz/d,z:dx/d};this.dash(a);}if(this.difficulty==='hard'&&Math.random()<.16)this.jump(a);}this.move(a,this.aiMove.x,this.aiMove.z,dt);a.angle=Math.atan2(p.x-a.x,p.z-a.z);}
  tick(dt){if(this.over)return;dt=clamp(dt,0,.05);this.time+=dt;this.shake=Math.max(0,this.shake-dt);this.player.guardWanted=this.input.guard;this.move(this.player,this.input.x,this.input.z,dt);this.ai(dt);
   for(const f of [this.player,this.enemy]){for(const key of ['cooldown','hurt','flash','dash','dashCooldown','attackPose','shieldTime','shieldCooldown','shieldRipple','land'])f[key]=Math.max(0,(f[key]||0)-dt);if(f.attackPose===0)f.attackState=null;const wantsGuard=(f.guardWanted||f.shieldTime>0)&&f.shieldCooldown===0&&f.energy>0;f.guard=wantsGuard;if(f.guard){f.energy=clamp(f.energy-9*dt,0,f.stats.energy);if(f.energy===0)this.breakShield(f);}else{f.energy=clamp(f.energy+7*dt,0,f.stats.energy);if(f.shieldCooldown===0)f.shield=clamp(f.shield+f.shieldMax*.18*dt,0,f.shieldMax);}if(f.y>0||f.vy>0){const wasAir=f.y>0;f.vy-=15*dt;f.y=Math.max(0,f.y+f.vy*dt);if(f.y===0){f.vy=0;if(wasAir)f.land=.16;}}f.motionState=f.hp<=0?'defeat':f.hurt>0?'hit':f.guard?'guard':f.attackState?.skill?(f.attackPose>.18?'skillCharge':'skillFire'):f.attackState?'attack':f.dash>0?'dash':f.y>0?'jump':f.land>0?'land':f.walking?'run':'idle';}
   for(const action of this.pending){action.time-=dt;if(action.time<=0&&!action.done){action.done=true;action.run();}}this.pending=this.pending.filter(a=>!a.done);
   for(const q of this.projectiles){const target=q.owner===this.player?this.enemy:this.player;if(q.homing){const dx=target.x-q.x,dz=target.z-q.z,d=Math.hypot(dx,dz)||1,turn=clamp(q.homing*dt,0,.08);q.direction.x=q.direction.x*(1-turn)+dx/d*turn;q.direction.z=q.direction.z*(1-turn)+dz/d*turn;const n=Math.hypot(q.direction.x,q.direction.z)||1;q.direction.x/=n;q.direction.z/=n;q.velocity.x=q.direction.x*q.speed;q.velocity.z=q.direction.z*q.speed;}if(q.curve){const nx=-q.direction.z,nz=q.direction.x;q.velocity.x+=nx*q.curve*dt*3;q.velocity.z+=nz*q.curve*dt*3;}const ox=q.x,oz=q.z;q.x+=q.velocity.x*dt;q.z+=q.velocity.z*dt;q.position.x=q.x;q.position.y=q.y;q.position.z=q.z;q.life-=dt;q.lifetime=q.life;this.particles.push({kind:q.kind==='shockwave'?'waveTrail':q.kind==='missile'?'smoke':'trail',x:q.x,y:q.y,z:q.z,life:.16,vx:0,vy:0,vz:0,scale:q.kind==='energyBall'||q.kind==='dragonEnergy'?.2:.08});const vx=q.x-ox,vz=q.z-oz,den=vx*vx+vz*vz,f=den?clamp(((target.x-ox)*vx+(target.z-oz)*vz)/den,0,1):0,close=Math.hypot(ox+f*vx-target.x,oz+f*vz-target.z)<q.radius;const vertical=q.kind==='shockwave'?target.y<.45:q.y>=target.y+.1&&q.y<=target.y+2.8;if(close&&vertical){if(this.hit(target,q.damage,q.owner)){this.burst(target.x,target.y+1.4,target.z,q.kind==='shockwave'?'wave':q.kind==='missile'?'missileBlast':'blast',q.kind==='missile'?18:28);this.particles.push({kind:'impactRing',x:target.x,y:target.y+1.35,z:target.z,life:.3,vx:0,vy:0,vz:0,scale:.35});}q.life=0;}}
   this.projectiles=this.projectiles.filter(q=>q.life>0);this.particles=this.particles.filter(p=>{p.life-=dt;if(p.owner){p.x=p.owner.x;p.y=p.owner.y+1.4;p.z=p.owner.z;}else{p.x+=(p.vx||0)*dt;p.z+=(p.vz||0)*dt;p.y+=(p.vy||0)*dt;if(p.vy)p.vy-=7*dt;}return p.life>0;});if(this.player.hp<=0||this.enemy.hp<=0){this.over=true;this.result=this.enemy.hp<=0?'win':'lose';const winner=this.result==='win'?this.player:this.enemy;winner.motionState='victory';}
  }
 };
})(window.SianRobot);
