(function(R){
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  class Fighter{constructor(x,stats,ai=false){this.x=x;this.y=0;this.vx=0;this.vy=0;this.w=54;this.h=86;this.face=ai?-1:1;this.hp=stats.hp;this.maxHp=stats.hp;this.energy=stats.energy;this.maxEnergy=stats.energy;this.stats=stats;this.ai=ai;this.grounded=true;this.guard=false;this.attack=0;this.skill=0;this.hurt=0;this.dash=0}}
  class Engine{
    constructor(build,difficulty="normal"){this.build=build;this.difficulty=difficulty;this.width=900;this.height=470;this.ground=386;this.player=new Fighter(170,R.stats(build));const mul={easy:.86,normal:1,hard:1.15}[difficulty];this.enemy=new Fighter(720,Object.fromEntries(Object.entries(R.stats(build)).map(([k,v])=>[k,Math.round(v*mul)])),true);this.input={left:false,right:false,guard:false};this.projectiles=[];this.particles=[];this.time=0;this.over=false;this.result=null;this.aiClock=0}
    jump(f){if(f.grounded&&!this.over){f.vy=-(9+f.stats.jump*.08);f.grounded=false}}
    attack(f,skill=false){if(this.over||f.attack>0||f.hurt>0)return false;const cost=skill?30:0;if(f.energy<cost)return false;f.energy-=cost;f.attack=skill?34:20;f.skill=skill?34:0;if(skill)this.projectiles.push({x:f.x+f.face*40,y:this.ground-56,vx:f.face*(7+f.stats.speed*.03),owner:f,damage:8+f.stats.power*.45,life:90});return true}
    dash(f,dir=f.face){if(this.over||f.dash>0||f.energy<16)return;f.energy-=16;f.vx=dir*(9+f.stats.speed*.06);f.dash=34}
    hit(target,damage,dir){if(target.hurt>0)return;const reduced=target.guard?damage*.28:Math.max(2,damage-target.stats.defense*.12);target.hp=clamp(target.hp-reduced,0,target.maxHp);target.hurt=target.guard?10:28;target.vx=dir*(target.guard?1.5:4);for(let i=0;i<10;i++)this.particles.push({x:target.x,y:this.ground-target.h/2,vx:(Math.random()-.5)*6,vy:-Math.random()*5,life:28,color:i%2?"#ffd84d":"#72e9ff"})}
    control(f,dt){const dir=(this.input.right?1:0)-(this.input.left?1:0);f.guard=this.input.guard;if(dir&&!f.guard){f.face=dir;f.vx+=dir*(.42+f.stats.speed*.006)*dt}f.vx*=Math.pow(.82,dt);f.x=clamp(f.x+f.vx*dt,35,this.width-35)}
    ai(dt){const a=this.enemy,p=this.player,d=p.x-a.x,dist=Math.abs(d);this.aiClock-=dt;if(this.aiClock<=0){this.aiClock={easy:34,normal:22,hard:14}[this.difficulty];a.guard=p.attack>4&&dist<105&&Math.random()<.55;if(!a.guard){if(dist>145){a.face=Math.sign(d);a.vx+=a.face*(1.8+a.stats.speed*.04)}else if(dist<70&&Math.random()<.35){a.vx-=Math.sign(d)*3}else if(Math.random()<.62)this.attack(a,Math.random()<({easy:.12,normal:.25,hard:.38}[this.difficulty]));if(Math.random()<.12)this.jump(a)}}a.x=clamp(a.x+a.vx*dt,35,this.width-35);a.vx*=Math.pow(.84,dt);if(Math.abs(d)>8)a.face=Math.sign(d)}
    tick(dt=1){if(this.over)return;dt=Math.min(2,dt);this.time+=dt;this.control(this.player,dt);this.ai(dt);for(const f of [this.player,this.enemy]){f.attack=Math.max(0,f.attack-dt);f.skill=Math.max(0,f.skill-dt);f.hurt=Math.max(0,f.hurt-dt);f.dash=Math.max(0,f.dash-dt);f.energy=clamp(f.energy+.08*dt,0,f.maxEnergy);if(!f.grounded){f.vy+=.55*dt;f.y+=f.vy*dt;if(f.y>=0){f.y=0;f.vy=0;f.grounded=true}}}
      const [p,e]=[this.player,this.enemy];if(p.attack>8&&p.attack<14&&Math.abs(p.x-e.x)<92&&p.face===Math.sign(e.x-p.x))this.hit(e,5+p.stats.power*.35,p.face);if(e.attack>8&&e.attack<14&&Math.abs(e.x-p.x)<92&&e.face===Math.sign(p.x-e.x))this.hit(p,5+e.stats.power*.35,e.face);
      this.projectiles.forEach(q=>{q.x+=q.vx*dt;q.life-=dt;const t=q.owner===p?e:p;if(Math.abs(q.x-t.x)<35&&Math.abs(q.y-(this.ground-t.h/2))<55){this.hit(t,q.damage,Math.sign(q.vx));q.life=0}});this.projectiles=this.projectiles.filter(q=>q.life>0&&q.x>0&&q.x<this.width);this.particles.forEach(x=>{x.x+=x.vx;x.y+=x.vy;x.vy+=.25;x.life--});this.particles=this.particles.filter(x=>x.life>0);if(p.hp<=0||e.hp<=0){this.over=true;this.result=e.hp<=0?"win":"lose"} }
  }
  R.BattleEngine=Engine;
})(window.SianRobot);
