/* Sian Pang: original match rules. Pure engine; animations consume immutable snapshots. */
(function(g){
'use strict';
const P=g.SianPang=g.SianPang||{},N=7;
const adjacent=(a,b)=>a>=0&&b>=0&&a<49&&b<49&&Math.abs(a%7-b%7)+Math.abs((a/7|0)-(b/7|0))===1;
function level(n){n=Math.max(1,Math.floor(n)||1);const shape=n<61?0:Math.floor((n-61)/10)%4;const mask=Array.from({length:49},(_,i)=>{const x=i%7,y=i/7|0;return shape===1?!(x===3&&y===3):shape===2?!(x===0||x===6)&&(y===0||y===6)?false:true:shape===3?!(x<2&&y<2||x>4&&y>4):true;});return {n,colors:n<=10?5:n<=30?6:n<=60?7:8,target:n<=10?1250+(n-1)*180:3500+Math.min(n-11,90)*65,seconds:60,moves:n>=61?Math.max(22,34-Math.floor((n-61)/10)):Infinity,mask,ice:n<31?0:Math.min(14,4+Math.floor((n-31)/5)),layers:n<46?1:2,mission:n<11?'score':n<=30?['color','special','combo'][(n-11)%3]:'ice',quota:n<=30?{color:15,special:2,combo:3}:null};}
function runs(board){const out=[];for(let axis=0;axis<2;axis++)for(let line=0;line<N;line++){let group=[];for(let pos=0;pos<=N;pos++){const i=axis?pos*N+line:line*N+pos,c=pos<N?board[i]:null,last=board[group[0]];if(c&&last&&c.type===last.type&&c.special!=='color'){group.push(i);continue;}if(group.length>=3)out.push({cells:group,axis});group=c&&c.special!=='color'?[i]:[];}}return out;}
// Geometry helpers for area/line specials. Pure index math, allocation-free per frame (only called on resolve).
const rowN=y=>[y*7,y*7+1,y*7+2,y*7+3,y*7+4,y*7+5,y*7+6];
const colN=x=>[x,x+7,x+14,x+21,x+28,x+35,x+42];
const rowCells=i=>rowN(i/7|0);
const colCells=i=>colN(i%7);
const areaCells=(i,r)=>{const out=[],cx=i%7,cy=i/7|0;for(let y=Math.max(0,cy-r);y<=Math.min(6,cy+r);y++)for(let x=Math.max(0,cx-r);x<=Math.min(6,cx+r);x++)out.push(y*7+x);return out;};
const bandRows=(i,r)=>{const out=[],cy=i/7|0;for(let y=Math.max(0,cy-r);y<=Math.min(6,cy+r);y++)out.push(...rowN(y));return out;};
const bandCols=(i,r)=>{const out=[],cx=i%7;for(let x=Math.max(0,cx-r);x<=Math.min(6,cx+r);x++)out.push(...colN(x));return out;};
const matchable=c=>!!c&&c.special!=='color';
const SPECIAL_WEIGHT={row:16,column:32,square:48,area:48,color:64,tnt:80};
const isLine=s=>s==='row'||s==='column';
const isSquare=s=>s==='square'||s==='area';
function squares(board){const out=[];for(let y=0;y<6;y++)for(let x=0;x<6;x++){const i=y*7+x,c=board[i];if(!matchable(c))continue;const cells=[i,i+1,i+7,i+8];if(cells.every(k=>matchable(board[k])&&board[k].type===c.type))out.push({cells,type:c.type});}return out;}
function squareAt(board,i){const x=i%7,y=i/7|0;for(const o of [0,-1,-7,-8]){const j=i+o,sx=j%7,sy=j/7|0;if(j<0||sx>5||sy>5||Math.abs(sx-x)>1||Math.abs(sy-y)>1)continue;const c=board[j];if(!matchable(c))continue;if([j,j+1,j+7,j+8].every(k=>matchable(board[k])&&board[k].type===c.type))return true;}return false;}
function groups(board){const list=[...runs(board).map(r=>({cells:new Set(r.cells),runs:[r],squares:[]})),...squares(board).map(s=>({cells:new Set(s.cells),runs:[],squares:[s]}))];for(let i=0;i<list.length;i++)for(let j=i+1;j<list.length;j++)if([...list[j].cells].some(k=>list[i].cells.has(k))){list[j].cells.forEach(k=>list[i].cells.add(k));list[i].runs.push(...list[j].runs);list[i].squares.push(...list[j].squares);list.splice(j,1);j=i;}return list;}
function moves(board){const out=[];for(let a=0;a<49;a++)for(const b of [a+1,a+7]){if(!adjacent(a,b)||!board[a]||!board[b])continue;if(board[a].special==='color'||board[b].special==='color'||board[a].special&&board[b].special){out.push([a,b]);continue;}[board[a],board[b]]=[board[b],board[a]];const ok=runs(board).some(r=>r.cells.includes(a)||r.cells.includes(b))||squareAt(board,a)||squareAt(board,b);[board[a],board[b]]=[board[b],board[a]];if(ok)out.push([a,b]);}return out;}
class Engine{
 constructor(n=1,rng=Math.random){this.config=level(n);this.rng=rng;this.serial=0;this.board=Array(49).fill(null);this.ice=Array(49).fill(0);this.score=0;this.combo=0;this.bestCombo=0;this.matches=0;this.created=0;this.removed=Array(8).fill(0);this.time=60;this.bonus=0;this.usedMoves=0;this.fever=0;this.heat=0;this.idle=0;this.comboLife=0;this.paused=false;this.phase='ready';this.events=[];this.queue=[];this.last=false;this.lastElapsed=0;this.iceRemoved=0;this.feverTick=0;this.fillSafe();const cells=this.board.map((c,i)=>c?i:-1).filter(i=>i>=0).sort(()=>this.rng()-.5);cells.slice(0,this.config.ice).forEach(i=>this.ice[i]=this.config.layers);}
 candy(){return {id:++this.serial,type:Math.floor(this.rng()*this.config.colors),special:null,time:this.config.n>=11&&this.bonus<12&&this.rng()<.015};}
 fillSafe(){for(let i=0;i<49;i++){if(!this.config.mask[i])continue;const forbidden=new Set();if(i%7>=2&&this.board[i-1]&&this.board[i-1]?.type===this.board[i-2]?.type)forbidden.add(this.board[i-1].type);if(i>=14&&this.board[i-7]&&this.board[i-7]?.type===this.board[i-14]?.type)forbidden.add(this.board[i-7].type);if(i%7>=1&&i>=8){const l=this.board[i-1],u=this.board[i-7],d=this.board[i-8];if(l&&u&&d&&l.type===u.type&&u.type===d.type)forbidden.add(l.type);}const c=this.candy();while(forbidden.has(c.type))c.type=(c.type+1)%this.config.colors;this.board[i]=c;}if(!moves(this.board).length)this.guaranteeMove();}
 guaranteeMove(){// An A B A row above a B A B row guarantees a legal central swap, without a prematch.
 for(let y=0;y<6;y++)for(let x=0;x<5;x++){const a=y*7+x,ix=[a,a+1,a+2,a+7,a+8,a+9];if(ix.every(i=>this.board[i])){[0,1,0,1,0,1].forEach((t,k)=>{this.board[ix[k]].type=t;this.board[ix[k]].special=null;});return;}}throw Error('Board requires a playable 3x2 region');}
 snapshot(){return this.board.map(c=>c?{...c}:null);}
 emit(type,extra={}){this.events.push({type,...extra});}
 animate(kind,before,duration=.17,extra={}){this.phase=kind;this.animation={kind,before,after:this.snapshot(),duration,elapsed:0,...extra};}
 swap(a,b){if(this.phase!=='ready'||this.paused||this.time<=0||!adjacent(a,b)||!this.board[a]||!this.board[b])return false;this.idle=0;const before=this.snapshot();[this.board[a],this.board[b]]=[this.board[b],this.board[a]];this.swapPair=[a,b];this.animate('swap',before);return true;}
 // Union of an explicit blast shape, clamped to the board and to playable cells.
 blast(...parts){const set=new Set();for(const part of parts)for(const i of part)if(i>=0&&i<49&&this.config.mask[i]&&this.board[i])set.add(i);return [...set];}
 combine(a,b,sa,sb){
  if(isLine(sa)&&isLine(sb))return this.blast(rowCells(a),colCells(a),rowCells(b),colCells(b));
  if(sa==='tnt'&&sb==='tnt')return this.blast(areaCells(a,3),areaCells(b,3));
  if(sa==='tnt'&&isLine(sb)||sb==='tnt'&&isLine(sa)){const t=sa==='tnt'?a:b,l=sa==='tnt'?sb:sa;return this.blast(areaCells(t,2),l==='row'?bandRows(t,1):bandCols(t,1));}
  if(isSquare(sa)&&isLine(sb)||isSquare(sb)&&isLine(sa)){const q=isSquare(sa)?a:b,l=isSquare(sa)?sb:sa;return this.blast(areaCells(q,1),l==='row'?bandRows(q,1):bandCols(q,1));}
  if(isSquare(sa)&&isSquare(sb))return this.blast(areaCells(a,2),areaCells(b,2));
  return this.blast(areaCells(a,2),areaCells(b,2));
 }
 infect(colorAt,otherAt,kind,type){const hits=[];this.board.forEach((c,i)=>{if(!c||!this.config.mask[i])return;if(i===colorAt||i===otherAt){c.special=kind==='row'?(i%2?'column':'row'):kind;hits.push(i);return;}if(c.type===type&&c.special!=='color'){c.special=kind==='row'||kind==='column'?(i%2?'column':'row'):kind;hits.push(i);}});return hits;}
 resolveSwap(){const [a,b]=this.swapPair,A=this.board[a],B=this.board[b];let forced=[];if(A.special==='color'||B.special==='color'){const both=A.special==='color'&&B.special==='color',ci=A.special==='color'?a:b,oi=A.special==='color'?b:a,other=this.board[oi];if(both)forced=this.board.flatMap((c,i)=>c?[i]:[]);else if(other.special)forced=this.infect(ci,oi,other.special,other.type);else forced=this.board.flatMap((c,i)=>c&&(c.type===other.type||i===a||i===b)?[i]:[]);}else if(A.special&&B.special)forced=this.combine(a,b,A.special,B.special);const matches=groups(this.board);if(!forced.length&&!matches.length){const before=this.snapshot();[this.board[a],this.board[b]]=[this.board[b],this.board[a]];this.animate('return',before,.17);this.emit('invalid');return;}this.usedMoves++;this.resolve(matches,forced);}
 resolve(matches,forced=[]){const before=this.snapshot(),hit=new Set(forced),keep=new Map();for(const m of matches){m.cells.forEach(i=>hit.add(i));const longest=m.runs.length?Math.max(...m.runs.map(r=>r.cells.length)):0;const cross=new Set(m.runs.map(r=>r.axis)).size>1;let special=longest>=5?'color':cross?'tnt':m.squares.length?'square':longest===4?(m.runs[0].axis?'row':'column'):null;if(!special&&this.fever>0&&++this.feverTick%3===0)special='square';if(special&&!this.last){const at=(this.swapPair||[]).find(i=>m.cells.has(i)&&!this.board[i]?.special)??[...m.cells].find(i=>!this.board[i]?.special);if(at!==undefined){keep.set(at,special);this.created++;}}}
 const visited=new Set();const pending=[...hit];while(pending.length){const i=pending.pop();if(visited.has(i)||!this.board[i])continue;visited.add(i);const c=this.board[i];let extra=[];if(c.special==='row')extra=rowCells(i);else if(c.special==='column')extra=colCells(i);else if(isSquare(c.special))extra=areaCells(i,1);else if(c.special==='tnt')extra=areaCells(i,2);else if(c.special==='color')extra=this.board.flatMap((v,k)=>v&&v.type===c.type?[k]:[]);for(const j of extra)if(!hit.has(j)){hit.add(j);pending.push(j);}}
 if(!this.last){this.combo=this.comboLife>0?this.combo+1:1;this.comboLife=this.fever>0?7:4.5;this.bestCombo=Math.max(this.bestCombo,this.combo);this.heat+=18+Math.min(this.combo,8)*2;if(this.heat>=100&&this.fever<=0){this.heat=0;this.fever=7;this.emit('fever');}}
 let count=0;for(const i of hit){const c=this.board[i];if(!c)continue;if(this.ice[i]>0){this.ice[i]--;if(!this.ice[i])this.iceRemoved++;}if(keep.has(i)){c.special=keep.get(i);c.time=false;continue;}if(this.ice[i]>0)continue;this.removed[c.type]++;count++;if(c.time&&!this.last&&this.bonus<12){const add=Math.min(3,12-this.bonus);this.bonus+=add;this.time+=add;this.emit('time',{seconds:add});}this.board[i]=null;}
 this.matches+=matches.length||1;const points=Math.round((250+Math.max(0,this.combo-1)*200)*Math.max(1,count/3)*(this.fever>0?1.5:1));this.score+=points;this.emit('pop',{cells:[...hit],points,combo:this.combo,special:keep.size?(()=>{const v=[...keep.values()];return v.includes('color')?7:v.includes('tnt')?6:v.some(isSquare)?5:4;})():3});this.animate('pop',before,.23,{cells:[...hit]});this.swapPair=null;
 }
 fall(){const before=this.snapshot();for(let x=0;x<7;x++){const slots=Array.from({length:7},(_,y)=>y*7+x).filter(i=>this.config.mask[i]);const alive=slots.map(i=>this.board[i]).filter(Boolean);for(let j=slots.length-1;j>=0;j--)this.board[slots[j]]=alive.pop()||this.candy();}this.animate('fall',before,.24);}
 shuffle(){const before=this.snapshot(),slots=this.board.map((c,i)=>c?i:-1).filter(i=>i>=0),candies=slots.map(i=>this.board[i]);let ok=false;for(let tries=0;tries<80;tries++){for(let i=candies.length-1;i>0;i--){const j=Math.floor(this.rng()*(i+1));[candies[i],candies[j]]=[candies[j],candies[i]];}slots.forEach((i,k)=>this.board[i]=candies[k]);if(!runs(this.board).length&&!squares(this.board).length&&moves(this.board).length){ok=true;break;}}if(!ok)this.fillSafe();this.emit('shuffle');this.animate('shuffle',before,.45);}
 beginLast(){this.last=true;this.lastElapsed=0;this.lastQueue=this.board.flatMap((c,i)=>c?.special?[i]:[]);this.emit('last');this.phase='last';this.lastWait=.2;}
 finish(){this.phase='result';this.animation=null;this.emit('result',{result:this.result()});}
 tick(dt){if(this.paused||this.phase==='result')return;dt=Math.max(0,Math.min(dt,2));this.idle+=dt;this.comboLife=Math.max(0,this.comboLife-dt);this.fever=Math.max(0,this.fever-dt);if(!this.last)this.time=Math.max(0,this.time-dt);else{this.lastElapsed+=dt;if(this.lastElapsed>=3.6){const remaining=this.board.flatMap((c,i)=>c?.special?[i]:[]);if(remaining.length)this.resolve([],remaining);this.finish();return;}}
 if(this.animation){this.animation.elapsed+=dt;if(this.animation.elapsed<this.animation.duration)return;const kind=this.animation.kind;this.animation=null;if(kind==='swap'){this.resolveSwap();return;}if(kind==='pop'){this.fall();return;}if(kind==='fall'){if(this.last){this.phase='last';this.lastWait=.08;return;}const m=groups(this.board);if(m.length){this.resolve(m);return;}}this.phase='ready';}
 if(this.last){this.lastWait-=dt;if(this.lastWait<=0){const i=this.board.findIndex(c=>c?.special);if(i>=0)this.resolve([],[i]);else if(this.lastElapsed>=2)this.finish();}return;}
 if(this.phase==='ready'){if(this.time<=0||this.usedMoves>=this.config.moves){this.beginLast();return;}if(!this.playable().length)this.shuffle();}}
 result(){const c=this.config,mission=c.mission==='score'||c.mission==='color'&&this.removed[c.n%c.colors]>=15||c.mission==='special'&&this.created>=2||c.mission==='combo'&&this.bestCombo>=3||c.mission==='ice'&&this.iceRemoved>=c.ice;const stars=mission&&this.score>=c.target?(this.score>=c.target*1.7?3:this.score>=c.target*1.3?2:1):0;return {level:c.n,score:this.score,stars,combo:this.bestCombo,matches:this.matches};}
 // Legal-move search is O(cells x swaps); cache it until the board's layout or special pieces change.
 playable(){let h=0,k=0;for(let i=0;i<49;i++){const c=this.board[i],v=c?c.type+1+(c.special?SPECIAL_WEIGHT[c.special]||96:0):0;h=(h*31+v)|0;k=(k*17+v*(i+1))|0;}if(!this._mv||h!==this._mh||k!==this._mk){this._mh=h;this._mk=k;this._mv=moves(this.board);}return this._mv;}
 hint(){return this.playable()[0]||[];}
}
function record(previous,r){const s={unlocked:1,levels:{},bestCombo:0,totalMatches:0,...previous};s.levels={...s.levels};const old=s.levels[r.level]||{score:0,stars:0};s.levels[r.level]={score:Math.max(old.score,r.score),stars:Math.max(old.stars,r.stars)};s.unlocked=Math.max(s.unlocked,r.stars?r.level+1:1);s.bestCombo=Math.max(s.bestCombo,r.combo);s.totalMatches+=r.matches;return s;}
Object.assign(P,{Engine,level,runs,squares,squareAt,groups,moves,adjacent,record,rowCells,colCells,areaCells});
if(typeof module!=='undefined')module.exports=P;
})(typeof window!=='undefined'?window:globalThis);
