(function(g){
'use strict';
const P=g.SianPang,names=['하트','오렌지','별','클로버','구슬','포도','꽃','민트'];
function play(){
 const oldOverflow=document.body.style.overflow;document.body.style.overflow='hidden';game.classList.add('pangModal');
 gameBody.innerHTML='<section class="pangGame"><div class="pangHead"><button data-back>← 게임월드</button><strong>시안팡 <small>STAR CANDY MATCH</small></strong></div><div class="pangHud"><b data-level></b><span>SCORE <strong data-score>0</strong></span><span>BEST <b data-best>0</b></span></div><div class="pangTimer"><b data-time>60</b><progress max="60" value="60" aria-label="남은 시간"></progress></div><div class="pangWrap"><canvas width="700" height="700" aria-label="캔디 보드: 인접한 두 캔디를 누르거나 끌어 교환하세요" tabindex="0"></canvas><div class="pangOverlay"></div></div><div class="pangFever"><b data-combo>COMBO 0</b><progress max="100" value="0" aria-label="피버"></progress><span data-fever>FEVER</span></div><p class="pangMission"></p><div class="pangFooter"><button data-pause>Ⅱ 잠깐 멈춤</button><button data-levels>레벨 선택</button><span>무제한 PLAY</span></div><p class="pangMessage" role="status">캔디를 밀어서 같은 모양 3개를 이어요!</p></section>';
 const root=gameBody.querySelector('.pangGame'),q=s=>root.querySelector(s),canvas=q('canvas'),ctx=canvas.getContext('2d'),overlay=q('.pangOverlay');let engine,started=false,stopped=false,last=0,selected=-1,drag=null,snap=null,particles=[],recorded=false,menu=false,tutorial=true;
 // Performance state: DOM refs are looked up once and written only on change; canvas layers are pre-rendered.
 const ui={score:q('[data-score]'),time:q('[data-time]'),timerBar:q('.pangTimer progress'),combo:q('[data-combo]'),feverBar:q('.pangFever progress'),fever:q('[data-fever]'),mission:q('.pangMission'),message:q('.pangMessage')},shown={},pool=[],sprites=[],PC=['#ffd45d','#ff92d0','#8cefe0'],SZ=114;
 let rect=null,ro=null,dirty=true,wasBusy=true,lastDraw=0,bg=null,feverOn=false,scoreN=-1,scoreText='0';
 const put=(k,v,prop='textContent')=>{if(shown[k]!==v){shown[k]=v;ui[k][prop]=v;}};
 const sheet=new Image();sheet.src='assets/pang/candies.jpeg';let loaded=false;sheet.onload=()=>{bake();loaded=true;dirty=true;const b=q('[data-play]');if(b){b.disabled=false;b.textContent='PLAY ▶';}};sheet.onerror=()=>{q('.pangMessage').textContent='캔디 그림을 불러오지 못했어요. 다시 열어 주세요.';};
 const stored=()=>state.pang||{unlocked:1,levels:{},bestCombo:0,totalMatches:0};
 function begin(n){engine=new P.Engine(n);bakeBg();dirty=true;selected=-1;drag=null;recorded=false;menu=false;started=false;tutorial=!stored().tutorial;overlay.hidden=false;overlay.innerHTML='<div class="pangStart"><img src="assets/game-cards/sian-pang.webp" alt="시안이와 캔디 모험"><h2>LEVEL '+n+'</h2><p>같은 캔디를 3개 이어요!</p><button data-play>PLAY ▶</button><small>언제든 다시 할 수 있어요</small></div>';q('[data-play]').disabled=!loaded;if(!loaded)q('[data-play]').textContent='캔디 준비 중…';q('[data-play]').onclick=()=>{if(!loaded)return;started=true;overlay.hidden=true;engine.paused=false;SianAudio?.pause(false);SianAudio?.music('pang');SianAudio?.unlock();};q('[data-level]').textContent='LEVEL '+n;q('[data-best]').textContent=(stored().levels[n]?.score||0).toLocaleString();hud();}
 function mission(){const c=engine.config;return '목표 '+(c.targetText||(c.targetText=c.target.toLocaleString()))+'점'+(c.mission==='color'?' · '+names[c.n%c.colors]+' '+engine.removed[c.n%c.colors]+'/15':c.mission==='special'?' · 특수 캔디 '+engine.created+'/2':c.mission==='combo'?' · 콤보 '+engine.bestCombo+'/3':c.mission==='ice'?' · 얼음 '+engine.iceRemoved+'/'+c.ice:'')+(Number.isFinite(c.moves)?' · 이동 '+Math.max(0,c.moves-engine.usedMoves):'');}
 function hud(){if(engine.score!==scoreN){scoreN=engine.score;scoreText=scoreN.toLocaleString();}put('score',scoreText);put('time',Math.ceil(engine.time)+'초');put('timerBar',Math.round(engine.time*10)/10,'value');put('combo',engine.last?'LAST PANG!':'COMBO '+engine.combo);put('feverBar',Math.round((engine.fever>0?engine.fever/7*100:engine.heat)*2)/2,'value');put('fever',engine.fever>0?'별빛 피버!':'FEVER');const f=engine.fever>0;if(f!==feverOn){feverOn=f;root.classList.toggle('isFever',f);}put('mission',mission());const d=canvas.dataset,sc=String(engine.score),dr=drag?String(drag.at):'';if(d.phase!==engine.phase)d.phase=engine.phase;if(d.score!==sc)d.score=sc;if(d.drag!==dr)d.drag=dr;}
 function result(r,persist=true){if(persist&&!recorded){recorded=true;const previous=stored(),oldStars=previous.levels[r.level]?.stars||0;state.pang=P.record(previous,r);state.pang.tutorial=true;state.stars+=Math.max(0,r.stars-oldStars);save();SianAudio?.effect(r.stars?'clear':'fail');}SianAudio?.stopMusic(.25);overlay.hidden=false;overlay.innerHTML='<div class="pangResult"><small>LEVEL '+r.level+'</small><h2>'+(r.stars?'LEVEL CLEAR!':'조금만 더 하면 돼!')+'</h2><div class="pangStars">'+('★'.repeat(r.stars)+'☆'.repeat(3-r.stars))+'</div><strong>'+r.score.toLocaleString()+'점</strong><p>최고 콤보 '+r.combo+'</p>'+(r.stars?'<button data-next>다음 Level →</button>':'')+'<button data-retry>다시 하기 ↻</button><button data-map>레벨 선택</button></div>';q('[data-next]')?.addEventListener('click',()=>begin(r.level+1));q('[data-retry]').onclick=()=>begin(r.level);q('[data-map]').onclick=levelMenu;}
 function levelMenu(){engine.paused=true;menu=true;SianAudio?.pause(true);overlay.hidden=false;const max=stored().unlocked||1;overlay.innerHTML='<div class="pangLevelList"><h2>캔디 모험 지도</h2><p>100단계 너머로 계속! · 무제한 도전</p><div>'+Array.from({length:Math.max(100,max+5)},(_,i)=>'<button data-n="'+(i+1)+'" '+(i+1>max?'disabled':'')+'>'+(i+1)+'<small>'+('★'.repeat(stored().levels[i+1]?.stars||0))+'</small></button>').join('')+'</div><button data-resume>돌아가기</button></div>';overlay.querySelectorAll('[data-n]').forEach(b=>b.onclick=()=>begin(+b.dataset.n));q('[data-resume]').onclick=()=>{menu=false;if(engine.phase==='result') {result(engine.result(),false);}else if(!started)begin(engine.config.n);else{engine.paused=false;overlay.hidden=true;SianAudio?.pause(false);}};}
 function pause(){if(!started||engine.phase==='result'||menu)return;engine.paused=!engine.paused;drag=null;SianAudio?.pause(engine.paused);overlay.hidden=!engine.paused;if(engine.paused){overlay.innerHTML='<div class="pangResult"><h2>잠깐 쉬어요</h2><button data-resume>계속하기 ▶</button></div>';q('[data-resume]').onclick=pause;}q('[data-pause]').textContent=engine.paused?'▶ 계속하기':'Ⅱ 잠깐 멈춤';}
 function cell(e){const r=rect||(rect=canvas.getBoundingClientRect()),x=(e.clientX-r.left)/r.width*7,y=(e.clientY-r.top)/r.height*7;return {x:x*100,y:y*100,at:x<0||y<0||x>=7||y>=7?-1:(y|0)*7+(x|0)};}
 function down(e){if(!started||engine.paused||engine.phase!=='ready'||drag||e.button>0)return;rect=canvas.getBoundingClientRect();const p=cell(e);if(p.at<0||!engine.board[p.at])return;e.preventDefault();canvas.setPointerCapture(e.pointerId);drag={id:e.pointerId,at:p.at,x:p.x,y:p.y,dx:0,dy:0,to:-1};}
 function move(e){if(!drag||e.pointerId!==drag.id)return;e.preventDefault();const p=cell(e),dx=p.x-drag.x,dy=p.y-drag.y,h=Math.abs(dx)>=Math.abs(dy),offset=h?(dx>0?1:-1):(dy>0?7:-7),to=drag.at+offset;drag.to=P.adjacent(drag.at,to)&&engine.board[to]?to:-1;drag.dx=h?Math.max(-85,Math.min(85,dx)):0;drag.dy=h?0:Math.max(-85,Math.min(85,dy));}
 function end(e,cancel=false){if(!drag||drag.id!==e.pointerId)return;e.preventDefault();const d=drag;drag=null;canvas.releasePointerCapture?.(e.pointerId);const distance=Math.hypot(d.dx,d.dy);if(!cancel&&distance>=24&&d.to>=0){selected=-1;engine.swap(d.at,d.to);if(engine.animation)engine.animation.drag=d;tutorial=false;}else if(!cancel&&distance<9){if(P.adjacent(selected,d.at)){engine.swap(selected,d.at);selected=-1;tutorial=false;}else selected=selected===d.at?-1:d.at;}else snap={...d,life:.15};}
 if(typeof ResizeObserver==='function'){ro=new ResizeObserver(()=>{rect=null;});ro.observe(canvas);}canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointermove',move);const up=e=>end(e),cancel=e=>end(e,true);canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',cancel);
 function bake(){if(typeof document.createElement!=='function')return;sprites.length=0;const sw=sheet.width/5,sh=sheet.height/2;for(let t=0;t<10;t++){const c=document.createElement('canvas');c.width=c.height=SZ;const x=c.getContext('2d');if(!x)return;x.translate(SZ/2,SZ/2);x.imageSmoothingQuality='high';x.shadowColor='#1b1c6a55';x.shadowBlur=7;x.shadowOffsetY=5;x.beginPath();x.roundRect(-43,-43,86,86,20);x.fillStyle='#fff';x.fill();x.shadowColor='transparent';x.shadowBlur=0;x.shadowOffsetY=0;x.clip();x.drawImage(sheet,t%5*sw,(t/5|0)*sh,sw,sh,-43,-43,86,86);sprites[t]=c;}}
 function mark(c){if(c.special==='row'||c.special==='column'){ctx.strokeStyle='#fff';ctx.lineWidth=6;ctx.beginPath();if(c.special==='row'){ctx.moveTo(-35,0);ctx.lineTo(35,0);}else{ctx.moveTo(0,-35);ctx.lineTo(0,35);}ctx.stroke();ctx.strokeStyle='#6951d9';ctx.lineWidth=2;ctx.stroke();}if(c.time){ctx.fillStyle='#163767';ctx.font='bold 21px sans-serif';ctx.fillText('+3',6,32);}}
 function candy(c,x,y,scale=1,alpha=1){if(!c||!loaded)return;const t=c.special==='color'?9:c.special==='area'?8:c.type,spr=sprites[t];ctx.save();ctx.globalAlpha=alpha;ctx.translate(x,y);ctx.scale(scale,scale);if(spr)ctx.drawImage(spr,-SZ/2,-SZ/2);else{ctx.shadowColor='#1b1c6a55';ctx.shadowBlur=7;ctx.shadowOffsetY=5;const sw=sheet.width/5,sh=sheet.height/2;ctx.beginPath();ctx.roundRect(-43,-43,86,86,20);ctx.fillStyle='#fff';ctx.fill();ctx.clip();ctx.drawImage(sheet,t%5*sw,(t/5|0)*sh,sw,sh,-43,-43,86,86);ctx.shadowBlur=0;}mark(c);ctx.restore();}
 function paintBg(x){const grad=x.createLinearGradient(0,0,700,700);grad.addColorStop(0,'#28386c');grad.addColorStop(1,'#59417e');x.fillStyle=grad;x.fillRect(0,0,700,700);for(let i=0;i<49;i++){if(!engine.config.mask[i])continue;x.fillStyle=(i+(i/7|0))%2?'#ffffff19':'#ffffff0d';x.beginPath();x.roundRect(i%7*100+4,(i/7|0)*100+4,92,92,18);x.fill();}}
 function bakeBg(){bg=null;if(typeof document.createElement!=='function')return;const c=document.createElement('canvas');c.width=c.height=700;const x=c.getContext('2d');if(!x)return;paintBg(x);bg=c;}
 function draw(t,dt){if(bg)ctx.drawImage(bg,0,0);else{ctx.clearRect(0,0,700,700);paintBg(ctx);}
 const a=engine.animation,p=a?Math.min(1,a.elapsed/a.duration):1,ease=1-Math.pow(1-p,3),before=new Map((a?.before||[]).flatMap((c,i)=>c?[[c.id,i]]:[]));const drawBoard=a?.kind==='pop'?a.before:engine.board;
 for(let i=0;i<49;i++){const c=drawBoard[i];if(!c)continue;let x=i%7*100+50,y=(i/7|0)*100+50,sc=1,al=1;const from=before.get(c.id);if(a&&a.kind!=='pop'){if(from!==undefined){const d=a.drag,dx=d?(from===d.at?d.dx:from===d.to?-d.dx*.5:0):0,dy=d?(from===d.at?d.dy:from===d.to?-d.dy*.5:0):0;x=(from%7*100+50+dx)*(1-ease)+x*ease;y=((from/7|0)*100+50+dy)*(1-ease)+y*ease;}else if(a.kind==='fall')y-=180*(1-ease);}if(a?.kind==='pop'&&a.cells.includes(i)){sc=1+Math.sin(p*Math.PI)*.18;al=1-p;}
 const d=drag||snap;if(d){const f=drag?1:snap.life/.15;if(i===d.at){x+=d.dx*f;y+=d.dy*f;sc=1.06;}else if(i===d.to){x-=d.dx*f*.5;y-=d.dy*f*.5;}}if(i===selected){ctx.strokeStyle='#ffdf70';ctx.lineWidth=6;ctx.strokeRect(x-45,y-45,90,90);}candy(c,x,y,sc,al);if(engine.ice[i]){ctx.fillStyle=engine.ice[i]>1?'#9edfff88':'#9edfff44';ctx.fillRect(i%7*100+7,(i/7|0)*100+7,86,86);ctx.strokeStyle='#d9f9ff';ctx.lineWidth=3;ctx.strokeRect(i%7*100+10,(i/7|0)*100+10,80,80);}}
 if(snap){snap.life-=dt;if(snap.life<=0)snap=null;}if(started&&!engine.paused&&engine.phase==='ready'&&(engine.idle>3||tutorial)){const [a,b]=engine.hint();if(a!==undefined){ctx.strokeStyle='#ffe786';ctx.lineWidth=5+Math.sin(t/160)*2;for(const i of [a,b]){ctx.beginPath();ctx.roundRect(i%7*100+6,(i/7|0)*100+6,88,88,17);ctx.stroke();}if(tutorial){const f=(Math.sin(t/500)+1)/2,x=(a%7+(b%7-a%7)*f)*100+50,y=((a/7|0)+((b/7|0)-(a/7|0))*f)*100+60;ctx.fillStyle='#fff';ctx.strokeStyle='#c78b64';ctx.lineWidth=3;ctx.beginPath();ctx.roundRect(x-8,y,18,40,9);ctx.fill();ctx.stroke();ctx.beginPath();ctx.roundRect(x-17,y+25,42,34,15);ctx.fill();ctx.stroke();}}}
 let live=0;for(let k=0;k<particles.length;k++){const p=particles[k];if(p.life<=0){pool.push(p);continue;}p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=180*dt;ctx.globalAlpha=Math.max(0,p.life/.6);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,7,7);particles[live++]=p;}particles.length=live;ctx.globalAlpha=1;}
 function frame(t){if(stopped)return;const dt=Math.min(2,last?(t-last)/1000:0);last=t;if(started&&!document.hidden)engine.tick(dt);if(engine.events.length)for(const ev of engine.events.splice(0)){if(ev.type==='pop'){SianAudio?.effect('pang'+ev.special,Math.min(1.5,1+ev.combo*.035));ui.message.textContent='+'+ev.points+' · COMBO '+ev.combo;for(const i of ev.cells)for(let k=0;k<3&&particles.length<140;k++){const p=pool.pop()||{};p.x=i%7*100+50;p.y=(i/7|0)*100+50;p.vx=(Math.random()-.5)*160;p.vy=-Math.random()*180;p.life=.6;p.color=PC[k];particles.push(p);}}else if(ev.type==='result')result(ev.result);else if(ev.type==='fever'){SianAudio?.effect('pangFever');}else if(ev.type==='last')SianAudio?.effect('pangLast');else if(ev.type==='shuffle')q('.pangMessage').textContent='섞어볼게!';else if(ev.type==='time')q('.pangMessage').textContent='+3초!';}SianAudio?.intensity(engine.fever>0?1:0);hud();const hintOn=started&&!engine.paused&&engine.phase==='ready'&&(engine.idle>3||tutorial),busy=dirty||!!engine.animation||!!drag||!!snap||particles.length>0||hintOn||selected>=0||(engine.phase!=='ready'&&engine.phase!=='result')||t-lastDraw>400;if(busy||wasBusy){draw(t,dt);lastDraw=t;dirty=false;}wasBusy=busy;Session.frame(frame);}
 q('[data-back]').onclick=openGameWorld;q('[data-pause]').onclick=pause;q('[data-levels]').onclick=levelMenu;const visibility=()=>{if(document.hidden&&started&&!engine.paused)pause();};document.addEventListener('visibilitychange',visibility);Session.cleanup(()=>{stopped=true;document.body.style.overflow=oldOverflow;game.classList.remove('pangModal');document.removeEventListener('visibilitychange',visibility);canvas.removeEventListener('pointerdown',down);canvas.removeEventListener('pointermove',move);canvas.removeEventListener('pointerup',up);canvas.removeEventListener('pointercancel',cancel);sheet.onload=null;ro?.disconnect();});
 begin(stored().unlocked);SianAudio?.start('pang');Session.frame(frame);
}
g.playPang=play;
})(window);
