(function(global){
 const SUBJECTS=['연산','수학','사고력 수학','한글','영어','과학','코딩','한자'];
 const CHAPTERS=['입문','기초','기초 응용','개념 확장','응용','복합 개념','문제 해결','심화','고급 응용','종합 Challenge'];
 const clone=x=>JSON.parse(JSON.stringify(x));
 function data(){state.records=state.records||{};const d=state.records.learningBank||(state.records.learningBank={version:1,recentQuestionIds:{},recentTemplates:{},recentAnswers:{},answerPositions:{},performance:{}});for(const s of SUBJECTS){d.recentQuestionIds[s]||=[];d.recentTemplates[s]||=[];d.recentAnswers[s]||=[];d.answerPositions[s]||={bag:[],last:-1,run:0,counts:[0,0,0,0]};d.performance[s]||={correctStreak:0,wrongStreak:0,attempts:0,correct:0};}return d;}
 function persist(){try{if(typeof localStorage!=='undefined')localStorage.setItem('sianhi-v2',JSON.stringify(state));}catch{}}
 function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
 function position(subject){const p=data().answerPositions[subject];if(!p.bag.length){p.bag=shuffle([0,1,2,3]);if(p.bag[0]===p.last&&p.bag.length>1)[p.bag[0],p.bag[1]]=[p.bag[1],p.bag[0]];}let n=p.bag.shift();if(n===p.last&&p.run>=2){const i=p.bag.findIndex(x=>x!==p.last);if(i>=0)[n,p.bag[i]]=[p.bag[i],n];}p.run=n===p.last?p.run+1:1;p.last=n;p.counts[n]++;return n;}
 function fingerprint(q){return [q.templateId,q.q,q.ans].join('|').replace(/\s+/g,' ');}
 function finalize(subject,raw){const answer=String(raw.ans),seen=new Set([answer]),wrong=[];for(const v of raw.opts||[]){const x=String(v);if(!seen.has(x)){seen.add(x);wrong.push(x);}if(wrong.length===3)break;}for(let n=1;wrong.length<3;n++){const x=/^-?\d+(?:\.\d+)?$/.test(answer)?String(Math.max(0,Number(answer)+(n%2?n:-n))):'다른 답 '+n;if(!seen.has(x)){seen.add(x);wrong.push(x);}}const at=position(subject),opts=wrong.slice(0,3);opts.splice(at,0,answer);const q={id:fingerprint(raw),learningObjective:raw.learningObjective||'',difficulty:raw.difficulty||1,questionType:raw.questionType||'multiple-choice',conceptTags:raw.conceptTags||[],questionPool:raw.questionPool||[raw.templateId],generator:raw.generator||raw.templateId,explanation:raw.explanation||('정답은 '+answer+'입니다.'),visual:raw.visual||'',...raw,category:raw.category||raw.templateId,ans:answer,opts,answerPosition:at};q.question=q.q;q.choices=q.opts;q.correctAnswer=q.ans;return q;}
 function BCheck(q){return !window.LearningBank.validateQuestion||window.LearningBank.validateQuestion(q).valid;}
 function generate(subject,stage,factory){const d=data(),recent=d.recentQuestionIds[subject],templates=d.recentTemplates[subject];let raw,id;for(let tries=0;tries<200;tries++){raw=factory(tries);raw.category||=raw.templateId;if(subject==='한글'&&BCheck(raw)===false)continue;id=fingerprint(raw);const duplicate=recent.includes(id),sameTemplate=templates.at(-1)===raw.templateId;if(!duplicate&&(!sameTemplate||tries>12))break;}if(subject==='한글'&&BCheck(raw)===false)raw=window.LearningBank.koreanFallback(stage);if(subject==='한글'&&window.LearningBank.koreanFallback&&recent.includes(fingerprint(raw))){for(let n=0;n<200;n++){const alternate=window.LearningBank.koreanFallback(stage,n);if(!recent.includes(fingerprint(alternate))){raw=alternate;break;}}}const q=finalize(subject,raw);recent.push(q.id);templates.push(q.templateId);d.recentAnswers[subject].push(q.ans);if(recent.length>20)recent.shift();if(templates.length>20)templates.shift();if(d.recentAnswers[subject].length>20)d.recentAnswers[subject].shift();persist();return q;}
 function record(subject,correct){const p=data().performance[subject];p.attempts++;if(correct){p.correct++;p.correctStreak++;p.wrongStreak=0;}else{p.wrongStreak++;p.correctStreak=0;}persist();}
 function adaptive(subject){const p=data().performance[subject];return p.correctStreak>=3?1:p.wrongStreak>=2?-1:0;}
 function makeCurriculum(subject,zones){return Array.from({length:100},(_,i)=>{const chapter=Math.floor(i/10),step=i%10,z=zones[chapter];return {stage:i+1,chapter:chapter+1,chapterName:CHAPTERS[chapter],title:z.title,learningObjective:z.objective,difficulty:chapter+1,questionType:z.types[step%z.types.length],conceptTags:z.tags,questionPool:z.templates,generator:z.generator,explanation:z.explanation,mode:['탐색','찾기','연결','비교','선택','퍼즐','응용','이야기','도전','챌린지'][step],story:['새 개념을 천천히 만나 봐요.','배운 내용을 찾아 연결해요.','비슷한 것과 다른 것을 살펴봐요.','여러 방법으로 답을 생각해요.','생활 속 문제에 적용해요.','힌트를 사용해 해결해요.','두 개념을 함께 사용해요.','이야기 속 단서를 찾아요.','스스로 설명하며 풀어요.','이번 장의 실력을 확인해요.'][step]};});}
 global.LearningBank={SUBJECTS,CHAPTERS,clone,data,shuffle,generate,record,adaptive,makeCurriculum};
})(window);
