(function(global){
 const S=global.LearningSpace,A=global.DiscoveryArt,M=global.DiscoveryModel,V=global.LearningSpeech;
 const ko=text=>({text,lang:'ko-KR'}),en=text=>({text,lang:'en-US'});
 function play(subject,stage){
  const q=M.make(subject,stage);if(!M.validate(q))throw new Error('Invalid discovery mission '+q.id);
  const root=S.shell(subject,stage,q.title,q.prompt,q.theme),area=root.querySelector('.spaceGameplay'),feedback=root.querySelector('.spaceFeedback'),audio=root.querySelector('.learningAudioStatus');root.classList.add('discoverySpace');root.dataset.mode=q.mode;
  let solved=false;const read=()=>V.speak(q.parts,{button:root.querySelector('.spaceVoice'),status:audio});
  V.bind(root.querySelector('.spaceVoice'),q.parts,audio);
  const actionHint=document.createElement('button');actionHint.className='gestureLesson';actionHint.setAttribute('aria-label','조작 방법 다시 보기');actionHint.innerHTML='<svg viewBox="0 0 110 36" aria-hidden="true"><circle cx="18" cy="17" r="9" fill="#b5dce2"/><path d="M32 17H79l-6-5m6 5-6 5" stroke="#83a7b6" stroke-width="2" fill="none"/><rect x="87" y="7" width="17" height="20" rx="5" fill="#ebd3aa"/><path class="demoFinger" d="M17 24V11q0-4 4-4t4 4v9l7-2q5 0 4 5l-3 9H20Z" fill="#f2d4ba" stroke="#ba9c87"/></svg><span>만져 봐요</span>';
  const dragModes=['sameWord','pictureMatch','buildWord','match','position','habitat','growth','float','magnet'];actionHint.dataset.gesture=dragModes.includes(q.mode)?'drag':'tap';actionHint.onclick=()=>{actionHint.classList.remove('showGesture');void actionHint.offsetWidth;actionHint.classList.add('showGesture');V.speak([ko(dragModes.includes(q.mode)?'물건을 잡고 옮겨 봐. 물건을 누른 다음 자리를 눌러도 돼.':'그림을 눌러 봐. 스피커를 누르면 소리를 들을 수 있어.')],{status:audio});};root.querySelector('.spaceHeading').insertBefore(actionHint,audio);actionHint.classList.add('showGesture');
  const near=document.createElement('button');near.className='nearSpeaker';near.setAttribute('aria-label','문제 다시 듣기');near.innerHTML=V.icon;near.onclick=()=>V.speak(q.parts,{button:near,status:audio});root.querySelector('.spaceStage').prepend(near);
  const finish=()=>{if(solved)return;solved=true;S.complete(root,subject,stage,q.explanation);V.speak(subject==='영어'?[ko('맞았어!'),en(['listen','soundChoice','phonics'].includes(q.mode)?q.word:q.mode==='color'?q.correct+' balloon.':q.mode==='position'?'The bear is '+q.relation+' the box.':q.mode==='action'?q.correct:['sentence','dialogue'].includes(q.mode)?'The '+q.animal+' is '+q.relation+' the box.':q.mode==='count'?q.parts.find(p=>p.lang==='en-US').text:'Well done!'),ko(['listen','soundChoice','phonics'].includes(q.mode)?A.labels[q.word]:'잘했어!')]:[ko('맞았어! '+q.explanation)],{status:audio});};
  const wrong=el=>{if(solved)return;el?.classList.add('spaceShake');Session.timeout(()=>el?.classList.remove('spaceShake'),360);feedback.textContent='다시 한번 볼까?';V.speak(subject==='영어'?[ko('다시 한번 볼까?'),...q.parts.filter(p=>p.lang==='en-US')]:[ko('다시 한번 볼까?')],{status:audio});};
  const piece=(key,content)=>`<button type="button" class="missionPiece discoveryPiece" data-piece="${key}" aria-label="${A.labels[key]||key} 옮기기">${content||A.draw(key)}</button>`;
  const target=(id,content,label)=>`<button type="button" class="missionTarget discoveryTarget" data-target="${id}" aria-label="${label}">${content}<span class="targetContents"></span></button>`;
  function bindDrop(onDrop,selector){S.drag(area,{selector:selector||'[data-piece]',onSelect:id=>{if(subject==='영어')V.speak([en(id)],{status:audio});},onDrop});}
  const picture=key=>A.draw(key);
  if(subject==='영어'){global.EnglishSpace.render({q,root,area,audio});}
  else if(['listen','color','count','action','sense','weather','season','sentence','dialogue','phonics','soundChoice'].includes(q.mode)){
   const scene=q.scene?A.draw(q.scene):['soundChoice','phonics'].includes(q.mode)?A.draw(q.word):'';
   const content=key=>q.mode==='color'?A.draw('balloon',{color:key}):q.mode==='count'?'<div class="starGroup">'+Array.from({length:+key},()=>A.draw('star',{color:'yellow'})).join('')+'</div>':['sentence','dialogue'].includes(q.mode)?A.position(q.animal,'box',key):q.mode==='phonics'?'<b class="letterToy">'+S.esc(key.toUpperCase())+' <small>'+S.esc(key)+'</small></b>':q.mode==='soundChoice'?V.icon:picture(key);
   area.innerHTML=(scene?'<div class="discoveryHero">'+scene+'</div>':'')+`<div class="pictureChoices ${q.options.length===3?'three':''}">${q.options.map((key,i)=>`<button type="button" class="pictureChoice" data-answer="${key}" aria-label="${q.mode==='soundChoice'?'소리 '+(i+1):q.mode==='count'?key+'개 별':['sentence','dialogue'].includes(q.mode)?(i+1)+'번째 장면':A.labels[key]||key}">${content(key)}</button>`).join('')}</div>`+(q.mode==='soundChoice'?'<button class="spaceCheck" disabled>이 소리예요 ✓</button>':'');
   let picked=null;area.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{if(solved)return;const id=b.dataset.answer;if(q.mode==='soundChoice'){picked=id;area.querySelectorAll('[data-answer]').forEach(x=>x.classList.toggle('pickedSound',x===b));V.speak([en(id)],{button:b,status:audio});area.querySelector('.spaceCheck').disabled=false;return;}if(id===q.correct){b.classList.add('choiceCelebration');finish();}else wrong(b);});
   if(q.mode==='soundChoice')area.querySelector('.spaceCheck').onclick=e=>picked===q.correct?finish():wrong(e.currentTarget);
  }else if(['match','position','habitat','growth'].includes(q.mode)){
   const content=t=>q.mode==='position'?A.position('bear','box',t.relation):q.mode==='growth'?'<span class="sequenceDots">'+Array.from({length:+t.id+1},()=>'<i></i>').join('')+'</span>':A.draw(t.key);
   area.innerHTML=`<div class="discoveryTargets ${q.mode}">${q.targets.map(t=>target(t.id,content(t),q.mode==='growth'?(+t.id+1)+'번째 자리':q.mode==='position'?({on:'상자 위',under:'상자 아래',in:'상자 안'}[t.id]):(t.label||A.labels[t.key])+' 자리')).join('')}</div><div class="pieceTray">${q.items.map(x=>piece(x,q.mode==='match'?'<span class="wordToy">'+S.esc(x)+'</span>'+V.icon:null)).join('')}</div>`;
   const placed=new Set();bindDrop((id,targetId,el,t)=>{if(solved||placed.has(id))return false;if(q.expected[id]!==targetId){wrong(el);return false;}placed.add(id);el.disabled=true;el.classList.add('piecePlaced');t.querySelector('.targetContents').innerHTML=A.draw(id);t.classList.add('targetFilled');S.burst(t);feedback.textContent='좋아! 알맞은 곳에 놓았어.';if(placed.size===q.items.length)finish();return true;});
  }else if(q.mode==='float'){
   let prediction=null;const observed=new Set();area.innerHTML='<div class="floatPrediction"><button data-predict="float" aria-label="물 위에 뜰 것 같아"><svg viewBox="0 0 90 48"><path d="M0 26H90" stroke="#86cbdc" stroke-width="5"/><circle cx="45" cy="18" r="10" fill="#efc77a"/></svg></button><button data-predict="sink" aria-label="물 아래로 가라앉을 것 같아"><svg viewBox="0 0 90 48"><path d="M0 15H90" stroke="#86cbdc" stroke-width="5"/><circle cx="45" cy="36" r="10" fill="#b5b6bd"/></svg></button></div>'+target('tank','<div class="tankWater"></div><div class="experimentResult"></div>','물에 넣기')+'<div class="pieceTray">'+q.items.map(x=>piece(x)).join('')+'</div><div class="observationSummary"></div>';
   area.querySelectorAll('[data-predict]').forEach(b=>b.onclick=()=>{prediction=b.dataset.predict;area.querySelectorAll('[data-predict]').forEach(x=>x.classList.toggle('pickedSound',x===b));V.speak([ko(prediction==='float'?'물 위에 뜰까? 넣어서 확인해 보자.':'아래로 가라앉을까? 넣어서 확인해 보자.')],{status:audio});});
   bindDrop((id,t,el,box)=>{if(solved||observed.has(id))return false;if(!prediction){feedback.textContent='먼저 물 위나 아래 그림을 눌러 예상해 봐.';V.speak([ko(feedback.textContent)],{status:audio});return false;}const floats=M.floats(id);observed.add(id);el.disabled=true;box.querySelector('.experimentResult').innerHTML='<div class="waterObject '+(floats?'floats':'sinks')+'">'+A.draw(id)+'</div>';const result=(A.labels[id])+(floats?'이 물 위에 떴어.':'이 아래로 가라앉았어.');feedback.textContent=result;V.speak([ko(result)],{status:audio});prediction=null;area.querySelectorAll('[data-predict]').forEach(x=>x.classList.remove('pickedSound'));if(observed.size===q.items.length){const sum=area.querySelector('.observationSummary');sum.innerHTML='<p>물 위에 뜬 두 친구를 골라 줘.</p><div class="pictureChoices">'+q.items.map(x=>`<button class="pictureChoice" data-observed="${x}" aria-label="${A.labels[x]}" aria-pressed="false">${A.draw(x)}</button>`).join('')+'</div><button class="spaceCheck">확인 ✓</button>';const chosen=new Set();sum.querySelectorAll('[data-observed]').forEach(b=>b.onclick=()=>{const x=b.dataset.observed;if(chosen.has(x))chosen.delete(x);else chosen.add(x);b.setAttribute('aria-pressed',String(chosen.has(x)));});sum.querySelector('.spaceCheck').onclick=e=>chosen.size===2&&[...chosen].every(M.floats)?finish():wrong(e.currentTarget);V.speak([ko(result+' 물 위에 뜬 두 친구를 골라 줘.')],{status:audio});}return true;});
  }else if(q.mode==='magnet'){
   const observed=new Set();area.innerHTML='<div class="magnetObjects">'+q.items.map(x=>target(x,A.draw(x),A.labels[x]+' 가까이')).join('')+'</div><div class="pieceTray">'+piece('magnet')+'</div><div class="observationSummary"></div>';
   bindDrop((id,t,el,box)=>{if(solved)return false;const sticks=M.magnetic(t);observed.add(t);box.classList.remove('magnetPull','magnetStill');void box.offsetWidth;box.classList.add(sticks?'magnetPull':'magnetStill');feedback.textContent=A.labels[t]+(sticks?'이 자석을 따라왔어!':(t==='paper'?'는':'은')+' 자석에 붙지 않았어.');V.speak([ko(feedback.textContent)],{status:audio});if(observed.size===q.items.length){const sum=area.querySelector('.observationSummary');if(!sum.children.length){sum.innerHTML='<p>자석에 붙은 친구를 골라 줘.</p><div class="pictureChoices">'+q.items.map(x=>`<button class="pictureChoice" data-magnetic="${x}" aria-label="${A.labels[x]} 선택">${A.draw(x)}</button>`).join('')+'</div>';sum.querySelectorAll('[data-magnetic]').forEach(b=>b.onclick=()=>M.magnetic(b.dataset.magnetic)?finish():wrong(b));}}return true;});
  }else if(q.mode==='shadow'){
   let light='center',moved=false;area.innerHTML='<div class="shadowLab"><div class="movingSun">'+A.draw('sun')+'</div><div class="castShadow"></div><div class="shadowTree">'+A.draw('tree')+'</div></div><div class="lightControls"><button data-light="left" aria-label="빛을 왼쪽으로">← '+A.draw('sun')+'</button><button data-light="right" aria-label="빛을 오른쪽으로">'+A.draw('sun')+' →</button></div><input class="lightSlider" type="range" min="0" max="2" value="1" aria-label="광원 위치"><div class="shadowAnswers"><button data-shadow="left">← 그림자</button><button data-shadow="right">그림자 →</button></div>';
   const change=n=>{light=n===0?'left':n===2?'right':'center';moved=true;area.querySelector('.shadowLab').dataset.light=light;area.querySelector('.lightSlider').value=n;};area.querySelectorAll('[data-light]').forEach(b=>b.onclick=()=>change(b.dataset.light==='left'?0:2));area.querySelector('.lightSlider').oninput=e=>change(+e.target.value);area.querySelectorAll('[data-shadow]').forEach(b=>b.onclick=()=>{if(moved&&light===q.light&&b.dataset.shadow===q.correct)finish();else wrong(b);});
  }else if(q.mode==='dayNight'){
   let angle=0,moved=false;area.innerHTML='<div class="dayNightLab"><div class="daySun">'+A.draw('sun')+'</div><div class="earthBall">'+A.draw('earth')+'<i class="earthNight"></i><i class="homeMarker"></i></div></div><button class="turnEarth" aria-label="지구 회전">↻ 지구 돌리기</button><button class="spaceCheck">이 자리예요 ✓</button>';
   area.querySelector('.turnEarth').onclick=()=>{if(solved)return;angle=(angle+180)%360;moved=true;area.querySelector('.homeMarker').style.transform='rotate('+angle+'deg) translateX(-54px) rotate('+(-angle)+'deg)';};area.querySelector('.spaceCheck').onclick=e=>moved&&((angle===0?'day':'night')===q.correct)?finish():wrong(e.currentTarget);
  }else if(q.mode==='experiment'){
   let level=0,changed=false;area.innerHTML='<div class="conditionComparison" data-condition="'+q.condition+'"><div class="controlExperiment">'+A.draw(q.condition==='light'?'plant':'wind')+'<span>그대로</span></div><div class="changedExperiment">'+A.draw(q.condition==='light'?'plant':'wind')+'<span>바꿔 보기</span></div></div><div class="conditionControls">'+[0,1,2].map(n=>`<button data-level="${n}" aria-label="${q.condition==='light'?'햇빛':'바람'} ${n}단계">${A.draw(q.condition==='light'?'sun':'wind')}<span class="sequenceDots">${Array.from({length:n+1},()=>'<i></i>').join('')}</span></button>`).join('')+'</div><button class="spaceCheck">변화를 봤어요 ✓</button>';
   area.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{if(solved)return;level=+b.dataset.level;changed=true;area.querySelectorAll('[data-level]').forEach(x=>x.classList.toggle('pickedSound',x===b));const el=area.querySelector('.changedExperiment');el.dataset.level=level;if(q.condition==='light'){el.style.setProperty('--growth',.5+level*.25);el.classList.add('plantExperiment');}else{el.classList.add('windExperiment');el.style.setProperty('--wind-speed',level===0?'0s':level===1?'2s':'.7s');}feedback.textContent=q.condition==='light'?'같은 물과 흙에서 햇빛의 양을 바꾼 모습을 살펴봐.':'바람이 세질수록 바람개비가 빨리 돌아.';});area.querySelector('.spaceCheck').onclick=e=>changed&&level===q.goal?finish():wrong(e.currentTarget);
  }
  if(state.sound)Session.timeout(read,250);
 }
 global.DiscoverySpace={play};
})(window);
