(function(global){
 const S=global.LearningSpace,chars=global.HanjaCharacters;
 const phasesFor=stage=>stage<=chars.length?['A','A','B','B','C','D']:stage<=chars.length*2?['B','C','D']:stage<=chars.length*3?['C','D']:['D'];
 function lesson(stage){const character=chars[(stage-1)%chars.length];return {stage,character,phases:phasesFor(stage),review:stage>chars.length};}
 const titles={A:'진한 선 따라쓰기',B:'점선 따라쓰기',C:'도움선 살짝 보기',D:'기억해서 쓰기'};
 function record(stage){state.records.learningSpace||={};state.records.learningSpace.hanja||={};return state.records.learningSpace.hanja[stage]||=( {phase:0,stroke:0,attempts:0,completed:false} );}
 function persist(){try{localStorage.setItem('sianhi-v2',JSON.stringify(state));}catch{}}
 function art(scene){const tree='<path d="M60 78V36" stroke="#ac8a5b" stroke-width="12"/><circle cx="60" cy="32" r="27" fill="url(#jade)"/><circle cx="43" cy="43" r="21" fill="url(#jade)"/><circle cx="77" cy="45" r="21" fill="url(#jade)"/>';let shape='';
 if(['tree','grove','forest'].includes(scene))shape=scene==='tree'?tree:scene==='grove'?`<g transform="translate(-19 13) scale(.78)">${tree}</g><g transform="translate(44 8) scale(.8)">${tree}</g>`:`<g transform="translate(20 -5) scale(.75)">${tree}</g><g transform="translate(-12 20) scale(.75)">${tree}</g><g transform="translate(50 20) scale(.75)">${tree}</g>`;
 else if(scene==='mountain')shape='<path d="M3 83L38 25L73 83Z" fill="url(#jade)"/><path d="M40 83L78 9L116 83Z" fill="#a6cfb9"/><path d="M78 9L66 33L78 28L88 31Z" fill="#fff7e1"/>';
 else if(['river','water'].includes(scene))shape='<path d="M42 0Q85 22 44 40T75 99H112Q62 67 89 46T77 0" fill="url(#water)"/><path d="M55 5Q85 25 55 39M57 63L85 83" fill="none" stroke="#ecffff" stroke-width="5" stroke-linecap="round"/>';
 else if(scene==='fire')shape='<path d="M25 78L94 87M34 89L83 73" stroke="#a7825b" stroke-width="9" stroke-linecap="round"/><path d="M62 7C77 34 93 45 83 65C77 88 33 89 27 63C19 48 37 36 40 21L51 40Z" fill="url(#flame)"/><path d="M57 39Q79 66 56 79Q31 67 57 39" fill="#ffebb1"/>';
 else if(scene==='sun')shape='<g stroke="#f1cb68" stroke-width="5">'+Array.from({length:8},(_,i)=>`<path d="M60 8V1" transform="rotate(${i*45} 60 45)"/>`).join('')+'</g><circle cx="60" cy="45" r="30" fill="url(#gold)"/>';
 else if(scene==='moon')shape='<path d="M76 8C40 21 41 71 87 76C41 99 11 60 35 24Q53 8 76 8" fill="url(#gold)"/>';
 else if(['rain','sky','empty'].includes(scene))shape='<path d="M24 48Q3 24 35 21Q44 -2 68 14Q96 9 99 34Q116 55 89 59H29Z" fill="#f4fcff" stroke="#aaceda" stroke-width="3"/>'+ (scene==='rain'?'<path d="M34 70L29 80M64 71L59 82M88 70L83 81" stroke="#65a8cf" stroke-width="5" stroke-linecap="round"/>':scene==='empty'?'<rect x="36" y="62" width="52" height="27" rx="8" fill="#e6dab8" stroke="#b6a278" stroke-width="3"/>':'');
 else if(scene==='field')shape='<path d="M12 56L75 26L116 61L52 93Z" fill="#b0cf85" stroke="#658e6b" stroke-width="4"/><path d="M42 42L82 77M31 74L96 43" stroke="#f3e0a6" stroke-width="5"/>';
 else if(scene==='soil'||scene==='stone')shape=scene==='soil'?'<path d="M12 61Q58 25 112 59V80H12Z" fill="#c3a47c"/><path d="M55 51V23M55 35Q30 38 34 17Q52 15 55 35M55 29Q79 30 80 12Q60 8 55 29" fill="#9cc28c" stroke="#7ca578" stroke-width="3"/>':'<path d="M20 67L29 34L65 19L98 42L105 76L55 87Z" fill="#acbfc5"/><path d="M29 34L66 39L98 42L65 19Z" fill="#dde9e6"/>';
 else if(['one','two','three'].includes(scene)){const n={one:1,two:2,three:3}[scene];shape=Array.from({length:n},(_,i)=>`<circle cx="${60-(n-1)*17+i*34}" cy="50" r="15" fill="url(#gold)"/>`).join('');}
 else if(['person','big','small'].includes(scene))shape=`<g transform="translate(${scene==='small'?30:0} ${scene==='small'?25:0}) scale(${scene==='small'?.6:1})"><circle cx="60" cy="19" r="13" fill="#f0cdab"/><path d="M60 37V60M60 41L31 53M60 41L88 53M60 60L37 87M60 60L85 87" fill="none" stroke="#83bba8" stroke-width="13" stroke-linecap="round"/></g>`;
 else if(['up','down','middle'].includes(scene))shape='<rect x="16" y="49" width="89" height="10" rx="5" fill="#a2c5c5"/>'+`<circle cx="60" cy="${scene==='up'?25:scene==='down'?80:54}" r="14" fill="url(#gold)"/>`;
 else if(scene==='eye')shape='<path d="M9 51Q58 4 111 51Q61 95 9 51Z" fill="#fff" stroke="#86aaa5" stroke-width="4"/><circle cx="60" cy="51" r="19" fill="#518e90"/><circle cx="60" cy="51" r="9" fill="#294562"/>';
 else if(scene==='mouth')shape='<path d="M20 36Q60 18 100 36Q83 89 60 85Q36 84 20 36Z" fill="#e99494"/><path d="M33 38H87L83 53H37Z" fill="#fffaf0"/>';
 else if(scene==='ear')shape='<path d="M43 78Q23 55 35 26Q51 5 75 25Q94 48 69 66Q68 93 49 87" fill="#f0ceb3" stroke="#c39f86" stroke-width="5"/><path d="M47 48Q42 28 64 32Q80 43 59 55V69" fill="none" stroke="#c39f86" stroke-width="5"/>';
 else if(scene==='hand')shape='<path d="M32 56L20 44Q10 37 12 51L31 78Q65 105 88 73L91 28Q85 17 80 29L77 48V12Q70 4 65 13V45L59 8Q52 1 47 12L51 46L41 19Q33 11 29 24Z" fill="#edccaf" stroke="#c8a98d" stroke-width="3"/>';
 else if(scene==='foot')shape='<ellipse cx="61" cy="60" rx="23" ry="30" fill="#edccaf"/>'+Array.from({length:5},(_,i)=>`<ellipse cx="${31+i*13}" cy="${35-Math.sin(i/4*Math.PI)*14}" rx="${6+i}" ry="10" fill="#edccaf"/>`).join('');
 return `<svg viewBox="0 0 125 105" role="img" aria-label="${S.esc(scene)}"><defs><radialGradient id="jade" cx="30%" cy="20%"><stop stop-color="#d8efb9"/><stop offset="1" stop-color="#74b8a0"/></radialGradient><linearGradient id="water"><stop stop-color="#c4f3f8"/><stop offset="1" stop-color="#74bddd"/></linearGradient><radialGradient id="gold"><stop stop-color="#fff5be"/><stop offset="1" stop-color="#edc25d"/></radialGradient><linearGradient id="flame" x2="0" y2="1"><stop stop-color="#ffda83"/><stop offset="1" stop-color="#e88c69"/></linearGradient></defs><ellipse cx="61" cy="94" rx="51" ry="9" fill="#476e5d22"/>${shape}</svg>`;
 }
 function assess(input,guide,pointerType){
  if(input.length<3||input.length>1200)return false;
  // Low-pass tiny finger tremor before measuring length and corridor coverage.
  const smooth=input.map((p,i)=>{if(i===0||i===input.length-1)return p;const a=input[Math.max(0,i-2)],b=input[Math.max(0,i-1)],c=input[Math.min(input.length-1,i+1)],d=input[Math.min(input.length-1,i+2)];return [(a[0]+b[0]+p[0]+c[0]+d[0])/5,(a[1]+b[1]+p[1]+c[1]+d[1])/5];});
  const first=smooth[0],last=smooth.at(-1),gs=guide[0],ge=guide.at(-1),dx=ge[0]-gs[0],dy=ge[1]-gs[1];
  if((last[0]-first[0])*dx+(last[1]-first[1])*dy<=0)return false;
  const uniform=path=>{const lengths=[0];for(let i=1;i<path.length;i++)lengths.push(lengths[i-1]+Math.hypot(path[i][0]-path[i-1][0],path[i][1]-path[i-1][1]));const total=lengths.at(-1);if(total<.01)return path;let k=1;return Array.from({length:97},(_,i)=>{const d=total*i/96;while(k<lengths.length-1&&lengths[k]<d)k++;const t=(d-lengths[k-1])/(lengths[k]-lengths[k-1]||1);return [path[k-1][0]+(path[k][0]-path[k-1][0])*t,path[k-1][1]+(path[k][1]-path[k-1][1])*t];});};
  return HangulTrace.assess(uniform(smooth),uniform(guide),pointerType==='mouse'?8:10);
 }
 function samples(p){const result=[];for(let i=1;i<p.length;i++){const a=p[i-1],b=p[i],n=Math.max(1,Math.ceil(Math.hypot(b[0]-a[0],b[1]-a[1])));for(let j=0;j<n;j++)result.push([a[0]+(b[0]-a[0])*j/n,a[1]+(b[1]-a[1])*j/n]);}result.push(p.at(-1));return result;}
 function play(stage){
  const info=lesson(stage),ch=info.character,r=record(stage);let round=r.completed?0:Math.min(r.phase,info.phases.length),stroke=r.completed?0:Math.min(r.stroke,ch.strokeCount-1),ink=[],accepted=[],active=null,disposed=false,animating=false,raf=0,dot=null,hint=false;
  const prompt=ch.meaning+' '+ch.reading+'. 보고, 따라 쓰고, 기억해서 써 보자.';
  const root=S.shell('한자',stage,(info.review?'다시 만나는 ':'처음 만나는 ')+ch.character,prompt,'garden'),area=root.querySelector('.spaceGameplay'),feedback=root.querySelector('.spaceFeedback');root.classList.add('hanjaSpace');
  function meaning(){return `<div class="hanjaMeaning"><div class="hanjaMeaningArt">${art(ch.scene)}</div><b class="hanjaSymbol">${ch.character}</b></div><p class="hanjaCaption">${ch.character} · ${ch.meaning} ${ch.reading}</p>`;}
  area.innerHTML=meaning()+`<div class="hanjaWork"></div><p class="hanjaAttribution">획순 자료: <a href="https://github.com/parsimonhi/animCJK" target="_blank" rel="noopener">AnimCJK 한국 한자</a> · <a href="assets/learning/hanja/NOTICE.md" target="_blank">출처</a></p>`;
  const work=area.querySelector('.hanjaWork');let canvas,g,observer;
  const phase=()=>info.phases[round]||'D';
  function line(ps,color,width,dash=[]){if(!ps.length)return;g.beginPath();g.lineWidth=width;g.strokeStyle=color;g.setLineDash(dash);ps.forEach(([x,y],i)=>i?g.lineTo(x,y):g.moveTo(x,y));g.stroke();g.setLineDash([]);}
  function draw(){if(disposed||!canvas||!canvas.isConnected)return;const size=canvas.clientWidth,dpr=Math.min(devicePixelRatio||1,2);if(canvas.width!==Math.round(size*dpr))canvas.width=canvas.height=Math.round(size*dpr);g.setTransform(canvas.width/100,0,0,canvas.height/100,0,0);g.clearRect(0,0,100,100);g.lineCap=g.lineJoin='round';line([[50,4],[50,96]],'#e5e7de',.35,[2,2]);line([[4,50],[96,50]],'#e5e7de',.35,[2,2]);const p=phase();
   ch.strokePaths.forEach((ps,i)=>{const done=i<stroke;const visible=p!=='D'||hint;if(visible){if(ch.outlines[i]&&p!=='B'){g.save();g.scale(100/1024,-100/1024);g.translate(0,-900);g.fillStyle=p==='C'?'#e3e9df':i===stroke?'#bdd9cb':'#e1e9dd';g.fill(new Path2D(ch.outlines[i]));g.restore();}else line(ps,p==='C'?'#e6e9df':i===stroke?'#89b9a7':'#cdded4',p==='B'?1.2:6,p==='B'?[1,2]:[]);}if(done)line(accepted[i]||ps,'#347c71',3.4);
    if((p==='A'||p==='B'||hint)&&i===stroke){const start=ps[0],next=ps[1];g.fillStyle='#caa34c';g.beginPath();g.arc(start[0],start[1],2.3,0,7);g.fill();g.fillStyle='#294562';g.font='4px Pretendard,sans-serif';g.fillText(String(i+1),Math.max(2,start[0]-5),Math.max(5,start[1]-4));if(p==='A'){const a=Math.atan2(next[1]-start[1],next[0]-start[0]),x=start[0]+Math.cos(a)*9,y=start[1]+Math.sin(a)*9;line([[x-3*Math.cos(a-.6),y-3*Math.sin(a-.6)],[x,y],[x-3*Math.cos(a+.6),y-3*Math.sin(a+.6)]],'#caa34c',1);}}
   });line(ink,'#286c7c',3.2);if(dot){g.beginPath();g.fillStyle='#d5a749';g.arc(dot[0],dot[1],2.8,0,7);g.fill();}
   const counter=work.querySelector('[data-strokes]');if(counter)counter.textContent=Math.min(stroke+1,ch.strokeCount)+' / '+ch.strokeCount+'획';
  }
  function demo(){if(disposed||!canvas)return;cancelAnimationFrame(raf);active=null;ink=[];hint=true;animating=true;let start;const ss=ch.strokePaths.map(samples),from=stroke;feedback.textContent='빛나는 점의 방향을 천천히 살펴봐.';function frame(t){if(disposed)return;start??=t;const pos=(t-start)/720,i=from+Math.floor(pos);if(i>=ss.length){dot=null;animating=false;hint=false;feedback.textContent='이제 직접 써 볼까?';draw();return;}dot=ss[i][Math.min(ss[i].length-1,Math.floor(pos%1*ss[i].length))];draw();raf=requestAnimationFrame(frame);}raf=requestAnimationFrame(frame);}
  const pt=e=>{const b=canvas.getBoundingClientRect();return [(e.clientX-b.left)*100/b.width,(e.clientY-b.top)*100/b.height];};
  function down(e){if(animating||active!==null||stroke>=ch.strokeCount||e.button>0)return;e.preventDefault();active=e.pointerId;canvas.setPointerCapture(active);ink=[pt(e)];draw();}
  function move(e){if(active!==e.pointerId)return;e.preventDefault();for(const ev of e.getCoalescedEvents?.()||[e]){const p=pt(ev),last=ink.at(-1);if(Math.hypot(p[0]-last[0],p[1]-last[1])>.5&&ink.length<1201)ink.push(p);}draw();}
  function up(e){if(active!==e.pointerId)return;e.preventDefault();const end=pt(e);if(Math.hypot(end[0]-ink.at(-1)[0],end[1]-ink.at(-1)[1])>.1)ink.push(end);active=null;r.attempts++;if(assess(ink,ch.strokePaths[stroke],e.pointerType)){accepted[stroke]=ink.slice();stroke++;if(global.VoiceDirector)LearningSpeech.speak([stroke===ch.strokeCount?{text:'완성! '+ch.meaning+' '+ch.reading+'이야.',lang:'ko-KR'}:VoiceDirector.cue('stroke')]);r.stroke=stroke;feedback.textContent='좋아! '+stroke+'획을 썼어.';hint=false;if(stroke===ch.strokeCount){r.phase=round+1;r.stroke=0;work.querySelector('[data-next-round]').disabled=false;feedback.textContent='잘 썼어! '+ch.character+' 완성. 다음 쓰기로 가 볼까?';S.burst(root.querySelector('.spaceStage'));}}else{feedback.textContent='여기서부터 다시 그어볼까? 시작점과 방향을 살펴봐.';hint=true;}ink=[];persist();draw();}
  function cancel(){active=null;ink=[];draw();}
  function clearBoard(){cancelAnimationFrame(raf);observer?.disconnect();if(canvas){canvas.removeEventListener('pointerdown',down);canvas.removeEventListener('pointermove',move);canvas.removeEventListener('pointerup',up);canvas.removeEventListener('pointercancel',cancel);}canvas=null;}
  function review(){clearBoard();work.innerHTML=`<p class="hanjaReviewCaption">그림에 어울리는 한자 블록을 옮겨 줘.</p><div class="hanjaReviewTargets"><button class="missionTarget" data-target="meaning" aria-label="${ch.meaning} 그림">${art(ch.scene)}<span class="targetContents"></span></button></div><div class="pieceTray">${LearningBank.shuffle([ch,chars[(chars.indexOf(ch)+6)%chars.length],chars[(chars.indexOf(ch)+14)%chars.length]]).map(c=>`<button class="missionPiece hanjaCard" data-piece="${c.character}" aria-label="${c.character} 한자 블록">${c.character}</button>`).join('')}</div>`;S.drag(work,{onDrop:(id,target,el,t)=>{if(root.dataset.finished)return false;if(id!==ch.character){feedback.textContent='그림과 함께 보았던 한자 모양을 찾아봐.';return false;}el.disabled=true;t.querySelector('.targetContents').textContent=ch.character;r.completed=true;r.phase=info.phases.length;r.stroke=0;persist();S.complete(root,'한자',stage,ch.meaning+' '+ch.reading+'을 눈과 손으로 기억했어.');return true;}});feedback.textContent='마지막으로 그림과 글자를 연결해 보자.';}
  function mount(){if(round>=info.phases.length){review();return;}clearBoard();accepted=[];ink=[];hint=false;animating=false;dot=null;const p=phase();work.innerHTML=`<div class="hanjaLoopDots" aria-label="쓰기 ${round+1}/${info.phases.length}">${info.phases.map((_,i)=>`<i class="${i<round?'done':i===round?'current':''}"></i>`).join('')}</div><div class="hanjaPhase"><span>${p} · ${titles[p]}</span><span data-strokes></span></div><div class="hanjaBoard"><canvas class="hanjaCanvas" aria-label="${ch.character} 한자 쓰기 영역" role="img"></canvas></div><div class="hanjaTools"><button type="button" data-reset>다시 쓰기</button><button type="button" data-demo>획순 보기</button><button type="button" data-next-round disabled>다음 쓰기 →</button></div>`;canvas=work.querySelector('canvas');g=canvas.getContext('2d');canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',cancel);work.querySelector('[data-reset]').onclick=()=>{cancelAnimationFrame(raf);stroke=0;r.stroke=0;r.phase=round;accepted=[];ink=[];active=null;animating=false;dot=null;hint=false;persist();work.querySelector('[data-next-round]').disabled=true;feedback.textContent='이 글자만 처음부터 다시 써 보자.';draw();};work.querySelector('[data-demo]').onclick=()=>{if(stroke===ch.strokeCount){feedback.textContent='다 썼어! 다음 쓰기로 가 보자.';return;}demo();};work.querySelector('[data-next-round]').onclick=()=>{round++;stroke=0;r.phase=round;r.stroke=0;persist();mount();};observer=new ResizeObserver(draw);observer.observe(canvas);draw();feedback.textContent=p==='D'?'도움선 없이 기억해서 써 봐. 필요하면 획순을 다시 봐도 괜찮아.':'시작점에서 천천히 써 보자.';if(p==='A'&&round===0)demo();}
  LearningSpeech.bind(root.querySelector('.spaceVoice'),()=>global.VoiceDirector?VoiceDirector.hanja(ch):ch.meaning+' '+ch.reading+'. '+(phase()==='D'?'기억해서 써 보자.':'획순을 따라 써 보자.'),root.querySelector('.learningAudioStatus'));
  const discover=document.createElement('button');discover.textContent='그림 속 모양 보기';discover.onclick=()=>{area.classList.remove('meaningDiscover');void area.offsetWidth;area.classList.add('meaningDiscover');S.voice(ch.character==='木'?'나무의 줄기와 가지를 떠올려 봐.':ch.character==='山'?'높고 낮은 산봉우리를 떠올려 봐.':ch.meaning+' '+ch.reading+'. 그림과 글자 모양을 함께 살펴봐.');};root.querySelector('.spaceActions').append(discover);mount();Session.cleanup(()=>{disposed=true;clearBoard();});
 }
 global.HanjaSpace={play,lesson,assess,art,phasesFor,record};
})(window);
