(function(B){
 const consonants=[...'ㄱㄴㄷㄹㅁㅂㅅㅇㅈㅊㅋㅌㅍㅎ'],vowels=[...'ㅏㅑㅓㅕㅗㅛㅜㅠㅡㅣ'],names=['기역','니은','디귿','리을','미음','비읍','시옷','이응','지읒','치읓','키읔','티읕','피읖','히읗'];
 const words=['나무','바다','사자','오리','하늘','구름','바람','고래','상어','문어','조개','해파리','산호초','잠수함','자동차','비행기','해바라기','놀이터','불가사리','기린','토끼','사과','우유','기차'];
 const choose=(a,n)=>a[((n%a.length)+a.length)%a.length],mc=(q,ans,opts,category,extra={})=>({q,ans,opts,category,templateId:category,questionType:'multiple-choice',explanation:'정답은 '+ans+'이에요. 문제의 글자와 뜻을 다시 살펴봐요.',difficulty:1,...extra});
 B.koreanFallback=(stage,n=0)=>{const pool=stage<=10?[...consonants,...vowels]:stage<21?[...consonants,...vowels,...'가나다라마바사아자차카타파하']:stage<70?Array.from({length:140},(_,i)=>String.fromCharCode(44032+Math.floor(i/10)*588+(i%10)*28)):words;const ans=choose(pool,n);return mc('「'+ans+'」와 같은 글자를 찾아요.',ans,[ans,...pool.filter(x=>x!==ans).slice(0,3)],'sameGlyph',{difficulty:Math.ceil(stage/10)});};
 B.koreanQuestion=function(stage,attempt,old){const ch=Math.floor((stage-1)/10),n=stage+attempt+Math.floor(Math.random()*97);let q;
 if(stage%4===0&&ch<9){const pool=ch===0?(stage<=4?consonants:vowels):ch===1?[...'가나다라마바사아자차카타파하']:ch<4?[...'갸냐댜랴먀뱌샤야쟈챠캬탸퍄햐거너더러머버서어저처커터퍼허겨녀뎌려며벼셔여져쳐켜텨펴혀고노도로모보소오교뇨됴료구누두루규뉴듀류그느드르기니디리']:ch===4?[...'까따빠싸짜']:ch===5?[...'개게과괘괴궈궤귀긔']:ch===6?[...'산달별꽃집문공책밥']:words;const ans=choose(pool,n);q=mc(ans+'을 따라 써 보세요.',ans,[], 'tracing',{questionType:'HANGUL_TRACING',traceType:ch===0?(stage<=4?'TRACE_CONSONANT':'TRACE_VOWEL'):ch>=7?'TRACE_WORD':'TRACE_SYLLABLE'});}
 else if(ch===0){const k=n%3;if(k===2){const i=n%14;q=mc('이름이 「'+names[i]+'」인 자음은?',consonants[i],[consonants[i],...consonants.filter(x=>x!==consonants[i]).slice(0,3)],'consonantName');}else{const pool=k?consonants:vowels,wrong=k?vowels:consonants,ans=choose(pool,n);q=mc('다음 중 '+(k?'자음':'모음')+'은?',ans,[ans,...Array.from({length:3},(_,i)=>choose(wrong,n+i))],k?'consonant':'vowel');}}
 else if(ch<4){const initial=n%14,v=ch===1?0:choose([2,6,4,8,12,13,17,18,20],n),indices=[0,2,3,5,6,7,9,11,12,14,15,16,17,18],ans=String.fromCharCode(44032+indices[initial]*588+v*28);q=mc(consonants[initial]+' + '+[...'ㅏㅐㅑㅒㅓㅔㅕㅖㅗㅘㅙㅚㅛㅜㅝㅞㅟㅠㅡㅢㅣ'][v]+'를 합치면?',ans,[ans,...[1,3,5].map(x=>String.fromCharCode(44032+indices[(initial+x)%14]*588+v*28))],'combine');}
 else if(ch===7){const ans=choose(words,n);if(n%3===0){const count=choose([2,3,4],n+1),a=choose(words.filter(x=>x.length===count),n);q=mc(count+'글자 낱말은?',a,[a,...words.filter(x=>x.length!==count).slice(0,3)],'syllableCount',{count});}else if(n%3===1){const sea=['고래','상어','문어','조개','해파리','새우'],a=choose(sea,n);q=mc('바다에 사는 것은?',a,[a,'토끼','기린','사자'],'seaAnimal');}else q=mc('「'+ans+'」의 빈칸: '+ans.slice(0,-1)+'□',ans.at(-1),[ans.at(-1),...[...'가나다라마바사'].filter(x=>x!==ans.at(-1)).slice(0,3)],'wordComplete');}
 else if(ch>=8&&n%3===0){q=old(stage,attempt);}
 else if(ch>=8){const actors=['시안','민수','지수','유나','하나','준우','서아'],things=['책','공','우유','사과','연필','모자'],a=choose(actors,n),b=choose(actors,n+2),item=choose(things,Math.floor(n/7));q=mc(a+(B.hangulRules.final(a.at(-1))?'이는 ':'는 ')+item+(B.hangulRules.final(item.at(-1))?'을':'를')+' 가지고 있어요. '+b+(B.hangulRules.final(b.at(-1))?'이는':'는')+' 꽃을 가지고 있어요.\n'+item+(B.hangulRules.final(item.at(-1))?'을':'를')+' 가진 사람은?',a,[a,...actors.filter(x=>x!==a).slice(0,3)],'readingOwner',{questionType:'reading'});}
 else q=old(stage,attempt);q.category||=q.templateId;q.difficulty=ch+1;return q;
 };
for(const s of window.SianCurriculum.curricula.한글){if(s.stage%4===0&&s.stage<90)s.questionType='HANGUL_TRACING';}
})(LearningBank);
