/* Shared light, depth, input and reward language for learning; no WebGL dependency. */
(function(global){
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const palette={red:['#ffb1a5','#ef6c73','#b74057'],blue:['#b4e6ff','#62addf','#357eaf'],yellow:['#fff0a6','#f5c654','#c28b34'],green:['#c2efca','#75bea1','#448b78']};
 const names={red:'빨간색',blue:'파란색',yellow:'노란색',green:'초록색',circle:'동그라미',triangle:'삼각형',square:'네모',star:'별',big:'큰',small:'작은'};
 let serial=0;
 function object(it){const id='toyPaint'+(++serial),p=palette[it.color]||palette.blue;let shape={circle:'<circle cx="50" cy="43" r="27"/>',triangle:'<path d="M50 13L83 71Q85 76 78 76H22Q15 76 18 70Z"/>',square:'<rect x="21" y="16" width="58" height="58" rx="12"/>',star:'<path d="M50 9L62 31L86 35L69 54L73 79L50 68L27 79L31 54L14 35L38 31Z"/>'}[it.shape]||'<circle cx="50" cy="43" r="27"/>';
 if(it.kind==='fruit')shape='<path d="M50 27C20 8 9 35 18 61C25 87 42 84 50 77C64 91 78 78 83 54C90 25 72 13 50 27Z"/><path d="M50 27Q42 14 49 7" fill="none" stroke="#886546" stroke-width="5"/><path d="M50 20Q64 1 77 13Q69 28 50 20" fill="#75b69a"/>';
 if(it.kind==='toy')shape='<circle cx="26" cy="20" r="13"/><circle cx="74" cy="20" r="13"/><rect x="23" y="21" width="54" height="53" rx="23"/><circle cx="38" cy="44" r="3" fill="#294562"/><circle cx="62" cy="44" r="3" fill="#294562"/><path d="M42 57Q50 65 58 57" fill="none" stroke="#294562" stroke-width="3"/>';
 const scale=it.scale|| (it.size==='small'?.72:1);
 return `<svg class="spaceObject" viewBox="0 0 100 100" aria-hidden="true"><defs><linearGradient id="${id}" x1="0" y1="0" x2=".8" y2="1"><stop stop-color="${p[0]}"/><stop offset=".5" stop-color="${p[1]}"/><stop offset="1" stop-color="${p[2]}"/></linearGradient></defs><ellipse class="contactShadow" cx="51" cy="88" rx="32" ry="7" fill="#355f7026"/><g transform="translate(${50-scale*50} ${78-scale*78}) scale(${scale})">${it.kind==='candy'?`<path d="M24 25L4 17L10 46L3 65L25 60M76 25L96 17L90 46L97 65L75 60" fill="${p[1]}" stroke="${p[0]}" stroke-width="3"/>`:''}<g fill="${p[2]}" transform="translate(0 6)">${shape}</g><g fill="url(#${id})" stroke="${p[0]}" stroke-width="1.5">${shape}</g><path d="M32 28Q37 23 43 23" fill="none" stroke="#fff9" stroke-width="5" stroke-linecap="round"/>${it.kind==='number'||it.kind==='coin'?`<text x="50" y="52" text-anchor="middle" fill="#294562" font-family="Pretendard,sans-serif" font-size="${String(it.value).length>3?19:28}" font-weight="800">${esc(it.value)}</text>`:''}</g></svg>`;
 }
 function label(it){return it.kind==='number'?String(it.value):it.kind==='coin'?it.value+'원 동전':(names[it.color]||'')+' '+(names[it.shape]||'')+(it.size==='small'?' 작은':'')+' '+({fruit:'과일',toy:'장난감',candy:'사탕',block:'블록'}[it.kind]||'');}
 function scenery(theme='garden'){return `<div class="spaceBackdrop" aria-hidden="true"><i class="spaceSun"></i><i class="spaceCloud c1"></i><i class="spaceCloud c2"></i><div class="spaceHills"></div></div><div class="spaceMidground" aria-hidden="true"><i class="spaceTree t1"></i><i class="spaceTree t2"></i>${['market','candy','toy','factory','table','bakery'].includes(theme)?'<div class="shopAwning"></div>':''}</div><div class="spaceForeground" aria-hidden="true"><i></i><i></i><i></i></div>`;}
 function voice(text){return LearningSpeech.speak(text);}
 function sound(){if(!state.sound)return;try{const A=window.AudioContext||window.webkitAudioContext;if(!A)return;const ctx=new A(),o=ctx.createOscillator(),gain=ctx.createGain();o.connect(gain);gain.connect(ctx.destination);gain.gain.setValueAtTime(.055,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.24);o.frequency.setValueAtTime(650,ctx.currentTime);o.frequency.exponentialRampToValueAtTime(1050,ctx.currentTime+.2);o.start();o.stop(ctx.currentTime+.25);o.onended=()=>ctx.close();Session.cleanup(()=>ctx.close().catch(()=>{}));}catch{}}
 function burst(host){host.classList.remove('spaceSuccess');void host.offsetWidth;host.classList.add('spaceSuccess');sound();}
 function shell(subject,stage,title,prompt,theme='garden'){
   gameBody.innerHTML=`<section class="learningSpace" data-subject="${esc(subject)}" data-theme="${theme}"><div class="spaceToolbar"><button type="button" data-space-back>← 지도</button><b>${esc(subject)} · ${stage}/100</b></div><div class="spaceHeading"><small>시안이의 작은 배움 세계</small><h2>${esc(title)}</h2><p>${esc(prompt)}</p><button type="button" class="spaceVoice">🔊 문제 듣기</button></div><div class="spaceStage">${scenery(theme)}<div class="spaceGameplay"></div></div><p class="spaceFeedback" aria-live="polite">그림을 만져 보고, 천천히 옮겨 봐.</p><div class="spaceActions"></div></section>`;
   const root=gameBody.querySelector('.learningSpace');LearningHeader.mount(root.querySelector('.spaceToolbar'),subject,stage,()=>openStageMap(subject));const audioStatus=document.createElement('p');audioStatus.className='learningAudioStatus';audioStatus.setAttribute('aria-live','polite');root.querySelector('.spaceHeading').append(audioStatus);LearningSpeech.bind(root.querySelector('.spaceVoice'),prompt,audioStatus);game.showModal();game.scrollTop=0;return root;
 }
 function complete(root,subject,stage,text){if(root.dataset.finished)return;root.dataset.finished='true';LearningBank.record(subject,true);state.stage100[subject]=Math.max(state.stage100[subject]||1,Math.min(100,stage+1));award('learn:'+subject+':'+stage);burst(root.querySelector('.spaceStage'));root.querySelector('.spaceFeedback').textContent='잘했어! '+text;const next=document.createElement('button');next.className='nextBtn';next.textContent=stage<100?'다음 미션 →':'지도로 돌아가기';next.onclick=()=>stage<100?playStage100(subject,stage+1):openStageMap(subject);root.querySelector('.spaceActions').append(next);}
 /* One pointer engine; click/tap-select then target is an equal-access alternative. */
 function drag(host,{onDrop,onSelect=()=>{},selector='[data-piece]',targetSelector='[data-target]'}){
   let selected=null,active=null,origin=null,moved=false,suppressClick=false;
   function clear(){host.querySelectorAll('.targetNear').forEach(e=>e.classList.remove('targetNear'));if(selected){selected.classList.remove('lifted');selected.style.removeProperty('transform');}active=null;}
   function nearest(x,y){return [...host.querySelectorAll(targetSelector)].find(t=>{const r=t.getBoundingClientRect();return x>=r.left&&x<=r.right&&y>=r.top&&y<=r.bottom;});}
   function choose(el){host.querySelectorAll('.pieceSelected').forEach(x=>x.classList.remove('pieceSelected'));selected=el;el.classList.add('pieceSelected');onSelect(el.dataset.piece);}
   function drop(t){if(!selected||selected.disabled)return;const el=selected;if(onDrop(el.dataset.piece,t.dataset.target,el,t)){el.classList.remove('pieceSelected');selected=null;}else{el.classList.add('spaceShake');Session.timeout(()=>el.classList.remove('spaceShake'),350);}}
   function down(e){const el=e.target.closest(selector);if(!el||el.disabled||active!==null||e.button>0)return;e.preventDefault();choose(el);active=e.pointerId;origin={x:e.clientX,y:e.clientY};moved=false;el.setPointerCapture(active);el.classList.add('lifted');}
   function move(e){if(active!==e.pointerId)return;e.preventDefault();const dx=e.clientX-origin.x,dy=e.clientY-origin.y;if(Math.hypot(dx,dy)>5)moved=true;selected.style.transform=`translate(${dx}px,${dy-8}px)`;host.querySelectorAll('.targetNear').forEach(t=>t.classList.remove('targetNear'));nearest(e.clientX,e.clientY)?.classList.add('targetNear');}
   function up(e){if(active!==e.pointerId)return;const t=nearest(e.clientX,e.clientY),wasMoved=moved;clear();if(wasMoved&&t)drop(t);suppressClick=wasMoved;}
   function cancel(){clear();suppressClick=true;}
   function click(e){if(suppressClick){suppressClick=false;return;}const p=e.target.closest(selector),t=e.target.closest(targetSelector);if(p&&!p.disabled){choose(p);return;}if(t)drop(t);}
   host.addEventListener('pointerdown',down);host.addEventListener('pointermove',move);host.addEventListener('pointerup',up);host.addEventListener('pointercancel',cancel);host.addEventListener('click',click);
   const cleanup=()=>{clear();host.removeEventListener('pointerdown',down);host.removeEventListener('pointermove',move);host.removeEventListener('pointerup',up);host.removeEventListener('pointercancel',cancel);host.removeEventListener('click',click);};Session.cleanup(cleanup);return cleanup;
 }
 global.LearningSpace={esc,names,object,label,scenery,shell,complete,drag,voice,burst};
})(window);
