(function(global){
 const B=global.LearningBank,C=global.SianCurriculum,esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 build100=subject=>C.curricula[subject]||C.curricula['수학'];
 stageQuestion=(subject,stage)=>C.question(subject,stage);
 openStageMap=function(subject){
  Session.begin();const stages=build100(subject),cur=state.stage100[subject]||1,zone=Math.floor((cur-1)/10),current=stages[cur-1];
  gameBody.innerHTML='<div class="stageMap"><div class="stageMapToolbar"><button class="mapClose">← 학습 월드</button><b>'+cur+' / 100</b></div><div class="stageMapIntro"><small>'+esc(subject)+' · '+esc(current.chapterName)+'</small><h2>'+esc(current.title)+'</h2><p>'+esc(current.learningObjective)+'</p><div class="conceptTags">'+current.conceptTags.map(x=>'<span>'+esc(x)+'</span>').join('')+'</div></div><div class="zoneTabs">'+B.CHAPTERS.map((name,z)=>'<button class="'+(z===zone?'on':'')+'" data-zone="'+z+'"><b>'+(z*10+1)+'–'+(z*10+10)+'</b><small>'+esc(name)+'</small></button>').join('')+'</div><div class="stageStory">📖 '+esc(current.story)+'</div><div class="stageNodes"></div></div>';
  const nodes=gameBody.querySelector('.stageNodes');function drawZone(z){nodes.innerHTML=stages.slice(z*10,z*10+10).map(s=>'<button class="stageNode '+(s.stage<cur?'clear':s.stage===cur?'current':'locked')+'" data-stage="'+s.stage+'" '+(s.stage>cur?'disabled':'')+'><i>'+(s.stage<cur?'★':s.stage)+'</i><b>'+esc(s.mode)+'</b><small>'+esc(s.questionType)+'</small></button>').join('');nodes.querySelectorAll('.stageNode:not(.locked)').forEach(b=>b.onclick=()=>playStage100(subject,+b.dataset.stage));}
  gameBody.querySelectorAll('[data-zone]').forEach(b=>b.onclick=()=>{gameBody.querySelectorAll('[data-zone]').forEach(x=>x.classList.remove('on'));b.classList.add('on');drawZone(+b.dataset.zone);});gameBody.querySelector('.mapClose').onclick=()=>game.close();drawZone(zone);game.showModal();
 };
 playStage100=function(subject,stage){
  Session.begin();if(subject==='코딩'){playCoding100(stage);return;}const info=build100(subject)[stage-1],q=stageQuestion(subject,stage);
  gameBody.innerHTML='<div class="storyStage"><div class="stageTop"><button class="backMap">← 지도</button><b>'+esc(subject)+' '+stage+'/100</b></div><div class="storyPanel"><small>CHAPTER '+info.chapter+' · '+esc(info.chapterName)+'</small><h2>'+esc(info.title)+'</h2><p>'+esc(info.learningObjective)+'</p><div class="conceptTags">'+info.conceptTags.map(x=>'<span>'+esc(x)+'</span>').join('')+'</div></div><div class="questCard"><div class="questionMeta"><span>'+esc(q.questionType)+'</span><span>난이도 '+q.difficulty+'</span></div>'+(q.visual?'<div class="questionVisual">'+esc(q.visual)+'</div>':'')+'<h3>'+esc(q.q)+'</h3><div class="choices">'+q.opts.map((x,i)=>'<button class="choice" data-index="'+i+'">'+esc(x)+'</button>').join('')+'</div><div class="feedback">천천히 생각하고 답을 골라 봐!</div><button class="hint">이야기와 문제 듣기</button></div></div>';
  gameBody.querySelector('.backMap').onclick=()=>openStageMap(subject);gameBody.querySelector('.hint').onclick=()=>say(info.story+' '+q.q,subject==='영어'?'en-US':'ko-KR');
  gameBody.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{const f=gameBody.querySelector('.feedback'),correct=+b.dataset.index===q.answerPosition;B.record(subject,correct);if(correct){b.classList.add('correctChoice');f.innerHTML='⭐ 성공! <small>'+esc(q.explanation)+'</small>';gameBody.querySelectorAll('.choice').forEach(x=>x.disabled=true);state.stage100[subject]=Math.max(state.stage100[subject]||1,Math.min(100,stage+1));award('learn:'+subject+':'+stage);const next=document.createElement('button');next.className='nextBtn';next.textContent=stage<100?'다음 미션 →':'지도로 돌아가기';next.onclick=()=>stage<100?playStage100(subject,stage+1):openStageMap(subject);f.append(next);}else{b.classList.add('wrongBrick');const struggling=B.data().performance[subject].wrongStreak>=2;f.innerHTML='한 번 더 생각해 보자.<small>'+(struggling?esc(q.explanation):'보기와 문제의 핵심 단어를 다시 살펴봐요.')+'</small>';Session.timeout(()=>b.classList.remove('wrongBrick'),300);}});
  game.showModal();
 };
})(window);
