(function(global){
 const B=global.LearningBank,C=global.SianCurriculum,esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 build100=subject=>C.curricula[subject]||C.curricula['수학'];
 stageQuestion=(subject,stage)=>C.question(subject,stage);
 openStageMap=function(subject){
  Session.begin();const stages=build100(subject),cur=state.stage100[subject]||1,zone=Math.floor((cur-1)/10),current=stages[cur-1];
  gameBody.innerHTML='<div class="stageMap"><div class="stageMapToolbar"><button class="mapClose">← 학습 월드</button><b>'+cur+' / 100</b></div><div class="stageMapIntro"><small>'+esc(subject)+' · '+esc(current.chapterName)+'</small><h2>'+esc(current.title)+'</h2><p>'+esc(current.learningObjective)+'</p><div class="conceptTags">'+current.conceptTags.map(x=>'<span>'+esc(x)+'</span>').join('')+'</div></div><div class="zoneTabs">'+B.CHAPTERS.map((name,z)=>'<button class="'+(z===zone?'on':'')+'" data-zone="'+z+'"><b>'+(z*10+1)+'–'+(z*10+10)+'</b><small>'+esc(name)+'</small></button>').join('')+'</div><div class="stageStory">📖 '+esc(current.story)+'</div><div class="stageNodes"></div></div>';
  const nodes=gameBody.querySelector('.stageNodes');function drawZone(z){nodes.innerHTML=stages.slice(z*10,z*10+10).map(s=>'<button class="stageNode '+(s.stage<cur?'clear':s.stage===cur?'current':'locked')+'" data-stage="'+s.stage+'" '+(s.stage>cur?'disabled':'')+'><i>'+(s.stage<cur?'★':s.stage)+'</i><b>'+esc(s.mode)+'</b><small>'+esc(['HANGUL_TRACING','HANJA_TRACING','ENGLISH_TRACING'].includes(s.questionType)?'따라쓰기':['MATH_MANIPULATIVE','PICTURE_DISCOVERY'].includes(s.questionType)?'그림 미션':'개념 탐험')+'</small></button>').join('');nodes.querySelectorAll('.stageNode:not(.locked)').forEach(b=>b.onclick=()=>playStage100(subject,+b.dataset.stage));}
  gameBody.querySelectorAll('[data-zone]').forEach(b=>b.onclick=()=>{gameBody.querySelectorAll('[data-zone]').forEach(x=>x.classList.remove('on'));b.classList.add('on');drawZone(+b.dataset.zone);});LearningHeader.mount(gameBody.querySelector('.stageMapToolbar'),subject,cur,()=>closeGame());drawZone(zone);game.showModal();
 };
 playStage100=function(subject,stage){
  Session.begin();if(['영어','과학'].includes(subject)&&global.DiscoverySpace){global.DiscoverySpace.play(subject,stage);return;}if(subject==='한자'&&global.HanjaSpace){global.HanjaSpace.play(stage);return;}if((subject==='수학'||subject==='사고력 수학'||(subject==='연산'&&stage<=30))&&global.MathSpace){global.MathSpace.play(subject,stage);return;}if(subject==='코딩'){playCoding100(stage);return;}const info=build100(subject)[stage-1],q0=stageQuestion(subject,stage),q=subject==='한글'&&!B.validateQuestion(q0).valid?stageQuestion(subject,stage):q0;
  gameBody.innerHTML='<div class="storyStage"><div class="stageTop"><button class="backMap">← 지도</button><b>'+esc(subject)+' '+stage+'/100</b></div><div class="storyPanel"><small>CHAPTER '+info.chapter+' · '+esc(info.chapterName)+'</small><h2>'+esc(info.title)+'</h2><p>'+esc(info.learningObjective)+'</p><div class="conceptTags">'+info.conceptTags.map(x=>'<span>'+esc(x)+'</span>').join('')+'</div></div><div class="questCard"><div class="questionMeta"><span>'+esc(q.questionType==='HANGUL_TRACING'?'한글 따라쓰기':q.questionType==='reading'?'이야기 읽기':'보고 고르기')+'</span><span>난이도 '+q.difficulty+'</span></div>'+(q.visual?'<div class="questionVisual">'+esc(q.visual)+'</div>':'')+'<h3>'+esc(q.q)+'</h3><div class="choices">'+q.opts.map((x,i)=>'<button class="choice" data-index="'+i+'">'+esc(x)+'</button>').join('')+'</div><div class="feedback">천천히 생각하고 답을 골라 봐!</div><button class="hint">이야기와 문제 듣기</button></div></div>';
  LearningHeader.mount(gameBody.querySelector('.stageTop'),subject,stage,()=>openStageMap(subject));const audioStatus=document.createElement('p');audioStatus.className='learningAudioStatus';audioStatus.setAttribute('aria-live','polite');gameBody.querySelector('.questCard').append(audioStatus);LearningSpeech.bind(gameBody.querySelector('.hint'),info.story+' '+q.q,audioStatus);window.SianAudio?.start(subject==='영어'?'memory':'learning');
  if(q.questionType==='HANGUL_TRACING'){const choices=gameBody.querySelector('.choices');choices.className='traceHost';Session.cleanup(HangulTrace.mount(choices,q,()=>{B.record(subject,true);state.stage100[subject]=Math.max(state.stage100[subject]||1,Math.min(100,stage+1));award('learn:'+subject+':'+stage);const f=gameBody.querySelector('.feedback');f.textContent='⭐ 잘 썼어!';const next=document.createElement('button');next.className='nextBtn';next.textContent='다음 미션 →';next.onclick=()=>stage<100?playStage100(subject,stage+1):openStageMap(subject);f.append(next);}));gameBody.querySelector('.feedback').textContent='시작점부터 천천히 따라 써 봐.';}
  gameBody.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{const f=gameBody.querySelector('.feedback'),correct=+b.dataset.index===q.answerPosition;B.record(subject,correct);if(correct){if(global.VoiceDirector)LearningSpeech.speak([VoiceDirector.respond('success',stage)]);b.classList.add('correctChoice');f.innerHTML='⭐ 성공! <small>'+esc(q.explanation)+'</small>';gameBody.querySelectorAll('.choice').forEach(x=>x.disabled=true);state.stage100[subject]=Math.max(state.stage100[subject]||1,Math.min(100,stage+1));award('learn:'+subject+':'+stage);const next=document.createElement('button');next.className='nextBtn';next.textContent=stage<100?'다음 미션 →':'지도로 돌아가기';next.onclick=()=>stage<100?playStage100(subject,stage+1):openStageMap(subject);f.append(next);}else{if(global.VoiceDirector)LearningSpeech.speak([VoiceDirector.respond('retry')]);b.classList.add('wrongBrick');const struggling=B.data().performance[subject].wrongStreak>=2;f.innerHTML='한 번 더 생각해 보자.<small>'+(struggling?esc(q.explanation):'보기와 문제의 핵심 단어를 다시 살펴봐요.')+'</small>';Session.timeout(()=>b.classList.remove('wrongBrick'),300);}});
  game.showModal();
 };
})(window);
