(function(H){
 const hit=H.overlaps,states={RUN:'RUN_STAGE',TRANSITION:'TRANSITION',INTRO:'BOSS_INTRO',BATTLE:'BOSS_STAGE',DEFEATED:'BOSS_DEFEATED',EXIT:'EXIT_OPEN'};
 H.BOSS_SCENES=states;
 H.prepareBoss=function(stage){if(stage.boss)stage.bossArena={theme:stage.theme,normalLength:stage.length,normalGoal:{...stage.goal}};return stage;};
 const floorFor=e=>e.stage.theme==='ocean'?430:420;
 function restorePlayer(e){const p=e.player,floor=floorFor(e);p.x=52;p.y=floor-p.h;p.velocityX=p.velocityY=0;p.gravity=1500;p.isGrounded=true;p.invincible=1.4;p.pose='idle';}
 function spawnQuestion(e){const b=e.boss,q=e.stage.boss.questions[b.question%b.maxHp],answer=q[1],choices=q.slice(1,4).map((text,i)=>({text,correct:i===0}));for(let i=choices.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[choices[i],choices[j]]=[choices[j],choices[i]];}b.prompt=q[0];b.choices=choices.map((choice,i)=>({id:`boss-choice-${b.question}-${i}`,...choice,x:118,y:175+i*74,w:66,h:66}));}
 H.beginBossTransition=function(e){if(e.sceneState!==states.RUN)return;e.sceneState=states.TRANSITION;e.sceneTimer=2.45;e.player.velocityX=e.player.velocityY=0;e.emit('bossTransition',{name:e.stage.boss.name});};
 H.enterBossArena=function(e){
  if(!e._normalStage)e._normalStage={platforms:e.stage.platforms,enemies:e.stage.enemies,hazards:e.stage.hazards,items:e.stage.items,checkpoints:e.stage.checkpoints,goal:e.stage.goal,length:e.stage.length};e._normalLetterCount=e.stage.words.length;
  const width=Math.max(640,e.viewport),floor=floorFor(e);e.stage.length=width;e.stage.platforms=[{x:0,y:floor,w:width,h:220,kind:'arena'}];e.stage.enemies=[];e.stage.hazards=[];e.stage.items=[];e.stage.checkpoints=[{x:52,y:floor,id:0}];e.stage.goal={x:width-78,y:floor-142,w:64,h:142};e.checkpoint=e.stage.checkpoints[0];e.cameraX=0;e.projectiles=[];e.bossAttacks=[];e.sceneState=states.INTRO;e.sceneTimer=2.2;restorePlayer(e);
  e.boss={name:e.stage.boss.name,hp:e.stage.boss.questions.length,maxHp:e.stage.boss.questions.length,question:0,prompt:'',choices:[],x:Math.min(width-205,width*.72),y:floor-174,w:150,h:174,phase:1,state:'enter',timer:1.2,pattern:-1,hitTime:0,defeatTime:0,unlocked:false,energy:0};e.emit('bossArena',{name:e.boss.name});
 };
 function startPattern(e){const b=e.boss,patterns=['charge','projectile','slam','shockwave'];b.pattern=(b.pattern+1)%patterns.length;b.attack=patterns[b.pattern];b.state='telegraph';b.timer=b.phase===3?.58:.78;e.emit('bossTelegraph',{pattern:b.attack});}
 function launchPattern(e){const b=e.boss;b.state='attack';e.emit('bossAttack',{pattern:b.attack});if(b.attack==='charge'){b.timer=.9;b.chargeDirection=e.player.x<b.x?-1:1;}if(b.attack==='projectile'){b.timer=.85;e.bossAttacks.push({kind:'orb',x:b.x,y:b.y+65,w:32,h:32,vx:-190-35*b.phase,vy:0,life:4});}if(b.attack==='slam'){b.timer=1.05;b.startY=b.y;b.slamX=Math.max(e.viewport*.55,Math.min(e.stage.length-210,e.player.x-45));}if(b.attack==='shockwave'){b.timer=.8;e.bossAttacks.push({kind:'wave',x:b.x-15,y:floorFor(e)-34,w:42,h:34,vx:-225-25*b.phase,vy:0,life:4});}}
 function tickAttacks(e,dt){const p=e.player;e.bossAttacks=e.bossAttacks.filter(a=>{a.x+=a.vx*dt;a.y+=a.vy*dt;a.life-=dt;if(hit(p,a)){e.damage();e.emit('bossAttackHit',{pattern:a.kind});return false;}return a.life>0&&a.x>-80&&a.x<e.stage.length+80;});e.projectiles=e.projectiles.filter(q=>{q.x+=q.vx*dt;q.y+=q.vy*dt;q.life-=dt;if(q.team==='player'&&hit(q,e.boss)){const b=e.boss;b.hp=Math.max(0,b.hp-1);b.hitTime=.48;e.burst(b.x+b.w/2,b.y+b.h/2);e.emit('bossHit',{damage:1,hp:b.hp});if(b.hp===0){b.state='defeat';b.defeatTime=2;e.sceneState=states.DEFEATED;e.sceneTimer=2;e.bossAttacks=[];e.emit('bossDefeat',{name:b.name});}else{b.question++;b.energy=.75;b.choices=[];}return false;}return q.life>0;});}
 function tickChoices(e,dt){const b=e.boss;b.energy=Math.max(0,b.energy-dt);e.answerCooldown=Math.max(0,e.answerCooldown-dt);if(!b.choices.length&&b.energy<=0&&b.hp>0)spawnQuestion(e);if(e.answerCooldown>0)return;for(const q of b.choices){if(!hit(e.player,q))continue;if(q.correct){e.projectiles.push({team:'player',kind:'starlight',x:e.player.x+e.player.w,y:e.player.y+20,w:30,h:22,vx:360,vy:(b.y+65-e.player.y)*.35,life:3});b.choices=[];b.energy=1;e.answerCooldown=1.1;e.player.x=Math.max(45,e.player.x-82);e.player.pose='power-up';e.player.poseTime=.45;e.emit('bossAnswer',{text:q.text});}else{b.choices=[];b.energy=1;e.answerCooldown=1.1;e.player.x=Math.max(45,e.player.x-82);e.damage();e.emit('wrong',{item:q});}break;}}
 function tickBossAI(e,dt){const b=e.boss,p=e.player,floor=floorFor(e);b.phase=b.hp/b.maxHp>.6?1:b.hp/b.maxHp>.3?2:3;b.hitTime=Math.max(0,b.hitTime-dt);b.timer-=dt;if(b.state==='idle'&&b.timer<=0)startPattern(e);else if(b.state==='telegraph'&&b.timer<=0)launchPattern(e);else if(b.state==='attack'){if(b.attack==='charge'){b.x+=b.chargeDirection*(250+35*b.phase)*dt;b.x=Math.max(e.viewport*.45,Math.min(e.stage.length-b.w-76,b.x));if(hit(p,b))e.damage();}if(b.attack==='slam'){const progress=1-Math.max(0,b.timer)/1.05;b.x+=(b.slamX-b.x)*Math.min(1,dt*4);b.y=b.startY-Math.sin(Math.min(1,progress)*Math.PI)*145;if(b.timer<=.18&&b.y<floor-b.h+4){b.y=floor-b.h;e.bossAttacks.push({kind:'wave',x:b.x-8,y:floor-32,w:42,h:32,vx:-250,vy:0,life:3});e.bossAttacks.push({kind:'wave',x:b.x+b.w-28,y:floor-32,w:42,h:32,vx:250,vy:0,life:3});}}if(b.timer<=0){b.y=floor-b.h;b.state='idle';b.timer=Math.max(.9,1.65-b.phase*.18);}}}
 H.tickBossScene=function(e,dt){const S=states,p=e.player;if(e.sceneState===S.RUN){if(e.letterCount===e.stage.words.length)H.beginBossTransition(e);return;}if(e.sceneState===S.TRANSITION){e.sceneTimer-=dt;p.velocityX=p.velocityY=0;if(e.sceneTimer<=0)H.enterBossArena(e);return;}p.x=Math.max(22,Math.min(e.stage.length-p.w-20,p.x));if(e.sceneState===S.INTRO){e.sceneTimer-=dt;p.velocityX=0;if(e.sceneTimer<=0){e.sceneState=S.BATTLE;e.boss.state='idle';e.boss.timer=.8;spawnQuestion(e);e.emit('bossStart',{name:e.boss.name});}return;}if(e.sceneState===S.BATTLE){tickChoices(e,dt);tickBossAI(e,dt);tickAttacks(e,dt);return;}if(e.sceneState===S.DEFEATED){e.sceneTimer-=dt;e.boss.defeatTime=Math.max(0,e.sceneTimer);if(e.sceneTimer<=0){e.sceneState=S.EXIT;e.boss.unlocked=true;e.boss.state='gone';e.emit('doorUnlock');}return;}if(e.sceneState===S.EXIT){e.bossAttacks=[];e.projectiles=[];}};
})(HangulRunner);
