(function(HR){
  const BASE='assets/hangul-runner/';
  function load(src){return new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=()=>reject(new Error('모험 그림을 불러오지 못했어요.'));i.src=BASE+src;});}
  // Crop only at rendering time; the original generated atlas remains unaltered.
  function crop(image,r,feet=false){const [x,y,w,h]=r.map(n=>Math.round(n*image.width/1254));const c=document.createElement('canvas');c.width=w;c.height=h;const g=c.getContext('2d',{willReadFrequently:true});g.drawImage(image,x,y,w,h,0,0,w,h);
    const d=g.getImageData(0,0,w,h).data;let l=w,t=h,rr=0,b=0;for(let yy=0;yy<h;yy++)for(let xx=0;xx<w;xx++)if(d[(yy*w+xx)*4+3]>45){l=Math.min(l,xx);t=Math.min(t,yy);rr=Math.max(rr,xx);b=Math.max(b,yy);}
    let sole=b+1;
    if(feet){for(let yy=b;yy>=t;yy--){let solid=0;for(let xx=l;xx<=rr;xx++)if(d[(yy*w+xx)*4+3]>200)solid++;if(solid>=Math.max(5,(rr-l)*.06)){sole=yy+1;break;}}}
    return {image:c,x:l,y:t,w:rr-l+1,h:b-t+1,sole:sole-t};}
  HR.loadArt=async()=>{
    const [character,objects,scenery,bossAtlas,enemyAtlas,oceanAtlas,marineAtlas]=await Promise.all(['character.webp','objects.webp','scenery.webp','bosses-v2.png','enemies-v2.png','ocean-props.webp','marine-hunters.webp'].map(load));
    const frames=Array.from({length:16},(_,i)=>crop(character,[i%4*313.5,Math.floor(i/4)*313.5,313.5,313.5],true));
    const rects=[[0,70,387,295],[387,110,251,255],[640,130,305,230],[945,0,309,375],
      [0,378,312,267],[313,370,312,274],[628,377,307,268],[937,400,317,245],
      [0,648,313,287],[316,665,304,270],[630,665,299,266],[937,638,317,302],
      [0,949,312,290],[315,957,311,282],[630,963,300,260],[936,942,318,297]];
    const sprites=rects.map(r=>crop(objects,r));
    const back=[crop(scenery,[0,0,700,584]),crop(scenery,[704,0,550,650]),crop(scenery,[0,602,595,645]),crop(scenery,[600,807,654,433])];
    const grid=(img,cols,rows)=>Array.from({length:cols*rows},(_,i)=>crop(img,[i%cols*1254/cols,Math.floor(i/cols)*img.height/img.width*1254/rows,1254/cols,img.height/img.width*1254/rows]));
    const oceanRects=Array.from({length:12},(_,i)=>[i%4*362,Math.floor(i/4)===0?0:Math.floor(i/4)===1?380:730,362,Math.floor(i/4)===0?380:Math.floor(i/4)===1?350:356]);oceanRects[10]=[715,730,445,326];oceanRects[11]=[1080,850,188,167];oceanRects.push([1190,780,258,175]);const ocean=oceanRects.map(r=>crop(oceanAtlas,r.map(n=>n*1254/1448)));
    return {frames,sprites,back,ocean,marine:grid(marineAtlas,2,1),bosses:grid(bossAtlas,3,3),enemies:grid(enemyAtlas,4,3)};
  };
  function draw(g,s,x,y,w,h,flip=false){if(!s||s.w<=0)return;g.save();if(flip){g.translate(x+w,y);g.scale(-1,1);x=0;y=0;}g.drawImage(s.image,s.x,s.y,s.w,s.h,x,y,w,h);g.restore();}
  HR.Renderer=class {
    constructor(canvas,art){this.canvas=canvas;this.g=canvas.getContext('2d',{alpha:false});this.art=art;this.width=960;this.height=540;this.dpr=1;}
    resize(width){this.width=width<620?640:960;this.height=540;this.dpr=Math.min(2,window.devicePixelRatio||1);this.canvas.width=this.width*this.dpr;this.canvas.height=this.height*this.dpr;}
    sprite(i,x,y,w,h,flip){draw(this.g,this.art.sprites[i],x,y,w,h,flip);}
    starlight(q,camera=0){const g=this.g,cx=q.x-camera+q.w/2,cy=q.y+q.h/2,dx=q.direction?.x??Math.sign(q.vx),dy=q.direction?.y??Math.sign(q.vy),final=q.kind==='final-starlight',radius=final?19:12;g.save();g.shadowColor=final?'#fff36a':'#7df4ff';g.shadowBlur=final?38:24;const trail=g.createLinearGradient(cx-dx*48,cy-dy*48,cx,cy);trail.addColorStop(0,'#8eeaff00');trail.addColorStop(1,'#fff4aacc');g.strokeStyle=trail;g.lineWidth=final?11:7;g.lineCap='round';g.beginPath();g.moveTo(cx-dx*(final?48:34),cy-dy*(final?48:34));g.lineTo(cx-dx*7,cy-dy*7);g.stroke();g.translate(cx,cy);g.rotate(Math.atan2(dy,dx)+Math.PI/2);g.fillStyle='#fffbd0';g.strokeStyle=final?'#ffbf36':'#58dcff';g.lineWidth=3;g.beginPath();for(let i=0;i<10;i++){const r=i%2?radius*.44:radius,a=-Math.PI/2+i*Math.PI/5;g.lineTo(Math.cos(a)*r,Math.sin(a)*r);}g.closePath();g.fill();g.stroke();g.fillStyle='#fff';for(let i=0;i<3;i++){const back=18+i*11;g.globalAlpha=.8-i*.2;g.beginPath();g.arc(-dy*(i-1)*5-dx*back,dx*(i-1)*5-dy*back,2.8-i*.5,0,Math.PI*2);g.fill();}g.restore();}
    hero(e,camera=0){const g=this.g,p=e.player,t=e.elapsed;let frame={idle:8,jump:9,fall:10,land:11,hurt:12,'power-up':13,small:12,dead:14,celebrate:15}[p.pose];if(p.pose==='run')frame=Math.floor(t*12)%8;
      if(p.flightTime>0){g.save();g.strokeStyle='#fff4b0';g.shadowColor='#7aeeff';g.shadowBlur=16;g.lineWidth=5;const cx=p.x-camera+p.w/2,cy=p.y+p.h*.45;for(const dir of [-1,1]){g.beginPath();g.moveTo(cx,cy+8);g.quadraticCurveTo(cx+dir*45,cy-30-Math.sin(t*12)*8,cx+dir*32,cy+15);g.stroke();}g.restore();}
      if(e.mode==='swim'&&e.status==='playing'&&e.poseTime<=0)frame=p.swimPose==='idle'?8:[2,5,6,1][Math.floor(t*3.2)%4];
      const s=this.art.frames[frame??8],growth=p.growthTime?(p.growthFrom+(p.h-p.growthFrom)*(1-Math.pow(p.growthTime/.6,2))):p.h,r=HR.playerRenderBounds(p,s,growth*(p.pose==='land'?.92:1));
      if(p.powerState==='star_power'&&e.status==='playing'){const cx=p.x-camera+p.w/2,cy=p.y+p.h*.48;g.save();g.strokeStyle='#fff078';g.shadowColor='#7deaff';g.shadowBlur=18;g.globalAlpha=.55+.12*Math.sin(t*5);g.lineWidth=3;g.beginPath();g.ellipse(cx,cy,p.w*.82,p.h*.6,0,0,Math.PI*2);g.stroke();g.fillStyle='#fff7a2';for(let i=0;i<5;i++){const a=t*(.7+i*.08)+i*Math.PI*2/5,x=cx+Math.cos(a)*(p.w*.8+5),y=cy+Math.sin(a)*(p.h*.48);g.beginPath();g.arc(x,y,2+i%2,0,Math.PI*2);g.fill();}g.restore();}
      if(p.invincible<=0||Math.floor(t*13)%2===0||e.status==='dead'){g.save();if(e.mode==='swim'){g.shadowColor='#eeffff';g.shadowBlur=7;}if(p.powerState==='big'){g.shadowColor='#ffe26c';g.shadowBlur=16;}if(p.powerState==='star_power'){g.shadowColor='#7deaff';g.shadowBlur=20;}if(e.mode==='swim'&&!p.isGrounded&&e.status==='playing'){const cx=p.x-camera+p.w/2,cy=p.y+p.h/2,tilt=p.facing*(Math.abs(p.velocityX)>30?.95:0)+(p.velocityY>35?p.facing*.3:p.velocityY< -35?-p.facing*.2:0);g.translate(cx,cy);g.rotate(tilt);draw(g,s,r.x-camera-cx,r.y-cy+Math.sin(t*2)*1.5,r.w,r.h,p.facing<0);}else draw(g,s,r.x-camera,r.y,r.w,r.h,p.facing<0);g.restore();}}
    surfaceSprite(i,x,surface,w,h,anchor){const s=this.art.sprites[i],offset=(anchor*s.image.width/([387,251,305][i])-s.y)/s.h*h;this.sprite(i,x,surface-offset,w,h);}
    enemy(a,x,t){if(['shark','eel'].includes(a.marineKind)){this.oceanMarine(a,x,t);return;}const g=this.g,byKind={'berry-bandit':0,'seed-shell':1,cactus:2,'fire-imp':3,'bubble-puffer':4,'reef-crab':5,'ink-sprite':6,'cloud-rascal':7,'storm-bat':7,'spark-drake':7,'tunnel-bat':8,'gear-shell':1};
      let index=a.artIndex??byKind[a.kind]??0;
      const sprite=this.art.enemies[index];g.save();g.globalAlpha=a.fade??1;if(a.telegraph){g.shadowColor='#ffbc5c';g.shadowBlur=22;}
      if(a.kind==='cactus'){const floor=a.drainY;g.fillStyle='#364b64';g.strokeStyle=a.warning?'#ffce58':'#94bfc8';g.lineWidth=4;g.beginPath();g.roundRect(x-8,floor-8,a.w+16,24,8);g.fill();g.stroke();if(a.retracted){g.restore();return;}}
      const height=a.h*(a.defeated?.35:a.state==='shell'?.65:1),width=height*sprite.w/sprite.h;
      g.translate(x+a.w/2,a.y+a.h);if(a.state==='rolling')g.rotate(t*12*a.dir);if(a.hitTime>0){g.shadowBlur=18;g.shadowColor='#fff';a.hitTime=Math.max(0,a.hitTime-.016);}
      draw(g,sprite,-width/2,-height+Math.sin(t*8+(a.phase||0))*2,width,height,a.dir>0);g.restore();
    }
    transition(e){const g=this.g,w=this.width,h=this.height,t=e.elapsed;g.setTransform(this.dpr,0,0,this.dpr,0,0);const bg=g.createRadialGradient(w/2,h*.55,20,w/2,h*.55,w*.7);bg.addColorStop(0,'#64241d');bg.addColorStop(.48,'#250f1c');bg.addColorStop(1,'#05050b');g.fillStyle=bg;g.fillRect(0,0,w,h);g.fillStyle='#ff6725';for(let i=0;i<18;i++){const x=(i*97+t*33)%w,y=h-30-(i*47+t*24)%120;g.globalAlpha=.25+(i%4)*.12;g.beginPath();g.arc(x,y,3+i%5,0,Math.PI*2);g.fill();}g.globalAlpha=1;g.fillStyle='#fff0c7';g.textAlign='center';g.font='900 30px Pretendard, sans-serif';g.fillText('모든 글자를 모았어!',w/2,205);g.fillStyle='#ffbf68';g.font='800 22px Pretendard, sans-serif';g.fillText(`${e.stage.boss.name}가 기다리는 보스 성으로 이동합니다`,w/2,250);g.fillStyle='#fff';g.globalAlpha=.8;g.font='700 15px Pretendard, sans-serif';g.fillText('BOSS STAGE  ·  LOADING'+'.'.repeat(1+Math.floor(t*2)%3),w/2,305);g.globalAlpha=1;}
    arena(e){const g=this.g,w=this.width,h=this.height,t=e.elapsed,theme=e.stage.theme,b=e.boss,floor=theme==='ocean'?430:420;g.setTransform(this.dpr,0,0,this.dpr,0,0);const palette={forest:['#120b18','#531b1b','#ff6a24'],ocean:['#021b38','#083c5f','#42d7e8'],sky:['#17122f','#403a82','#c6e4ff'],underground:['#070b18','#26254d','#91ffe2'],dinosaur:['#18332a','#4e703e','#d9b46c'],ice:['#143e62','#35748b','#b7f8ff'],fire:['#3e1321','#813025','#ffb239'],lightning:['#201645','#4d3d7b','#f5e365'],space:['#090b25','#372154','#bd86ff']}[theme]||['#120b18','#531b1b','#ff6a24'];const bg=g.createLinearGradient(0,0,0,h);bg.addColorStop(0,palette[0]);bg.addColorStop(.7,palette[1]);bg.addColorStop(1,'#05060b');g.fillStyle=bg;g.fillRect(0,0,w,h);
      if(theme==='ocean'&&this.oceanBackground)this.oceanBackground(e);
      g.fillStyle=palette[2]+'22';for(let i=0;i<8;i++){const x=i*w/7;g.fillRect(x-14,88,28,floor-88);g.beginPath();g.arc(x,88,44,Math.PI,0);g.fill();}g.strokeStyle='#ffffff18';g.lineWidth=4;for(let y=126;y<floor;y+=48){g.beginPath();g.moveTo(0,y);g.lineTo(w,y);g.stroke();}
      if(theme==='forest'){g.fillStyle='#ff5a19';g.fillRect(0,floor+20,w,h-floor);for(let x=-20;x<w+30;x+=42){g.beginPath();g.moveTo(x,floor+24);g.quadraticCurveTo(x+18,floor-2+Math.sin(t*5+x)*8,x+38,floor+24);g.fill();}}
      else {g.fillStyle=palette[2]+'55';g.fillRect(0,floor+18,w,h-floor);}
      const stone=g.createLinearGradient(0,floor-22,0,floor+34);stone.addColorStop(0,'#a88c78');stone.addColorStop(.18,'#55475c');stone.addColorStop(1,'#211d2c');g.fillStyle=stone;g.fillRect(0,floor,w,42);g.strokeStyle='#17131e';g.lineWidth=3;for(let x=0;x<w;x+=48)g.strokeRect(x,floor,48,42);
      const locked=e.sceneState!=='EXIT_OPEN',gx=e.stage.goal.x;g.save();g.translate(gx+32,floor-71);g.shadowColor=locked?'#ff3f35':'#fff4a8';g.shadowBlur=locked?14:38;g.fillStyle=locked?'#251828':'#fff4c4';g.strokeStyle=locked?'#ff5b46':'#ffc64f';g.lineWidth=6;g.beginPath();g.roundRect(-33,-70,66,140,26);g.fill();g.stroke();g.fillStyle=locked?'#ef513d':'#8e5b1f';g.font='900 28px Pretendard';g.textAlign='center';g.fillText(locked?'🔒':'✦',0,10);g.restore();
      for(const q of b?.choices||[]){const pulse=1+Math.sin(t*5+q.x)*.05;g.save();g.translate(q.x+q.w/2,q.y+q.h/2);g.scale(pulse,pulse);g.rotate(Math.sin(t*2+q.x)*.025);g.shadowColor='#7deeff';g.shadowBlur=24;const rune=g.createRadialGradient(-8,-10,4,0,0,34);rune.addColorStop(0,'#fffbe0');rune.addColorStop(.55,'#8af4ff');rune.addColorStop(1,'#7064dc');g.fillStyle=rune;g.strokeStyle='#fff4a8';g.lineWidth=4;g.beginPath();for(let i=0;i<12;i++){const r=i%2?27:34,a=-Math.PI/2+i*Math.PI/6;g.lineTo(Math.cos(a)*r,Math.sin(a)*r);}g.closePath();g.fill();g.stroke();g.strokeStyle='#ffffff88';g.lineWidth=2;g.beginPath();g.arc(0,0,23,0,Math.PI*2);g.stroke();g.fillStyle='#30245f';g.font=`900 ${q.text.length>2?15:27}px Pretendard`;g.textAlign='center';g.textBaseline='middle';g.fillText(q.text,0,1);g.restore();}
      for(const a of e.bossAttacks||[]){g.save();g.shadowColor='#ff3f1f';g.shadowBlur=22;g.fillStyle=a.kind==='wave'?'#ff9a31':'#ff492d';g.beginPath();a.kind==='wave'?g.ellipse(a.x+a.w/2,a.y+a.h/2,a.w*.7,a.h*.45,0,0,Math.PI*2):g.arc(a.x+16,a.y+16,16,0,Math.PI*2);g.fill();g.restore();}
      for(const q of e.projectiles||[])this.starlight(q,0);
      if(b&&b.state!=='gone'){const sprite=this.art.bosses[(e.stage.worldId||1)-1],def=e.sceneState==='BOSS_DEFEATED',hit=b.hitTime>0;
        g.save();g.translate(b.x+b.w/2+(hit?Math.sin(t*55)*7:0),b.y+b.h);if(def){g.rotate((1-b.defeatTime/2)*-.65);g.globalAlpha=Math.max(.1,b.defeatTime/2);}
        g.shadowColor=hit?'#fff':b.state==='telegraph'?'#ff6048':palette[2];g.shadowBlur=hit?42:b.state==='telegraph'?28:12;
        const bh=b.h*1.24,bw=bh*sprite.w/sprite.h;draw(g,sprite,-bw/2,-bh+Math.sin(t*3)*3,bw,bh);
        if(b.phase===3||b.shieldTime>0){g.strokeStyle=b.shieldTime>0?'#8ff8ff':'#ffce5f';g.globalAlpha=b.shieldTime>0?.9:1;g.lineWidth=b.shieldTime>0?7:3;g.beginPath();g.ellipse(0,-b.h*.4,b.w*(b.shieldTime>0?.78:.65),b.h*(b.shieldTime>0?.74:.65),0,0,Math.PI*2);g.stroke();}g.restore();}
      this.hero(e,0);if(theme==='ocean'&&this.oceanLight)this.oceanLight(e,.025);for(const v of e.particles){g.globalAlpha=Math.min(1,v.life*2);this.sprite(11,v.x-5,v.y-5,12,12);}g.globalAlpha=1;
      if(b){g.fillStyle='#180e18cc';g.beginPath();g.roundRect(w*.18,18,w*.64,72,18);g.fill();g.fillStyle='#fff';g.textAlign='center';g.font='900 17px Pretendard';g.fillText(b.name,w/2,43);g.fillStyle='#3a2632';g.fillRect(w*.25,54,w*.5,18);g.fillStyle=b.phase===3?'#ff362d':'#ff674f';g.fillRect(w*.25+3,57,(w*.5-6)*(b.hp/b.maxHp),12);if(e.sceneState==='BOSS_STAGE'&&b.state==='choice'){g.fillStyle='#fff4c4';g.font='900 20px Pretendard';g.fillText(b.prompt,w/2,118);g.fillStyle='#8ff8ff';g.font='800 14px Pretendard';g.fillText(`별빛 글자를 골라요 · ${Math.max(1,Math.ceil(b.choiceTime))}초`,w/2,141);}if(e.sceneState==='BOSS_STAGE'&&b.wrongTime>0){g.fillStyle='#ffb06b';g.font='900 22px Pretendard';g.fillText('× 다시 찾아보자!',w/2,174);}if(e.sceneState==='BOSS_INTRO'){g.fillStyle='#fff';g.font='900 32px Pretendard';g.fillText('BOSS BATTLE',w/2,150);}if(e.sceneState==='BOSS_DEFEATED'){g.fillStyle='#fff0a0';g.font='900 30px Pretendard';g.fillText('보스를 물리쳤어!',w/2,155);}if(e.sceneState==='EXIT_OPEN'){g.fillStyle='#fff0a0';g.font='900 24px Pretendard';g.fillText('문이 열렸어! 직접 문으로 이동해요',w/2,145);}if(b.state==='telegraph'){g.fillStyle='#ffb56b';g.font='800 17px Pretendard';g.fillText({charge:'돌진을 피해요!',projectile:'에너지 탄을 피해요!',slam:'위험 표시에서 벗어나요!',shockwave:'충격파를 뛰어넘어요!'}[b.attack],w/2,h-30);}}
    }
    paint(e){if(e.sceneState==='TRANSITION'){this.transition(e);return;}if(['BOSS_INTRO','BOSS_STAGE','BOSS_DEFEATED','EXIT_OPEN'].includes(e.sceneState)){this.arena(e);return;}const g=this.g,w=this.width,h=this.height,c=e.cameraX,t=e.elapsed,theme=e.stage.theme||'forest';g.setTransform(this.dpr,0,0,this.dpr,0,0);
      const palettes={forest:['#68c6f7','#b5e7f5','#ecf9fa'],ocean:['#075f9d','#13a9bd','#063c72'],sky:['#7999f4','#d6c2ff','#fff0d0'],underground:['#241c3a','#493052','#141d2c'],dinosaur:['#6ac6ad','#bbdda0','#527e46'],ice:['#7fbfe0','#dcf8ff','#9cbfe4'],fire:['#773342','#f19c57','#a84638'],lightning:['#292c65','#7977b9','#bbc2ee'],space:['#0b1237','#32295d','#533d7d']},colors=palettes[theme]||palettes.forest;
      const sky=g.createLinearGradient(0,0,0,h);sky.addColorStop(0,colors[0]);sky.addColorStop(.62,colors[1]);sky.addColorStop(1,colors[2]);g.fillStyle=sky;g.fillRect(0,0,w,h);
      if(theme==='ocean'&&this.oceanBackground)this.oceanBackground(e);
      if(theme==='sky'){for(let i=-1;i<6;i++){const x=i*210-(c*.1+t*12)%210;g.fillStyle='#fff9';g.beginPath();g.ellipse(x,95+(i%3)*85,95,30,0,0,Math.PI*2);g.fill();}}
      if(theme==='underground'){g.fillStyle='#89ffd555';for(let i=0;i<12;i++){g.beginPath();g.arc((i*127-c*.2)%1050,90+(i%5)*90,4+i%3*2,0,Math.PI*2);g.fill();}}
      if(['dinosaur','ice','fire','lightning','space'].includes(theme)){g.save();for(let i=-1;i<9;i++){const x=i*180-(c*.16)%180;
        if(theme==='space'){g.fillStyle='#fff9';g.beginPath();g.arc(x+70,55+(i+1)*37%230,3,0,Math.PI*2);g.fill();g.fillStyle='#9782bf';g.beginPath();g.ellipse(x,225,30,22,.4,0,Math.PI*2);g.fill();}
        else {g.fillStyle=theme==='ice'?'#efffff99':theme==='fire'?'#532b3e99':theme==='lightning'?'#32365788':'#32765788';g.beginPath();g.moveTo(x-100,420);g.lineTo(x+40,120+(i%3)*45);g.lineTo(x+170,420);g.fill();}
        if(theme==='lightning'&&Math.floor(t*2)%7===0){g.strokeStyle='#fff6b4';g.lineWidth=4;g.beginPath();g.moveTo(x,65);g.lineTo(x-18,105);g.lineTo(x+8,100);g.lineTo(x-12,145);g.stroke();}
      }g.restore();}
      // Independent layers, camera ratios: cloud .06, mountain .13, castle .21,
      // waterfall .34, forest .53, platform 1, foreground 1.12.
      if(theme==='forest'){for(let i=-1;i<5;i++){const x=i*420-(c*.06+t*4)%420;this.sprite(13,x,35+(i%2)*55,185,92);}
      for(let i=-1;i<4;i++)draw(g,this.art.back[0],i*760-(c*.13)%760,75,850,470);
      draw(g,this.art.back[1],560-(c*.21)%1500,65,245,294);
      for(let i=-1;i<4;i++){let x=i*680-(c*.34)%680;draw(g,this.art.back[2],x,170,320,410);
        // Subtle moving highlights give waterfalls a continuous flow.
        g.save();g.globalAlpha=.15;g.fillStyle='#fff';for(let k=0;k<6;k++)g.fillRect(x+125+k*12,280+(t*100+k*29)%210,3,26);g.restore();}
      for(let i=-1;i<5;i++)draw(g,this.art.back[3],i*460-(c*.53)%460,242,520,287);}
      for(const a of e.stage.platforms){const x=a.x-c;if(x+a.w<-40||x>w+40)continue;
        if(theme==='ocean'&&this.oceanTerrain){this.oceanTerrain(a,x,e);}else if(a.kind==='drain'){g.fillStyle=theme==='forest'?'#79634d':theme==='underground'?'#706581':'#4d8292';g.strokeStyle='#c5e3d6';g.lineWidth=3;g.beginPath();g.roundRect(x,a.y,a.w,a.h+12,6);g.fill();g.stroke();g.fillStyle='#22373d';g.fillRect(x+6,a.y+2,a.w-12,5);}else if(theme!=='forest'){const ground={ocean:'#a2bfa5',sky:'#e7e7ff',underground:'#786c99',dinosaur:'#8aaa58',ice:'#d6f7ff',fire:'#914940',lightning:'#868ba7',space:'#6b6193'}[theme]||'#8aaa58';g.fillStyle=ground;g.fillRect(x,a.y,a.w,Math.min(a.h,120));g.fillStyle='#ffffff66';g.fillRect(x,a.y,a.w,7);g.fillStyle='#00000022';for(let j=0;j<a.w;j+=50)g.fillRect(x+j,a.y+12,3,Math.min(a.h,90));}else if(a.kind==='ground'){
          // Texture tiles meet exactly at collider tops; split terrain leaves real holes.
          const n=Math.ceil(a.w/260);for(let j=0;j<n;j++){const tw=a.w/n;this.surfaceSprite(0,x+j*tw-1,a.y,tw+2,a.h,45);}
          // Keep the illustrated grass edge only; do not overlay a flat green stripe across the terrain.
          g.fillStyle='#abd765';for(let blade=0;blade<a.w;blade+=13){g.beginPath();g.moveTo(x+blade,a.y);g.lineTo(x+blade+3,a.y-3);g.lineTo(x+blade+5,a.y);g.fill();}
          if(Math.floor(a.x/620)%2===0){this.sprite(3,x+25,a.y-182,148,192);this.sprite(14,x+165,a.y-35,73,44);}
        }else if(a.kind==='bridge'){this.surfaceSprite(2,x-5,a.y,a.w+10,73,155);}
        else this.surfaceSprite(1,x-3,a.y,a.w+6,66,55);
      }
      for(const cp of e.stage.checkpoints){if(cp.id===0)continue;const x=cp.x-c;if(x<-70||x>w+70)continue;
        this.sprite(15,x-20,346,62,77);g.fillStyle=cp.id<=e.checkpoint.id?'#076b79':'#fff';g.font='bold 12px Pretendard, sans-serif';g.textAlign='center';g.fillText('쉼터 '+cp.id,x+10,333);}
      for(const a of e.stage.hazards){const x=a.x-c;if(x<-80||x>w+80)continue;if(a.kind==='lava'||a.kind==='electric'){g.fillStyle=a.inactive?'#7f7186':a.kind==='lava'?'#ff7848':'#fff268';g.fillRect(x,a.y,a.w,a.h);continue;}const i={thorn:8,rock:6,log:7,crate:9}[a.kind];this.sprite(i,x-10,a.y-16,a.w+20,a.h+20);}
      for(const b of e.stage.blocks||[]){if(b.removed)continue;const x=b.x-c;if(x+b.w<-60||x>w+60||b.hidden&&!b.revealed)continue;if(theme==='ocean'&&this.oceanBlock){this.oceanBlock(b,x,t);continue;}const lift=b.bump?Math.sin((.22-b.bump)/.22*Math.PI)*9:0;g.save();g.translate(0,-lift);g.shadowColor='#32243c66';g.shadowBlur=8;g.fillStyle=b.kind==='reward'?(b.used?'#8e806f':'#ffd45e'):b.kind==='breakable'?'#c86f45':'#526579';g.strokeStyle=b.kind==='reward'?'#fff1a2':'#d8e4e8';g.lineWidth=3;g.beginPath();g.roundRect(x,b.y,b.w,b.h,8);g.fill();g.stroke();g.shadowBlur=0;if(b.kind==='reward'&&!b.used){g.fillStyle='#fff8c7';g.font='900 25px Pretendard';g.textAlign='center';g.fillText('✦',x+b.w/2,b.y+34);}if(b.kind==='breakable'){g.strokeStyle='#8d442c';g.lineWidth=2;g.beginPath();g.moveTo(x+3,b.y+b.h/2);g.lineTo(x+b.w-3,b.y+b.h/2);g.moveTo(x+b.w*.35,b.y+3);g.lineTo(x+b.w*.35,b.y+b.h/2);g.moveTo(x+b.w*.7,b.y+b.h/2);g.lineTo(x+b.w*.7,b.y+b.h-3);g.stroke();}if(b.cracked){g.strokeStyle='#5b302b';g.lineWidth=3;g.beginPath();g.moveTo(x+12,b.y+4);g.lineTo(x+25,b.y+19);g.lineTo(x+18,b.y+34);g.lineTo(x+38,b.y+47);g.stroke();}g.restore();}
      for(const a of e.stage.enemies){if(a.defeated&&a.defeatTime<=0)continue;const x=a.x-c;if(x<-80||x>w+80)continue;this.enemy(a,x,t);}
      for(const shot of e.enemyShots||[]){const x=shot.x-c;g.save();if(shot.kind==='electric-ring'){g.strokeStyle='#fffb9c';g.lineWidth=4;g.shadowColor='#97edff';g.shadowBlur=14;g.beginPath();g.ellipse(x+shot.w/2,shot.y+shot.h/2,shot.w/2,shot.h/2,0,0,Math.PI*2);g.stroke();g.restore();continue;}if(shot.kind==='ink'){g.fillStyle='#342251';g.beginPath();g.ellipse(x+12,shot.y+12,13,11,0,0,Math.PI*2);g.fill();g.restore();continue;}g.shadowColor='#ff6a2f';g.shadowBlur=18;const flame=g.createRadialGradient(x+12,shot.y+9,2,x+12,shot.y+9,15);flame.addColorStop(0,'#fff59a');flame.addColorStop(.45,({ice:'#a5edff',wind:'#bbffff',electric:'#fff659',energy:'#d5a5ff',pinch:'#ffbb9c'})[shot.kind]||'#ffb22e');flame.addColorStop(1,({ice:'#4c9cce',wind:'#72cbbc',electric:'#b093ef',energy:'#8355de',pinch:'#eb7766'})[shot.kind]||'#e83925');g.fillStyle=flame;g.beginPath();g.ellipse(x+12,shot.y+9,15,10,0,0,Math.PI*2);g.fill();g.restore();}
      for(const item of e.stage.items){if(item.contained)continue;if(e.collected.has(item.id)){const age=t-(item.collectedAt??-99);if(item.kind==='letter'&&age<.55){g.save();g.globalAlpha=1-age/.55;this.learningLetter(item,item.x-c+(24-(item.x-c))*age/.55,-age*180);g.restore();}continue;}const x=item.x-c;if(x<-100||x>w+100)continue;const bob=Math.sin(t*3+item.x)*3-(item.pop||0)*18;
        if(theme==='ocean'&&item.kind==='letter'&&this.oceanLetter){this.oceanLetter(item,x,bob);continue;}
        if(item.kind==='letter'||item.kind==='decoy'){
          this.learningLetter(item,x,bob);
        }else {const i={coin:10,star:11,powerStar:11,power:12,flight:12}[item.kind];const cw=item.kind==='coin'?item.w*(.7+.3*Math.abs(Math.cos(t*2))):item.w;if(item.kind==='powerStar'){g.save();g.strokeStyle='#7deaff';g.shadowColor='#fff4a8';g.shadowBlur=22;g.lineWidth=3;g.beginPath();g.arc(x+item.w/2,item.y+bob+item.h/2,item.w*.62,0,Math.PI*2);g.stroke();g.restore();}this.sprite(i,x+(item.w-cw)/2,item.y+bob,cw,item.h);if(item.kind==='flight'||item.kind==='powerStar'){g.fillStyle='#fff';g.font='900 15px sans-serif';g.textAlign='center';g.fillText(item.kind==='flight'?'✦ 날개':'★ POWER',x+item.w/2,item.y-8);}}
      }
      for(const q of e.projectiles||[])this.starlight(q,c);
      if(e.boss&&(!e.boss.unlocked||e.boss.defeatTime>0)){const bx=w-125,by=155,hit=e.boss.hitTime>0,fade=e.boss.unlocked?Math.max(0,e.boss.defeatTime/1.2):1;g.save();g.globalAlpha=fade;g.translate(bx+(hit?Math.sin(t*55)*7:0),by);g.shadowColor=hit?'#fff':e.stage.world.color;g.shadowBlur=hit?42:25;g.fillStyle=hit?'#fff8d1':e.stage.world.color;g.beginPath();g.ellipse(0,0,82+Math.sin(t*3)*3,70,0,0,Math.PI*2);g.fill();g.shadowBlur=0;g.fillStyle='#263147';g.fillRect(-64,-22,128,42);g.fillStyle='#8ff8ff';g.fillRect(-45,-8,26,8);g.fillRect(19,-8,26,8);g.fillStyle=e.stage.world.color;g.beginPath();g.moveTo(-64,-12);g.lineTo(-103,14);g.lineTo(-72,38);g.moveTo(64,-12);g.lineTo(103,14);g.lineTo(72,38);g.lineWidth=18;g.strokeStyle=e.stage.world.color;g.stroke();g.fillStyle='#fff';g.textAlign='center';g.font='900 16px Pretendard';g.fillText(e.stage.boss.name,0,8);g.fillStyle='#261b35';g.fillRect(-78,86,156,15);g.fillStyle='#ffdb55';g.fillRect(-75,89,150*(e.boss.hp/e.boss.maxHp),9);const question=e.stage.boss.questions[Math.min(e.boss.question,e.stage.boss.questions.length-1)];g.font='900 28px Pretendard';g.fillStyle='#fff';g.fillText(question?.[0]||'격파!',0,-91);if(hit){g.font='900 34px Pretendard';g.fillStyle='#fff5a8';g.fillText('정답 공격!',-30,55);}g.restore();}
      if(!e.boss){const goal=e.stage.goal,gx=goal.x-c,active=e.letterCount===e.stage.words.length;g.save();g.translate(gx+goal.w/2,goal.y+goal.h);g.strokeStyle=active?'#fff2a1':'#7ca8ae';g.lineWidth=7;g.beginPath();g.moveTo(0,0);g.lineTo(0,-80);g.stroke();g.shadowColor=active?'#ffe65c':'transparent';g.shadowBlur=active?30:0;g.fillStyle=active?'#fff4a8':'#93aeb3';g.beginPath();for(let i=0;i<10;i++){const r=i%2?12:28,a=-Math.PI/2+i*Math.PI/5;g.lineTo(Math.cos(a)*r,Math.sin(a)*r-82);}g.closePath();g.fill();g.fillStyle=active?'#55d7c1':'#657c82';g.beginPath();g.ellipse(0,3,30,10,0,0,Math.PI*2);g.fill();g.restore();g.textAlign='center';g.font='800 15px Pretendard, sans-serif';g.fillStyle=active?'#155773':'#526c72';g.fillText(active?(e.stage.boss?'보스 입구 · 여기로 와요!':'별빛 신호가 켜졌어요!'):'글자를 모두 모으면 빛나요',gx+goal.w/2,goal.y-18);}
      const p=e.player;this.hero(e,c);if(theme==='ocean'&&this.oceanForeground)this.oceanForeground(e);
      for(const v of e.particles){g.globalAlpha=Math.min(1,v.life*2);this.sprite(11,v.x-c-5,v.y-5,10,10);}g.globalAlpha=1;
      if(e.comboTime>0&&e.combo){g.save();g.globalAlpha=Math.min(1,e.comboTime*1.5);g.fillStyle='#fff5a8';g.strokeStyle='#5c3b64';g.lineWidth=5;g.font='900 22px Pretendard';g.textAlign='center';g.strokeText(e.combo>1?`${e.combo} COMBO!`:'NICE!',p.x-c+p.w/2,p.y-24);g.fillText(e.combo>1?`${e.combo} COMBO!`:'NICE!',p.x-c+p.w/2,p.y-24);g.restore();}
      if(theme==='forest'||theme==='dinosaur')for(let i=0;i<5;i++){const x=i*340-(c*1.12)%340;this.sprite(14,x,502+Math.sin(i)*7,105,55);}
      // Draw distance/position in the scene so assistive status matches visible gameplay.
      g.fillStyle='rgba(255,255,255,.82)';g.beginPath();g.roundRect(16,16,170,30,15);g.fill();g.fillStyle='#235570';g.textAlign='left';g.font='700 13px Pretendard, sans-serif';g.fillText(e.stage.world.name+' · '+Math.floor(p.x/10)+' m',29,36);
    }
  };
  HR.Renderer.prototype.learningLetter=function(item,x,bob){const g=this.g,w=item.w,h=item.h,y=item.y+bob,text=String(item.text);g.save();g.fillStyle='#fff4cf';g.strokeStyle='#b98536';g.lineWidth=2;g.beginPath();g.roundRect(x,y,w,h,8);g.fill();g.stroke();g.fillStyle='#263c50';g.textAlign='center';g.textBaseline='middle';const lines=text.length>3?[text.slice(0,Math.ceil(text.length/2)),text.slice(Math.ceil(text.length/2))]:[text];let size=lines.length===1?(text.length===1?30:22):19;for(;size>10;size--){g.font=`850 ${size}px Pretendard, sans-serif`;if(lines.every(line=>g.measureText(line).width<=w-8))break;}lines.forEach((line,i)=>g.fillText(line,x+w/2,y+h/2+(i-(lines.length-1)/2)*(size+1)));g.restore();};
})(HangulRunner);
