/* Adventure UI adapter. Physics/content/storage stay isolated in their own modules. */
(function(H){
 let active=null,artPromise=null;
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 H.start=async function(){
  if(active)active();Session.begin();game.classList.add('hangul-runner-dialog');
  gameBody.innerHTML='<section class="hr-shell"><div class="hr-loading"><b>시안이의 한글 대모험</b><p>아홉 개의 세계를 펼치고 있어요…</p></div></section>';if(!game.open)game.showModal();
  const root=gameBody.querySelector('.hr-shell');let alive=true,frame=0,controls=null,observer=null,audio=null,engine=null,renderer=null,last=0,acc=0,paused=true,reported=false;
  const stop=()=>{if(!alive)return;alive=false;cancelAnimationFrame(frame);controls?.destroy();observer?.disconnect();audio?.close().catch(()=>{});game.classList.remove('hangul-runner-dialog');root.dataset.activeLoops='0';root.dataset.inputListeners='0';if(active===stop)active=null;};active=stop;Session.cleanups.push(stop);
  let art;try{art=await(artPromise||(artPromise=H.loadArt()));}catch(error){artPromise=null;root.querySelector('p').textContent=error.message;return;}if(!alive)return;
  root.innerHTML=`<div class="hr-top"><div><small>SIANHi · LETTER ADVENTURE</small><h2>한글 달리기 대모험</h2></div><div class="hr-top-actions"><button data-action="sound">♪ 소리</button><button data-action="pause">잠깐 멈춤</button><button data-action="map">월드맵</button><button data-action="back">게임 월드</button></div></div>
   <div class="hr-hud"><b class="hr-stage-name">한글 달리기 월드맵</b><span class="hr-health"></span><span class="hr-treasure"></span><span class="hr-clock"></span></div>
   <div class="hr-viewport"><canvas tabindex="0" aria-label="한글 달리기 게임 화면"></canvas><div class="hr-overlay hr-map-layer"></div><div class="hr-toast" role="status"></div></div>
   <div class="hr-letters" aria-label="모은 글자"></div>
   <div class="hr-bottom"><div class="hr-touch"><button data-control="left" aria-label="왼쪽">←</button><button data-control="right" aria-label="오른쪽">→</button><button data-control="jump" aria-label="위로 또는 점프">↑ <span>위·점프</span></button><button data-control="down" aria-label="아래로">↓</button></div><p class="hr-help">숲: ← → 이동 · ↑ 점프<br>바다·하늘: 상하좌우 이동</p><button data-action="return" hidden>못 찾은 글자 찾기</button></div>`;
  const $=s=>root.querySelector(s),overlay=$('.hr-overlay'),toast=$('.hr-toast'),canvas=$('canvas');let toastUntil=0,lastHud='',sound=!!state.sound;
  renderer=new H.Renderer(canvas,art);
  const gesture=()=>{if(sound&&!audio){const A=window.AudioContext||window.webkitAudioContext;if(A)audio=new A();}audio?.resume?.().catch(()=>{});};
  const chime=kind=>{if(!sound||audio?.state!=='running')return;const o=audio.createOscillator(),v=audio.createGain();o.frequency.setValueAtTime(({death:220,growth:440,shrink:330,blockHit:290,blockBreak:190})[kind]||(kind==='hurt'||kind==='wrong'?170:kind==='letter'?784:523),audio.currentTime);if(kind==='growth')o.frequency.exponentialRampToValueAtTime(880,audio.currentTime+.18);if(kind==='death')o.frequency.exponentialRampToValueAtTime(80,audio.currentTime+.18);v.gain.setValueAtTime(.05,audio.currentTime);v.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.2);o.connect(v);v.connect(audio.destination);o.start();o.stop(audio.currentTime+.21);};
  const message=text=>{toast.textContent=text;toastUntil=performance.now()+2400;toast.classList.add('visible');};
  const progress=()=>H.worldProgress(state);
  const unlocked=id=>{const index=H.worldStages.findIndex(s=>s.id===id);return index===0||!!progress().stages[H.worldStages[index-1].id];};
  function showMap(){paused=true;controls?.reset();$('.hr-stage-name').textContent='한글 달리기 월드맵';$('.hr-health').textContent=`${H.worlds.length} WORLD · ${H.worldStages.length} STAGE`;$('.hr-treasure').textContent=`모험 별 ${state.stars||0}`;$('.hr-clock').textContent='';$('.hr-letters').innerHTML='';overlay.hidden=false;overlay.className='hr-overlay hr-map-layer';
   const p=progress();overlay.innerHTML=`<section class="hr-world-map"><header><small>THE GREAT HANGUL ADVENTURE</small><h3>시안아, 어떤 세계로 떠날까?</h3><p>길을 따라 글자를 모으고 아홉 명의 수호자를 만나 보자!</p></header><div class="hr-world-route">${H.worlds.map((w,wi)=>`<article class="hr-world-card theme-${w.theme}" style="--world:${w.color}"><div class="hr-landmark"><span>${['🌳','🐋','☁️','💎','🦕','❄️','🌋','⚡','🪐'][wi]}</span><i>${wi+1}</i></div><div class="hr-world-copy"><small>WORLD ${w.id}</small><h4>${esc(w.name)}</h4><p>${esc(w.description)}</p><div class="hr-stage-path">${H.worldStages.filter(s=>s.worldId===w.id).map(s=>{const open=unlocked(s.id),done=p.stages[s.id],boss=!!s.boss;return `<button data-world-stage="${s.id}" class="${boss?'boss':''} ${done?'done':''}" ${open?'':'disabled'}><b>${boss?'♛':s.number}</b><span>${boss?'BOSS':s.id}</span>${done?`<em>${'★'.repeat(done.rating)}</em>`:''}</button>`}).join('<i class="hr-path-line"></i>')}</div></div></article>`).join('')}</div></section>`;
   overlay.querySelectorAll('[data-world-stage]').forEach(b=>b.onclick=()=>{gesture();startStage(b.dataset.worldStage);});
  }
  function startStage(id){const stage=H.buildWorldStage(id);engine=new H.WorldEngine(stage,{viewport:renderer.width,onEvent});paused=false;reported=false;last=0;acc=0;lastHud='';overlay.hidden=true;overlay.className='hr-overlay';$('[data-action="return"]').hidden=true;$('.hr-stage-name').textContent=`${id} · ${stage.name}`;$('.hr-letters').innerHTML=stage.words.map((word,i)=>`<span data-letter="${i}">□</span>`).join('');message(stage.story);canvas.focus();updateHud();}
  function clearPanel(result){const idx=H.worldStages.findIndex(s=>s.id===result.stageId),next=H.worldStages[idx+1],worldDone=result.boss;overlay.hidden=false;overlay.innerHTML=`<div class="hr-panel hr-clear"><small>${worldDone?'WORLD CLEAR':'STAGE CLEAR'}</small><h3>${worldDone?'새로운 세계가 열렸어!':'시안아, 해냈어!'}</h3><div class="hr-rating">${'★'.repeat(result.rating)}${'☆'.repeat(3-result.rating)}</div><p class="hr-result-letters">${result.letters.join(' · ')}</p><dl><div><dt>별</dt><dd>${result.stars}</dd></div><div><dt>코인</dt><dd>${result.coins}</dd></div><div><dt>시간</dt><dd>${result.seconds}초</dd></div><div><dt>HP</dt><dd>${result.hp}/3</dd></div></dl>${next?`<button data-next>${worldDone?`WORLD ${next.worldId}로 출발`:'다음 스테이지'} →</button>`:'<p class="hr-grand-clear">🏆 아홉 개의 한글 세계를 모두 구했어!</p>'}<button data-again>한 번 더</button><button data-menu>월드맵</button></div>`;overlay.querySelector('[data-next]')?.addEventListener('click',()=>startStage(next.id));overlay.querySelector('[data-again]').onclick=()=>startStage(result.stageId);overlay.querySelector('[data-menu]').onclick=showMap;}
  function onEvent(e){if(e.type!=='chapter')chime(e.type);if(e.type==='chapter')message(e.text);if(e.type==='letter'){const el=$(`[data-letter="${e.item.index}"]`);if(el){el.textContent=e.item.text;el.classList.add('collected');}message(`${e.item.text}! 잘 찾았어!`);if(sound)say(e.item.text);}if(e.type==='bossTransition'){controls.reset();$('.hr-stage-name').textContent=`${engine.stage.id} · 보스 성으로 이동`;message('모든 글자를 모았어! 보스의 세계로 이동합니다.');}if(e.type==='bossArena'){$('.hr-stage-name').textContent=`${engine.stage.id} · ${e.name} 보스전`;message('문이 닫혔어요. 수호괴수가 나타납니다!');}if(e.type==='bossStart')message('BOSS BATTLE! 공격을 피하고 정답을 찾아요.');if(e.type==='bossAnswer')message(`${e.text} 정답! 별빛 에너지 발사!`);if(e.type==='bossHit')message(`별빛 공격 적중! 보스 HP ${e.hp}`);if(e.type==='bossDefeat')message(`${e.name}를 물리쳤어! 잠시 후 문이 열려요.`);if(e.type==='doorUnlock'){message('문이 열렸어! 직접 문으로 이동해요.');if(sound)say('문이 열렸어요. 출구로 이동하세요.');}if(e.type==='wrong')message('앗, 다른 글자야! 문제를 다시 읽어 보자.');if(e.type==='flight')message('별빛 날개 12초! ↑와 ↓로 날아요.');if(e.type==='flightEnd')message('날개가 쉬어요. 아래 길의 다음 날개를 찾아요.');if(e.type==='growth')message('별빛 열매! 큰 시안으로 자랐어요.');if(e.type==='power'&&engine.player.pendingGrowth)message('넓은 곳으로 나가면 자라요!');if(e.type==='shrink')message('작아졌어요! 반짝이는 동안 안전한 곳으로 가요.');if(e.type==='hurt')message('괜찮아! 반짝이는 동안은 안전해.');if(e.type==='checkpoint')message('쉼터 도착!');if(e.type==='death')message('가장 가까운 쉼터에서 다시 시작해요.');if(e.type==='order')message(`${e.text}부터 찾아보자!`);if(e.type==='missing'){$('[data-action="return"]').hidden=false;message(engine.stage.boss&&engine.sceneState!=='EXIT_OPEN'?'보스를 먼저 물리쳐야 문이 열려요!':'아직 찾지 못한 글자가 있어요!');}if(e.type==='clear'&&!reported){reported=true;const earned=H.recordWorldClear(state,e.result);save();message(`보관함에 별 ${earned}개 추가!`);controls.reset();clearPanel(e.result);}}
  function updateHud(){if(!engine||overlay.classList.contains('hr-map-layer'))return;const p=engine.player,key=[p.hp,p.powerState,Math.ceil(p.flightTime||0),engine.letterCount,engine.coins,engine.stars,Math.floor(engine.elapsed),Math.floor(p.x/10),engine.boss?.hp].join('|');if(lastHud===key)return;lastHud=key;$('.hr-health').textContent=`HP ${p.hp}/3 · ${p.powerState==='big'?'큰 시안':'작은 시안'}${p.flightTime>0?' · 날개 '+Math.ceil(p.flightTime)+'초':''}${engine.boss?' · BOSS '+engine.boss.hp+'/'+engine.boss.maxHp:''}`;$('.hr-treasure').textContent=`글자 ${engine.letterCount}/${engine.stage.words.length} · 별 ${engine.stars} · 코인 ${engine.coins}`;$('.hr-clock').textContent=Math.floor(engine.elapsed/60)+':'+String(Math.floor(engine.elapsed%60)).padStart(2,'0');root.dataset.activeLoops='1';root.dataset.inputListeners=String(controls.listeners.length);}
  function pause(){if(!engine||engine.status==='clear')return;paused=!paused;controls.reset();if(paused){overlay.hidden=false;overlay.innerHTML='<div class="hr-panel"><small>PAUSE</small><h3>잠깐 쉬어 가자.</h3><button data-resume>계속하기</button><button data-menu>월드맵</button></div>';overlay.querySelector('[data-resume]').onclick=()=>{paused=false;overlay.hidden=true;canvas.focus();};overlay.querySelector('[data-menu]').onclick=showMap;}else overlay.hidden=true;}
  controls=new H.Controls(root,pause,gesture);$('[data-action="pause"]').onclick=pause;$('[data-action="map"]').onclick=showMap;$('[data-action="back"]').onclick=openGameWorld;$('[data-action="sound"]').onclick=()=>{sound=!sound;state.sound=sound;gesture();save();message(sound?'게임 소리를 켰어요.':'게임 소리를 껐어요.');};$('[data-action="return"]').onclick=()=>{engine.returnToMissing();$('[data-action="return"]').hidden=true;};
  observer=new ResizeObserver(entries=>{renderer.resize(entries[0].contentRect.width);if(engine)engine.viewport=renderer.width;});observer.observe($('.hr-viewport'));renderer.resize($('.hr-viewport').clientWidth);engine=new H.WorldEngine(H.buildWorldStage('1-1'),{viewport:renderer.width});showMap();
  function loop(t){if(!alive)return;if(!last)last=t;const dt=Math.min(.08,(t-last)/1000);last=t;if(!paused&&engine.status!=='clear'){acc+=dt;while(acc>=1/120){engine.step(1/120,controls.read());acc-=1/120;}}else acc=0;renderer.paint(engine);updateHud();if(t>toastUntil)toast.classList.remove('visible');frame=requestAnimationFrame(loop);}frame=requestAnimationFrame(loop);
 };
})(HangulRunner);
